### ISSUE TITLE
Incorperate leaf age demographics into the FATES model

### ISSUE THREAD

**Issue by serbinsh** [NGEET/fates#100]
### Summary of Issue:

Incorporating leaf age demographics into the FATES model to enable leaf age /phenological control on physiology and RT
### Expected behavior and actual behavior:

NA
### Steps to reproduce the problem (should include create_newcase or create_test command along with any user_nl or xml changes):

NA
### What is the changeset ID of the code, and the machine you are using:

NA
### have you modified the code? If so, it must be committed and available for testing:

NA
### Screen output or output files showing the error message and context:

NA

**Comment by serbinsh** [comment]
@xuchongang FYI - here is a discussion I created on this in 2016.  I think we should set a coordinated development plan on this where we can utilize your implementation and then also build in what we are working on with MAAT that we expect to build into FATES over the next year or so.  Tagging @walkeranthonyp @wujin1985 @alistairrogers here

**Comment by ckoven** [comment]
@serbinsh thanks for re-opening this thread. To me a really key question is what would be the differences between the simple approach in @xuchongang's #432 implementation — where the photosynthesis eqns are calculated using a mean vcmax and jmax across the leaf age cohorts — versus a more expensive solution where we calculate the photosynthesis eqns on each leaf age cohort and take the mean leaf-level fluxes across the age cohorts.  This seems like a question that MAAT is ideally suited to answer.  @walkeranthonyp and I discussed this last week as a possible way to approach reconciling this issue?

**Comment by xuchongang** [comment]
@serbinsh , thank you very much for sharing of the discussion.  It is very useful. I agree with @ckoven to compare the two approaches for differences in MAAT but has the option of two approaches of implementation for computational cost purposes.

**Comment by serbinsh** [comment]
...also just to be clear, I am not advocating for one approach over another.  Just explaining why we have been focused on a specific approach that we had plan to use with MAAT first to test and evaluate, based on the earlier work in GCB.   I personally think we should have options, especially since we want to have predictive ability, yes, but also have a chance to ask questions and play with different assumptions/hypotheses in FATES to see what impacts they have on model simulations.  I would say that this is a great example of how we can facilitate new approaches to modeling seasonality to explore the impacts on our ability to model sites/regions, etc.  Thats what we are interested in going, but use MAAT first allows us to more quickly experiment

**Comment by ckoven** [comment]
this is a thing as of #462; closing.
