### ISSUE TITLE
Leaf orientation index range commented out

### ISSUE THREAD

**Issue by adrifoster** [NGEET/fates#1001]
In `EDSurfaceAlbedoMod` a [line](https://github.com/NGEET/fates/blob/521aee82a25ea0118e7f7b28275bd5fc139384be/biogeophys/EDSurfaceAlbedoMod.F90#L366) capping the PFT parameter `fates_leaf_xl` (leaf orientation index) has been commented out. According to Gordon Bonan's [textbook ](https://www.cambridge.org/core/books/climate-change-and-terrestrial-ecosystem-modeling/7D31B7BC519E3E892EFDC01F0B54F701)(page 238), "this equation is restricted to -0.4 < &chi;<sub>l</sub> < 0.6"

Based off of many of my runs failing (for solar radiation balance check errors) when this parameter is outside those ranges (as well as within... but perhaps a separate issue), I think we should put this capping back.

**Comment by jkshuman** [comment]
Thanks for noting this @adrifoster and providing the reference to Gordon's book. Seems like your testing supports the change.

**Comment by rgknox** [comment]
@adrifoster I like @JessicaNeedham 's idea, and I'd also like to pair that with a graceful fail mechanism during the parameter checks in initialization if a user sets a value of xl outside this range.  If we do this, maybe we don't apply capping in the radiation call, so the two methods don't  diverge
