### ISSUE TITLE
Build failures with NAG compiler: `too many continuation lines`

### ISSUE THREAD

**Issue by glemieux** [NGEET/fates#1010]
In the course of testing https://github.com/ESCOMP/CTSM/pull/1962 on izumi, the fates tests all failed to build with the following error:
```
Error: /home/glemieux/ctsm/src/fates/main/FatesHistoryInterfaceMod.F90, line 2478: Too many continuation lines
```
@ekluzek [noted](https://github.com/ESCOMP/CTSM/pull/1962#issuecomment-1491034972) that this is likely due to a limitation on the number of line continuations, specific to the nag compiler.  The problem line is within the context of the `associate` section, so splitting this section is the solution.

**Comment by rgknox** [comment]
hehe, that is an associate() statement call that spans from line to 2214->2490, thats 276 lines.  Maybe NAG only goes up to 250?  I wonder if the F90 standard allows for nested associate statements and we could split it into two?
