### ISSUE TITLE
Unit discrepancy in FATES_NPP_PF

### ISSUE THREAD

**Issue by JessicaNeedham** [NGEET/fates#1047]
The [units of FATES_NPP_PF](https://github.com/NGEET/fates/blob/fce15a9b3d739f3ea6cc4c8315faea235878b0d6/main/FatesHistoryInterfaceMod.F90#L5455C4-L5455C4) are kg m-2 yr-1 but the description says it is per second. Looking at how it is [calculated](https://github.com/NGEET/fates/blob/fce15a9b3d739f3ea6cc4c8315faea235878b0d6/main/FatesHistoryInterfaceMod.F90#L3023) I think the units should say kg m-2 s-1. This is also the case for [FATES_NPP_SE_PF](https://github.com/NGEET/fates/blob/fce15a9b3d739f3ea6cc4c8315faea235878b0d6/main/FatesHistoryInterfaceMod.F90#L5467).

**Comment by rgknox** [comment]
maybe add this to the TRS PR?
