### ISSUE TITLE
Clean up inventory initialization files

### ISSUE THREAD

**Issue by adrifoster** [NGEET/fates#1062]
Right now the inventory initialization files have a lot of columns that are not used by FATES. This (anecdotally) results in some confusion for new users trying to make init files.

I understand the files are the way they are now so that we can maintain compatibility with ED init files. However, I propose that we clean up the files and make them easier to use, and then we can just write a python tool that will convert an ED init file into a FATES init file so that we can maintain this compatibility. We won't really be able to go from a FATES file to an ED file since the ED file needs more information, but I think this is okay.

**Comment by glemieux** [comment]
Closing per #1104
