### ISSUE TITLE
Logging fractions to product pools parameters

### ISSUE THREAD

**Issue by ckoven** [NGEET/fates#1084]
Currently FATES uses a [single parameter ](https://github.com/NGEET/fates/blob/main/parameter_files/fates_params_default.cdl#L1668)to describe what happens to the wood product that is generated from logging, which is applied across al woody PFTs. Classic CLM and ELM both share a set of PFT-dependent parameters and logic.  @lawrencepj1 tells me that these numbers come from the "Grand Slam protocol", which appears to be this [Houghton et al. 1983 paper](https://esajournals.onlinelibrary.wiley.com/doi/10.2307/1942531)

The CLM & ELM parameters table by PFT, which roughly follow numbers from table 3 of that paper, are pasted below. The first three parameters (pconv, pprod10, and pprod100) are the wood fractions into instantaneous-loss, 10-year, and 100-year product pools resulting from land use change, and the last is the 10-year pool partitioning for forest harvest (so 1-pprodharv10 is the 100-year-pool harvest partitioning). In order to have the global runs with land-use comparable to the non-FATES ones, we should probably update the FATES parameters to at least match this level of complexity, and once there, perhaps there might be some effort to modernize further.  Som reorganization to the code logic (e.g., making the [`site_mass%wood_product` pools](https://github.com/NGEET/fates/blob/main/main/EDTypesMod.F90#L208) pft-indexed) would be needed to do this.

| pftname | pconv | pprod10 | pprod100 | pprodharv10 |
| --- | --- | --- | --- | --- |
| needleleaf_evergreen_temperate_tree   | 0.6 | 0.3 | 0.1 | 0.75 |
| needleleaf_evergreen_boreal_tree  | 0.6 | 0.3 | 0.1 | 0.75 |
| needleleaf_deciduous_boreal_tree  | 0.6 | 0.3 | 0.1 | 0.75 |
| broadleaf_evergreen_tropical_tree   | 0.6 | 0.4 | 0 | 1 |
| broadleaf_evergreen_temperate_tree  | 0.6 | 0.3 | 0.1 | 0.75 |
| broadleaf_deciduous_tropical_tree   | 0.6 | 0.4 | 0 | 1 |
| broadleaf_deciduous_temperate_tree  | 0.6 | 0.3 | 0.1 | 0.75 |
| broadleaf_deciduous_boreal_tree   | 0.6 | 0.3 | 0.1 | 0.75 |
| broadleaf_evergreen_shrub   | 0.8 | 0.2 | 0 | _ |
| broadleaf_deciduous_temperate_shrub   | 0.8 | 0.2 | 0 | _ |
| broadleaf_deciduous_boreal_shrub  | 0.8 | 0.2 | 0 | _ |
| c3_arctic_grass   | 1 | 0 | 0 | _ |
| c3_non-arctic_grass   | 1 | 0 | 0 | _ |
| c4_grass  | 1 | 0 | 0 | _ |

**Comment by sshu88** [comment]
Hi @ckoven, just a quick comment. I would think the harvested forest C from logging (active) to be different from that from land use change (passive) for the future work to add more management options. How about separate and store them into two different variables?

**Comment by ckoven** [comment]
@sshu88, yes that makes sense to me, to store them in different variables within FATES at least, even if they get put in the same pools in the HLMs ultimately.

**Comment by rosiealice** [comment]
So I asked Glen Peters (who is not on GitHub afaik) and he remembered about this paper, which has country-specific product look turnover rates: 

https://www.nature.com/articles/nclimate1535
