### ISSUE TITLE
segmentation fault when writing restart file

### ISSUE THREAD

**Issue by yfang-repo** [NGEET/fates#1158]
FATES-SP:
I see negative lb1/ub1 values 
 when adding print statements here for a large size problem: (https://github.com/NGEET/fates/blob/42d804ba54d0cf013a9737018ff9920e0c9808ea/main/FatesRestartVariableType.F90#L92)

It can not be reproduced with a small size problem. Can anyone point to me where the lb and ub set?  Thanks!

**Comment by yfang-repo** [comment]
It is still related to[https://github.com/NGEET/fates/issues/986].

**Comment by ckoven** [comment]
@yfang-repo seems like it is trying to make too big of an array in the cohort dimension? In SP mode, the size of that vector is determined by `num_swb` here I think? https://github.com/NGEET/fates/blob/42d804ba54d0cf013a9737018ff9920e0c9808ea/main/FatesInterfaceMod.F90#L874

Is the product of the number of gridcells and `num_swb` too big for the integer type that is being used?
