### ISSUE TITLE
History fields not calculated due to "history_dimlevel" are still output (as NaNs)

### ISSUE THREAD

**Issue by adrifoster** [NGEET/fates#1214]
Seemingly, if you don't calculate a history field because of your dimlevel, we still write out the data, as NaNs. This is kind of confusing and I think we should turn off the hist_addfield for that variable if we don't actually calculate it.

@rgknox apologies if this was already discussed and I missed it!

**Comment by rgknox** [comment]
This should be the case, which variable(s) are not doing this? (hoping not all!)

**Comment by adrifoster** [comment]
Actually nevermind I think this might be an issue with a new variable we (@noahlb123 and I) were trying to make. sorry!

**Comment by rgknox** [comment]
phew.. (wipes sweat off brow)
If you notice its a real bug, lets open this again and we will get it fixed.
