### ISSUE TITLE
Logging direct mort condition check bug

### ISSUE THREAD

**Issue by XiulinGao** [NGEET/fates#1289]
https://github.com/NGEET/fates/blob/08f2410fd2a9e04920eedb4cc2d51a09f68127ec/biogeochem/EDLoggingMortalityMod.F90#L346

I was running the logging module with area-based logging approach and found no direct mortality at all. I tracked down to this line of code. As for area-based logging, cur_harvest_tag is set to 2, thus there will never be direct logging mortality resulted from it. 
https://github.com/NGEET/fates/blob/08f2410fd2a9e04920eedb4cc2d51a09f68127ec/biogeochem/EDLoggingMortalityMod.F90#L283

this condition check should be (cur_harvest_tag .eq. 0 .or. cur_harvest_tag .eq. 2).

**Comment by sshu88** [comment]
This tag was designed to be 0 for C-based harvest if biomass match the demand or area-based harvest. Later I have changed this to 2 for area-based harvest thus it can bypass some of the harvest debt calculation in patch dynamics. Thanks for the correction.

**Comment by glemieux** [comment]
Btw, @XiulinGao are you using e3sm or ctsm for this?  I ask as I found an e3sm-side issue that impacts running in this mode: https://github.com/E3SM-Project/E3SM/issues/6806

**Comment by XiulinGao** [comment]
@glemieux I am using ctsm, and I did not run into the harvest mode issue.
