### ISSUE TITLE
is water_memory remembering correctly?

### ISSUE THREAD

**Issue by rgknox** [NGEET/fates#186]
### Summary of Issue:

water memory remembers the water content of the top soil layer over the last 10 days.  It is remembering the instantaneous water content at 0Z, which is not a great thing and needs to be fixed.  The big problem I see is the order of operations in how it saves the water content to the array.

First it assigns index 1 from the boundary condition array.

Then it loops through indices 10 down to 2, assigning the values at those indices from what was in indices 9 to 1.

The problem is that when it is assigning the value to index 2, it is using the value from one which was over-written. I guess its not a huge deal, it is just weighting the first index double.

See phenolog() in EDPhysiologyMod.F90,

**Comment by ckoven** [comment]
going through old code, this can be closed.
