### ISSUE TITLE
clean/refactor phenology

### ISSUE THREAD

**Issue by ckoven** [NGEET/fates#204]
There are a couple issues with respect to phenology that need fixing. I'm just noting this now as a thing to do when we have time.

(1) most of the phenology parameters (effectively everything other than leaf_long, and the flags to use a given routine themselves) are not at the PFT level; thus we can't really have competition by PFT due to differing phenologic traits (other than overall strategy).  perhaps not a big deal for NGT, but this ought to be fixed for all other biomes.  simplest way is to just put the existing code within a PFT loop and calculate each of these site-level phenology switches separately for each PFT using possibly different parameters for each PFT

(2) there's at least one hard-coded PFT parameter that becomes a bug in the new PFT paradigm: https://github.com/NGEET/ed-clm/blob/master/components/clm/src/ED/biogeochem/EDPhysiologyMod.F90#L485
in which it assumes that the drought-deciduous PFT is number 7.  This can (and ought to, at some point soon) be fixed by the above strategy...

**Comment by rgknox** [comment]
this will be addressed in https://github.com/NGEET/fates/pull/862

**Comment by ckoven** [comment]
This issue was closed a while ago because one of the problems identified in it was fixed, but the first point in my initial comment will also finally be fixed by #1392.
