### ISSUE TITLE
init_root_moist_stress never called in the land model

### ISSUE THREAD

**Issue by bishtgautam** [NGEET/fates#208]
### Summary of Issue: 
During initialization, method to compute root moisture stress formulation
is never called.

### Expected behavior and actual behavior:

`call init_root_moist_stress()` should be added in [components/clm/src/main/init_hydrology.F90](https://github.com/NGEET/ed-clm/blob/master/components/clm/src/main/init_hydrology.F90).

### What is the changeset ID of the code, and the machine you are using: 
bc571f9  
### have you modified the code? If so, it must be committed and available for testing: 
No

**Comment by rgknox** [comment]
Surely we can close this by now...?  @billsacks @ekluzek 

Here is where this routine is now called: 
https://github.com/ESCOMP/CTSM/blob/master/src/main/init_hydrology.F90#L33

 (Note this is issue is so old, it pre-dates the split of FATES from CLM when we maintained it as one model, ed-clm).

I'm closing this issue.
