### ISSUE TITLE
refactor  FATES_c_to_litr_<>_c and add restart cabability

### ISSUE THREAD

**Issue by rgknox** [NGEET/fates#217]
Litter fluxes are governed by fates.  On restarts, we ask the host land-models to remember these fluxes for us.  By asking the HLMs to remember this for us, we are adding an extra variable to the pipeline, a variable that is dictated by FATES.  

Specifically, there is a 3 step process that happens right now:

1) bc_out(s)%FATES_c_to_litr_lab_c_col(:) is defined by FATES internals on the dynamics timestep (or during cold-start)

2) bc_out(s)%FATES_c_to_litr_lab_c_col(:) is then transferred into  the HLM structure: soilbiogeochem_carbonflux_inst%FATES_c_to_litr_cel_c_col(c,:) immediately after (also on the dynamics time-step)

3) On every model time-step, inside CNSTateUpdate1:   soilbiogeochem_carbonflux_inst%decomp_cpools_sourcesink_col(c,j,i_met_lit) = soilbiogeochem_carbonflux_inst%FATES_c_to_litr_lab_c_col(c,j) * dt

The structure in the middle (soilbiogeochem_carbonflux_inst%FATES_c_to_litr_cel_c_col(c,:)) is not needed, but we have it added because it is used on restarts in-case restarts are called when we are not restarting on a dynamics call.

Proposal: Remove soilbiogeochem_carbonflux_inst%FATES_c_to_litr_cel_c_col(c,:), along with the lig and lab counterparts.  Save bc_out(s)%FATES_c_to_litr_cel_c_col(j) to the restart, or its internals.  Have  bc_out(s)%FATES_c_to_litr_cel_c_col update soilbiogeochem_carbonflux_inst%decomp_cpools_sourcesink_col directly every model step.

@ckoven and @rosiealice, does this seem feasible to you?

**Comment by ckoven** [comment]
closing as restart problem was solved long ago.
