### ISSUE TITLE
Nutrient-enabled FATES (planning)

### ISSUE THREAD

**Issue by jenniferholm** [NGEET/fates#280]
Goal = develop a nutrient-enabled HLM-FATES model.
Plan = Modularity between the ELM/CLM soil sub-models and the FATES vegetation. So the big-leaf vegetation will not be invoked.
Currently FATES only has carbon, and does not have any nutrient feedbacks between the soil and the vegetation. Additionally FATES only has two prognostic pools, which essentially holds all the vegetation pools. As a first step we need to explicitly prognose each of the carbon pools separately. 

- Discussion points:
Develop the FATES structure to allow for multiple HLM-BGC approaches. For example allow for nutrient schemes from CLM5, ECA, CNP-RD, others(?)

Also See "FatesBGCDynMod.F90" in the HLM for initial development of a module which creates a pathway to call the belowground biogeochemistry code as driven by the FATES vegetation model but bypassing the aboveground CN vegetation code. It is modeled after the CNDriverMod in its call sequence and functionality.

Initial simplistic steps to accomplish this issue, but feedback is requested. I anticipate a separate Github issue for each step (if not more). 

1. Explicitly prognose all the 7 vegetation carbon pools. Leaf, fine root, alive coarse root, dead coarse root, alive stem, dead stem, storage.
1a) Develop prognostic allocation for these vegetation pools. Only the total 'alive' C pool has 'memory' right now.
2. Bring in ability for nutrients; N, P
3. Determine the root uptake given multiple approaches of plant demand and root C:N
4. Develop the leaf level demand, constraints, and final allocation
(Please see the attached powerpoints)

Additional issues to consider =

- Time steps. Currently FATES is daily, but the nutrient competition should be 30 minute. Do the nutrient uptake in 30 minutes, and put into the storage pool for daily resolution.
- For allometry, consider using the Friedlingstein coefficients to scale from fine roots to the rest of the plant. (In FATES all the vegetation all vegetation dynamics are based off of allometry).

Inviting review and discussion on initial planning from @rgknox, @ckoven, @rosiealice, @xuchongang, @serbinsh, @walkeranthonyp.

Tagging to stay updated -- @bchristo, @jkshuman @climate-dude, @pnlfang, @huangmy , @alistairrogers 

[Simple workflow for nutrients in FATES.pptx](https://github.com/NGEET/fates/files/1341983/Simple.workflow.for.nutrients.in.FATES.pptx)

[Review of litter classes in FATES.pptx](https://github.com/NGEET/fates/files/1341985/Review.of.litter.classes.in.FATES.pptx)

RK edit: Added tags

**Comment by rgknox** [comment]
nutrient dynamics are in fates, and these design points are integrated
