### ISSUE TITLE
Current FATES parameter file for greater than 2 PTFs

### ISSUE THREAD

**Issue by jenniferholm** [NGEET/fates#281]
Hi all, 

I wanted to provide an additional FATES parameter file that Ryan and I have worked on that will allow more than 2 PFTs. This is not to be confused with the current, default parameter file, which I think is still - fates_params_2troppftclones.c170810.nc. 
Currently the PFT specific parameters in this file has two indices for 2 PFTs. 

If you would like the capability to run a simulation with more PFTs, please consider using this format and file. You can change the number of PFTs that you would like to use by changing "fates_initd" and "fates_seed_rain". If these values are left as zero, then no PFT will be simulated for that index. 

This parameter file has space for 13 PFTs, and is only a template for if you would like to run more than 2 PFTs. 

DISCLAIMER - the actual parameter fields and values have NOT been tested and validated.
Note - strict PPA is "turned on" in this file
Note - fates_initd is 0.3 for all fields, so all 13 PFTs will run if you use as is. 
Note - all the fates_allom parameters are still the default values from the tropical file, and are not PFT specific. 
Note - there are some "older" parameters that existed prior to FATES (so older CLM parameters). These parameters have been updated with the PFT specific vales from CLM, and correspond to the first 13 PFTs as found in the CLM parameter file, in the same order. Please let me know if this doesn't make sense. 

This is not an "issue" or problem that needs fixing. 

[fates_params.c170929_13pfts.nc.zip](https://github.com/NGEET/fates/files/1345156/fates_params.c170929_13pfts.nc.zip)

**Comment by rgknox** [comment]
out of date, closing
