### ISSUE TITLE
Mapping of parameters that are common with CLM/E3SM 

### ISSUE THREAD

**Issue by rosiealice** [NGEET/fates#311]
@ran-feng, @jkshuman and I were just discussing how to make a parameter file for her miocene simulations that has a grass and an evergreen needleleaf tree. One useful thing here, we noted, would be a flag in the parameter file that could say whether a parameter was equivalent to one in the main model vs whether a parameter is unique to FATES. Then, one could know which parameters could be copied from the default file and which need to have new definitions. 

Given there are probably quite a few people who will want to do this type of parameter file generation, it seems like this would be a useful addition.

On  the other hand, it would put us in a position where we would need to track whether parameters had been deprecated by the host model.

Maybe another solution is just to have a table on the wiki or elsewhere which can give this information broadly to the user community who aren't as familiar with all of the history of these parameter fields. 

What does everyone think? (tagging @aswann  and @kovenock to see if this would be a thing you guys might enjoy)

**Comment by glemieux** [comment]
Closing per https://github.com/NGEET/fates-users-guide/issues/11
