### ISSUE TITLE
Fates ouput: how to convert between classes? CLM variables report Fates info?

### ISSUE THREAD

**Issue by kovenock** [NGEET/fates#321]
Hi @ckoven and @rgknox,

Two questions about Fates output:

1. What additional information do I need to output to calculate PFT level changes in a SCPF and PFT level variables?

For example, I would like to compare changes between simulations in PFT level biomass and GPP. (i.e. I want to know if PFT1 increased in biomass across the site while PFT2 decreased in biomass between a control and an experiment simulation.) I have output for PFTbiomass and GPP_SCPF. What additional information do I need to output to calculate PFT level changes? For example, are there conversion factors, such the area of each PFT/size class, that I need to analyze this output?

Maybe a wiki page about how to integrate up across classes (e.g. from cohort to patch, size class to pft, etc) would be helpful?

2. When I run Fates simulations I still get output for CLM variables (e.g. TLAI). Does CLM output report information for Fates? In other words, does it make sense to analyze output for TLAI when running Fates? And, and if so, at what scale should this information be considered - is it site level?

Thanks in advance for your help and advice.

**Comment by rgknox** [comment]
closing, but feel free to re-open for further discussion @kovenock
