### ISSUE TITLE
Increasing LAI in default run

### ISSUE THREAD

**Issue by rosiealice** [NGEET/fates#339]
Here is a record of the discussion of low LAI we have been having on an email thread. 

@kovenock 
Abby and I are looking for ways to simulate higher LAI ecosystems in our Fates simulations at bci. Currently, we are using the parameter file called fates_params_2troppftclones.c171018.nc. With this parameter set, the annual mean LAI is around 2.2 m2/m2 at 400ppm CO2 (and 2.4 m2/m2 at 800ppm CO2). We think that the initial LAI level could alter the outcome of our competition experiments and would like to test the influence of starting from a higher LAI ecosystem.

Do you have suggestions on how to best increase the LAI at bci in Fates simulations?

Jennifer Holmes has mentioned to me that she has a parameter file for the gf2 site that gives a higher LAI ( ~ 6 or 7 m2/m2 if I remember correctly) but I thought I would check with you first for suggestions and/or advice on what is important to consider.

@ckoven 
We were just talking about this on our recent modeling call.  There are a few issues leading to the low LAI bias in current parameter sets.  One is that we don’t have a healthy understory.  I’m about to submit a PR that reduces respriation rates when a plants carbon stores are low (currently they die at a faster rate, presumably due to deferred maintenance costs, but they don’t actually defer those maintenance costs, which my PR changes).  I’ve tested this and confirmed that it does produce an understory.  A second issue is that, in earlier attempts to have an understory, we specifically reduced the allometric coefficient relating leaf biomass and stem diameter so that a given tree would have a thinner canopy.  The idea was to let light into the understory, but in practive it didn’t work very well, and the net effect was to put a community-level LAI cap on the forest.  So we need to increase this parameter again.

 Rosie was going to do some investigations of whether the canopy trimming logic was also involved in this, but I’m not sure the status of that.

 I’m going to try to kick off some simulations using my respiration-throttling code later today, and will also try a case where I increase the leaf biomass : DBH coefficient.  Hopefully some combination of those will generate decent LAI.

@rosiealice
I have done some experiments increasing the canopy LAI using the minimum canopy spread parameter.  Figures attached. In summaryL

 1) Decreasing the minimum spread (allom_d2ca_coefficient_min) from 0.33 to 0.10 increases LAI from ~2.4 to ~3.5 in the Amazon

 2) In doing so, we appear to turn on the 'trimming' algorithm.

 3) The understory biomass is a) lower in the new parameetization, as expected, and is also significantly more chaotic.

 My feeling is that going from being limited by the maximum allometry to being limited by trimming pushes the model into some kind of alternative state, and ultimately, we do ned to improve the light getting to the understory to make things better.

![screen shot 2018-02-27 at 4 29 17 pm](https://user-images.githubusercontent.com/12954691/36810076-fd32b75e-1c86-11e8-8de1-39fd6c777b48.png)

@rgknox 
Another thing we may want to try is modifying the optical parameters, like backscattering coefficients, and clumping.  If the system is not nutrient or water limited, its light limited. We may be able to see if the carbon balance is as efficient as it should be, which could help us increase LAI, but otherwise, I would guess that we need more light penetration per unit LAI.

 @ckoven 
I still think that of the two separate ways to achieve high LAI of the canopy layer [which are (1) make narrower cylinders with the same leaf biomass:DBH relationship, vs (2) increase the leaf biomass: DBH coefficient], we probably want to be doing more of (2) than (1).  I say that because in principle (1) will tend towards much higher stand densities and therefore biomass.  But I believe that neither our biomass, nor our stand densities are as wrong as our LAI…

@rosiealice
Agreed. Also, however,  if we are invoking trimming at LAI ~3.5 then we'll need to do something to the carbon economics of the lower leaves to get any higher than that as well as increasing the maximum allometric LAI?

**Comment by ckoven** [comment]
this discussion is all out of date now. closing.
