### ISSUE TITLE
Developing FATES within HLM git workflow instructions.

### ISSUE THREAD

**Issue by rosiealice** [NGEET/fates#344]
In the CTSM code management meeting yesterday, we (@billsacks, @ekluzek, @rosiealice, @dlawrenncar & @bandre-ucar) were discussing the need to add FATES-specific workflow to the CTSM GitHub instructions, as a 'Part 3' of this:
https://github.com/ESCOMP/ctsm/wiki/Getting-started-with-CTSM-in-git

From what I can tell, on the FATES wiki, we so far have this documentation for developers, 
https://github.com/NGEET/fates/wiki/FATES-Development-Workflow
which doesn't get a far as telling one how to test and run FATES within the HLM of your choice, a process which appears to be substantially more complicated...

There are a few issues we should try and get agreement on in general, I think, and so I started this issue as a means to allow discussion. e.g. 
- Should we try and flesh out these instructions on NGEET/FATES, or simply point to the relevant instructions in the ACME or CTSM repos?   I think keeping this documented on the HLM repos might be easier to maintain, since changes in the git workflow are slightly more likely to come from that side. But I'm not at all sure that's the only relevant argument. 
- What should the workflow look like?  (where do forks point, when do we run manage externals, etc.) 
- What should one call ones remote repositories (and do we need that to be consistent across different sets of instructions) 

@ekluzek noted that getting these instructions to work smoothly (even in the non-FATES case) is proving challenging. I, for one, am still pretty confused about how this should operate.

Meeting notes from @billsacks are here. 
https://github.com/ESCOMP/ctsm/wiki/CTSM-Meeting-Notes-2018

Thoughts? Additional questions?

**Comment by glemieux** [comment]
Closing this out as I think we have a good handle on this between the CTSM wiki, E3SM confluence pages, and the Fates [User's guide developer's](https://fates-users-guide.readthedocs.io/en/latest/) section.  Will cross post this to the https://github.com/NGEET/fates-users-guide issues board for reference however.
