### ISSUE TITLE
Hourly runs with CLM5-FATES much slower than previous fates-clm HLM FATES combo

### ISSUE THREAD

**Issue by serbinsh** [NGEET/fates#351]
All,
I am working on updating and testing CTSM(CLM5)-FATES in PEcAn, with the current non-expanded parameter file.  I am not sure if I am the only one doing hourly runs right now and/or seeing this issue but, in general, the hourly runs in CLM5-FATES are much slower than before.  This is consistent when outputting only a few variables versus  a lager number of outputs, of both clm and fates. 

I could reduce the model output in PEcAn from hourly to monthly to increase speed but I'm not sure thats what we want to do.  Has anyone else run an hourly run with CLM5-FATES yet?

**Comment by ckoven** [comment]
redundant to the more recent issue #859. closing.
