### ISSUE TITLE
deciduous plants not passing carbon balance

### ISSUE THREAD

**Issue by rgknox** [NGEET/fates#356]
A carbon balance check occurs during different steps of fates dynamics.  The carbon balance is failing in the new multi-pft tests.  So far, the carbon balance checks only fail when deciduous plants are involved.

This problem has existed for some time (half year at least) after discussion with a few people.  Some bugs have been corrected, but apparently more exist.

The current error threshold is a relative error of 10e-6, compared against the total site carbon stock in kgC.  Specifically, the error is how much the differences in the in/out fluxes disagree with the change in total carbon stock for the site.

See routine:  ed_total_balance_check()

https://github.com/NGEET/fates/blob/master/main/EDMainMod.F90#L434

I suppose it is possible that the threshold is just too strict, but that is unlikely.

**Comment by rgknox** [comment]
I ran a 100 year test in a generic tropical environment that included the 14 pfts in the alternative default file.  I turned back on stress deciduous and did not generate any carbon conservation errors.  Thats good!

Will run some f45_f45 multi-decade simulations this week and will report back.  In the mean-time, i downgraded stress decidous from broken to un-supported on the wiki.

https://github.com/NGEET/fates/wiki/Current-Unsupported-or-Broken-Features

**Comment by rosiealice** [comment]
Phew. That's good news. Did you turn on cold deciduous too? They should work the same way, but, you know...

**Comment by rgknox** [comment]
In the tests I did have cold deciduous turned on, and will test them in the f45_f45 simulation too.

**Comment by ckoven** [comment]
this got fixed somewhere along the way. closing.
