### ISSUE TITLE
Scripts to make single site met data?

### ISSUE THREAD

**Issue by rosiealice** [NGEET/fates#361]
Does anyone have scripts to make single site driver data (in monthly netcdf files)?

We currently have at least three sites' San Lorenzo, PNM, and Tanguro (for @jkshuman's fire experiment) for which we generally have a need to make CIME single site driver data (monthly .nc files with temperature, SW radiation, precipitation, windspeed, pressure and relative humidity, and annual .csv files with similar fields in. 

It's not a huge deal to generate this type of script, but if anyone has them lying around, that would be great. I know @rgknox has these but I think he's out of town.  Tagging @jenniferholm @tompowell9 @xuchongang @serbinsh just incase :) 

FWIW, I'm working on a generalized script to do single site runs, based on the one that @rgknox  and @serbinsh had created, into which we should be able to drop these drivers later on. Hopefully that will make for a useful tool for everyone looking at these sites in the end.

**Comment by serbinsh** [comment]
@rosiealice coming back to this, did you ever create your generalized script?  I have developed something for running sites on modex that I can share which I suspect you can tweak for your needs.  In general I still think its a good idea to provide a "toolbox" for end-users with different examples/ways to generate drivers and custom runs, unless that has already happened?

Also, for my Docker development I have a modified python script for generating single-point drivers, using the default CLM forcing data, that can be used to create clm/elm and fates driver files.  Its a WIP but I do hope to make a release version to share, though it perhaps is really only useful to me?  

https://github.com/serbinsh/ctsm_containers/blob/master/tools/create_single_point/python3/create_hlm_driver_data_v2.py

It uses a file like this to define the options:
https://github.com/serbinsh/ctsm_containers/blob/master/tools/create_single_point/python3/config.cfg

This doesn't use the local met, but instead extracts from the cime drivers, much like the matlab tool others have used.  

In addition, it looks like the ncl scripts for generating regional driver "cutouts" still work but the NCAR group seems to be transitioning those functions to a python package

Here is an example single-site script that uses those drivers. Perhaps useful

[create_ctsm-fates_1pt_case_custom_site.txt](https://github.com/NGEET/fates/files/3762253/create_ctsm-fates_1pt_case_custom_site.txt)

**Comment by rgknox** [comment]
the scripts I link above are still there and public.  Feel free to re-open this issue if people have questions.
