### ISSUE TITLE
Make every other NGEE modeling call a 'FATES community' call

### ISSUE THREAD

**Issue by rosiealice** [NGEET/fates#362]
At the DoE DGVM meeting, some of us were discussing how to capitalize on community engagement in the aftermath of the tutorial and the code release. At the moment, we have bi-weekly NGEE-tropics modeling calls (12-1 mountain time, Thursday) and we suggested making **every other call** (right, @ckoven?) of these a FATES community call, at least in the first instance. This would allow coordinate and communication of activities within FATES that are outside of NGEE tropics, with a view to this community increasing as people get their hands on the code. (There are a lot of DoE proposals submitted to use FATES, for example). 

I'm just putting this here as a reminder that we decided to do that, and also to solicit feedback on this idea from people.  We'd try and publicize this via the github repo, the tutorial attendees, etc. 

I guess the main downside is having less time to devote to non-FATES things in the NGEE-tropics calls. 

Thoughts?

**Comment by ckoven** [comment]
All-
Just a reminder that we'll be having our first open FATES development call today at 11am Pacific.  We ended up deciding to just change the purpose of the slot that has been used for the NGEE-T modeling calls and open it to the community; we will therefore be holding these calls every two weeks going forwards.  If you haven't gotten any messages about this and want to, please sign up for the google group at https://groups.google.com/forum/#!forum/fates_model

I am therefore declaring this issue as resolved and closing it.

**Comment by xuchongang** [comment]
Charlie,
  I am not able to call in today due to another commitment at the same
time. Sorry about this and please let me know if there are action items for
me.

Yours
Chonggang
