### ISSUE TITLE
f09_g16.ICLM45ED with multi-dimensioned history variables fails

### ISSUE THREAD

**Issue by rgknox** [NGEET/fates#401]
TRANSFERRED FROM NGEET/fates-clm  (October 2017):

I don't have the fail message, but I wanted to at least make a record of the problem. The f09_g16.ICLM45ED seems to pass ok as long as none of our multi-dimensioned history variables are turned on, like anything with the "SCPF" or "SCAG", etc, conventions. When these types of varialbes are included, we get netcdf or pio errors (I forget which one).
It may be possible that we are encountering the maximum dataset sizes by certain builds of netcdf? But if this is true, I would think that this issue would first show up in the restart files (which are generallly much larger as they contain cohorts).

@huitang-earth  responded in March of 2018:

```
I have encountered similar issues when running f19_g17 resolution with fates-clm as well as CLM5.0-FATES. The PIO errors occur when writing history or restart files.

I have tried two ways to circumvent this problem: (1) increase CPUs, (2) increase "PIO_NUMTASKS" and reduce "PIO_STRIDE" accordingly in "env_run.xml".

As a reference, our machine has 32 cpus/ 64GB mem per node, we use 128 cpus, with PIO_NUMTASKS=16, PIO_STRIDE=8. This works for our case (even with 14 pfts), while the default set up ( PIO_NUMTASKS=4, PIO_STRIDE=32) does not work.

I am not sure if this is a good solution to such problem, or there might be some changes in the code that could solve the problem.

```

**Comment by ckoven** [comment]
this hasn't come up in a year, so we believe it is solved. closing.
