### ISSUE TITLE
FATES needs to run with at least 2 PFTs in the parameter file

### ISSUE THREAD

**Issue by ckoven** [NGEET/fates#404]
This is just a note to document that, as far as is known, FATES needs at least 2 PFTs in the parameter file right now.  If you try to run with just 1 PFT, it rashes during model initialization.  I noticed this a while ago, and failed to make an issue of it. @jkshuman reported that she and I believe @JoshuaRady ran into the problem again.  So I'm making an issue of it now.  There is a simple workaround, which is that the second PFT doesn't actually have to have any cohorts present, so you can set initd in the second PFT to zero and FATES runs fine, there just does have to be a second PFT present.  Also we should identify the cause of this and fix it.

**Comment by rgknox** [comment]
While working on the multi-element refactor, I ran across an issue that may be related.  I created a new history output dimension that was indexed by element type (i.e. C, N or P).  However, during the tests, I was using the carbon only model, which created an output dimension with size = 1.  The dimension of size 1 was creating problems on the CTSM side of history file writing.  Here are fixes that I employed, perhaps it will fix this problem...

https://github.com/rgknox/ctsm/commit/4b21a1318d0c2e13c72cb0ffc5beb5a1912c6a1b

@ckoven 
@ekluzek

**Comment by rgknox** [comment]
I'm hopeful that this issue is now solved.
With PR #524 , we were able to fix an issue on the HLM side of the code that was baring single PFT runs, see previous post.  

I am now running a single PFT simulation at BCI and the model is running fine. If others have single PFT simulations they would like to do, I'd be excited to hear if there simulations are running correctly. Also, I'd like to know if their output is intelligible. I will also be posting what I find.

**Comment by rosiealice** [comment]
Great. That was one of the weirder bugs...

**Comment by jkshuman** [comment]
@katiemurenbeeld is here at NCAR this week to start regional and point runs with single PFTs. @rgknox are you still testing this fix, or can we test this with @katiemurenbeeld runs? Will look at PR #524

**Comment by jkshuman** [comment]
@rgknox see that it was merged into master. will let you know if we run into any issues with single PFTs

**Comment by rosiealice** [comment]
I was running with one PFT and nothing terrible happened...

**Comment by JessicaNeedham** [comment]
I've also had no problem running with a single PFT.

**Comment by rgknox** [comment]
awesome, closing until further notice
