### ISSUE TITLE
Small typo in EDSurfaceAlbedoMod.F90

### ISSUE THREAD

**Issue by jenniferholm** [NGEET/fates#408]
When double checking the albedo output to the HLMs, I found that there was a small typo for the "albi"  parameter. This is the diffuse surface albedo. 

At line 199, in EDSurfaceAlbedoMod.F90, the 'albd_parb' should be 'albi_parb'. 
This section of the code is setting the initial direct and diffuse albedo when there are no leaf layers in the patch. This will matter at the beginning of bare ground simulations, but could also effect albedo during recovery from clear-cuts, or other potential big disturbances. 

line 198: bc_out(s)%albd_parb(ifp,ib) = bc_in(s)%albgr_dir_rb(ib)
line 199: bc_out(s)%albd_parb(ifp,ib) = bc_in(s)%albgr_dif_rb(ib)

Fix should be minor and quick. :)

**Comment by rgknox** [comment]
See:

https://github.com/NGEET/fates/blob/master/biogeophys/EDSurfaceAlbedoMod.F90#L130

I think we are all set here
