### ISSUE TITLE
Bug fixed in E3SM's  FATES-spitfire runs.

### ISSUE THREAD

**Issue by rgknox** [NGEET/fates#419]
@thorntonpe found a bug that affects E3SM simulations with FATES and fire.  The bug is on the E3SM side.  I checked CTSM side, and everything was fine there.

See here, that a buffer is being updated for 24 hour winds and relative humidity. However, there are indexing errors.

https://github.com/E3SM-Project/E3SM/blob/master/components/clm/src/main/atm2lndType.F90#L703

@thorntonpe will fix it in an up-coming PR

**Comment by ckoven** [comment]
@rgknox do you know if this was fixed?

**Comment by glemieux** [comment]
Close per https://github.com/E3SM-Project/E3SM/commit/ba3cf4d53944cafa3de93bdcdf4af4105671eafd.
