### ISSUE TITLE
parameter naming conventions for new allocation and transport parameters

### ISSUE THREAD

**Issue by rgknox** [NGEET/fates#422]
Hi all,

With PR #421, there are a bunch of new parameters, with new dimensions, and some old ones that will be deprecated and folded into the new ones.

**Please voice suggestions or request changes in this thread.** :)

**The hard part**:   _Keep in mind that some parameters may have different meanings under different contexts.  So we have to strike a balance between a parameter having a very descriptive name and being specialized; and having a generic name but able to be re-used in another hypothesis._

---------------------

### Stoichiometry

The existing CN ratios "**froot_cn_ratio**", "**leaf_cn_ratio**" and "**wood_cn_ratio**" are being **removed**. With an expanded and arbitrary number of organs, these organ-specific parameter names need to go.  Also, in the soon to be release CNP model, since we have flexible stoichiometry, we will have target ranges for these ratios, not a single value...

To remove:
```
	float fates_froot_cn_ratio(fates_pft) ;
		fates_froot_cn_ratio:units = "gC/gN" ;
		fates_froot_cn_ratio:long_name = "Fine root C:N" ;
	float fates_leaf_cn_ratio(fates_pft) ;
		fates_leaf_cn_ratio:units = "gC/gN" ;
		fates_leaf_cn_ratio:long_name = "Leaf C:N" ;
	float fates_wood_cn_ratio(fates_pft) ;
		fates_wood_cn_ratio:units = "gC/gN" ;
		fates_wood_cn_ratio:long_name = "Wood C:N" ;

```

These are being replaced by arrays that are dimensioned by PFT x organ  (leaf, fineroot, sapwood, storage, structure, reproduction).  Also, the ratio is inverted, which makes the math cleaner and allows values of zero to essentially turn of a nutrient species if desired.

```
 	float fates_prt_nitr_stoich_p1(fates_prt_organs,fates_pft) ;
		fates_prt_nitr_stoich_p1:units = "(gN/gC)" ;
		fates_prt_nitr_stoich_p1:long_name = "nitrogen stoichiometry" ;
 	float fates_prt_nitr_stoich_p2(fates_prt_organs,fates_pft) ;
		fates_prt_nitr_stoich_p2:units = "(gN/gC)" ;
		fates_prt_nitr_stoich_p2:long_name = "nitrogen stoichiometry, parameter 2 (hypothesis dependant meaning)" ;
 	float fates_prt_phos_stoich_p1(fates_prt_organs,fates_pft) ;
		fates_prt_phos_stoich_p1:units = "(gP/gC)" ;
		fates_prt_phos_stoich_p1:long_name = "phosphorous stoichiometry, parameter 1 (hypothesis dependant meaning)" ;
 	float fates_prt_phos_stoich_p2(fates_prt_organs,fates_pft) ;
		fates_prt_phos_stoich_p2:units = "(gP/gC)" ;
		fates_prt_phos_stoich_p2:long_name = "phosphorous stoichiometry, parameter 2 (hypothesis dependant meaning)" ;

```
------------------

### Growth respiration

In the existing hypothesis, we apply growth respiration as a tax on what is left of the daily integrated GPP minus maintenance respiration costs.  So there is only 1 value per PFT.  But I would like to make this organ specific in other hypotheses.

Proposal 1.  Keep the old parameter to be used with the existing hypothesis.  Use the new parameter which is organ specific for the newer hypotheses.

or...

Proposal 2.  Remove the old parameter, and just use the new parameter.  If the user options to use the old default hypothesis, a run-time check will demand that they specified all growth respiration was uniform across organs.

Old:
```
	float fates_grperc(fates_pft) ;
		fates_grperc:units = "unitless" ;
		fates_grperc:long_name = "Growth respiration factor" ;
```
New:
```
	float fates_prt_unit_gr_resp(fates_prt_organs,fates_pft) ;
		fates_prt_unit_gr_resp:units = "gC/gC" ;
		fates_prt_unit_gr_resp:long_name = "Unit growth respiration rate per organ" ;

```

-------------------------

### Allocation prioritization, turnover and re-translocation:

These are all new parameters, with no analogues...

```
 	float fates_prt_alloc_priority(fates_prt_organs,fates_pft) ;
		fates_prt_alloc_priority:units = "index (0-fates_prt_organs)" ;
		fates_prt_alloc_priority:long_name = "Priority order for allocation" ;
 	float fates_turnover_retrans_mode(fates_pft) ;
		fates_turnover_retrans_mode:units = "index" ;
		fates_turnover_retrans_mode:long_name = "retranslocation method for leaf/fineroot turnover" ;
 	float fates_turnover_carb_retrans_p1(fates_prt_organs,fates_pft) ;
		fates_turnover_carb_retrans_p1:units = "na" ;
		fates_turnover_carb_retrans_p1:long_name = "retranslocation of carbon in turnover, parameter 1 (hypothesis dependant meaning)" ;
 	float fates_turnover_nitr_retrans_p1(fates_prt_organs,fates_pft) ;
		fates_turnover_nitr_retrans_p1:units = "na" ;
		fates_turnover_nitr_retrans_p1:long_name = "retranslocation of nitrogen in turnover, parameter 1 (hypothesis dependant meaning)" ;
 	float fates_turnover_phos_retrans_p1(fates_prt_organs,fates_pft) ;
		fates_turnover_phos_retrans_p1:units = "na" ;
		fates_turnover_phos_retrans_p1:long_name = "retranslocation of phosphorous in turnover, parameter 1 (hypothesis dependant meaning)" ;
```

**Comment by bchristo** [comment]
Very helpful descriptions @rgknox thanks! For growth respiration I vote
proposal 2.

**Comment by serbinsh** [comment]
@rgknox et al.  I like where this is all going, although I do worry about the logistics of dealing with even more parameters, and parameter name changes, in simulations where we are trying to characterize model uncertainties.  In general, how we deal with provide data-driven max/min values for parameters such as leaf_C:N within an uncertainty analysis will need to be thought out, but doable.  

As for growth respiration, I worry about just moving a current unknown from a single parameter designed to capture the residual respiration that we can't actually measure and moving this into a number of smaller but similarly difficult to measure parameters, that, in the end, would still result in the same or more model uncertainty.  Given that we still don't have a good handle on how we parameterize "growth respiration" as a whole, I am not sure how we then can better constrain FATES with a number of additional but smaller "growth respiration parameters" designed to parse out the respiration of each organ. Not sure this is completely clear, I am still trying to figure out how best to express my reservations about this. 

That said, in Dietze et al 2014 there is a good discussion on how we may break apart GR into component parts that may be relevant (pages 293-295).  


Again, my biggest concern now is how we will best understand the sources of variation in FATES simulations where we have additional parameters that we may potentially have a hard time providing observationally-driven or theoretical parameter values

**Comment by rosiealice** [comment]
I might be with @serbinsh on thi. growth respiration, according to everyone I've talked to that 'measures' it, is a very slippery fish indeed, and so it seems pretty ambitious to think that we'll know enough to distinguish different rates for different tissues any time soon...

**Comment by mdietze** [comment]
FWIW, we did follow up on the 2014 paper arguing that we could break apart GR by tissue type. Didn't ever get it published (undergrad project where student graduated and we haven't had time to resurrect), but here's the code https://github.com/mdietze/GrowthRespiration (which assumes you've got PEcAn installed and are calling BETYdb). Did get far enough to show that we could distinguish tissue-specific rates (for at least leaf, stem, and root; didn't look at reproduction; storage is easy if you assume it's 100% sugar & starch). We could also determine which biochemical constituents drove the remaining uncertainty in the GR calculation, but didn't get so far as looking at PFT-specific variation in GR parameters (for that I think we're going to be limited by insufficient data on lignin and lipid concentrations in leaves and roots, but I also know there's more data out there that's not in BETY yet). **IF** I had time, I'd be eager to follow up on this, but I'm over-committed.

**Comment by rgknox** [comment]
I think it is because all things allocation and transport in the plant are so poorly understood, that we want flexibility.  This is also the reason why things are being designed to allow inter-comparison of different hypotheses.  If we know so little about the theory, we can use the model in different ways to evaluate how things might work.  Remember, there is nothing preventing the user from setting all growth respiration parameters to the same value.

**Comment by serbinsh** [comment]
@rgknox @mdietze @rosiealice Thanks for the followup comments.  I had forgot about Mike's unpublished work, I suppose we could take another look at that moving forward if we split GR into various units.  @rgknox I agree that allowing for testing of hypotheses is useful, will just need to think about how to set params via frameworks like PEcAn.

**Comment by rgknox** [comment]
As a follow up from today's model meeting, I will change the growth respiration parameter, as it is presented in the fates file, to revert to its single scalar value.  The inner workings of the PARTEH code itself will continue to have differentiated growth respiration rates of different tissues, which all use the same parameter when called by FATES.

**Comment by rgknox** [comment]
this is super out of date. Half of this was implemented, and half of this was decidely not implemented (ie growth respiration is a whole plant tax on GPP-R_maint).  Closing
