### ISSUE TITLE
Change uppercase "DEBUG" parameters in code to lowercase, interfere's with DEBUG CPP token

### ISSUE THREAD

**Issue by ekluzek** [NGEET/fates#425]
In a ton of FATES module files there is a local module logical parameter called "DEBUG" that is set to .false., by default. The user can then hardcode it to ".true." to get extra diagnostic output. The problem with this is that there is also an uppercase CPP token in CIME called "DEBUG" that then interfere's with this. So we'd like to change all of these instances from all uppercase to all lowercase.

See the related CTSM issue regarding this:

https://github.com/ESCOMP/ctsm/issues/534

**Comment by ekluzek** [comment]
The list of files I see this in are:

biogeochem/EDCanopyStructureMod.F90:  logical, parameter :: DEBUG=.false.
biogeochem/EDCohortDynamicsMod.F90:  logical, parameter :: DEBUG  = .false. ! local debug flag
biogeochem/EDCohortDynamicsMod.F90:     logical, parameter :: FUSE_DEBUG = .false.   ! This debug is over-verbose
biogeochem/EDPhysiologyMod.F90:  logical, parameter :: DEBUG  = .false. ! local debug flag
main/FatesRestartInterfaceMod.F90:  logical, parameter :: DEBUG=.false.

As well as the following:

biogeochem/EDMortalityFunctionsMod.F90
biogeophys/EDAccumulateFluxesMod.F90
biogeophys/EDSurfaceAlbedoMod.F90
biogeophys/FatesPlantRespPhotosynthMod.F90
fire/SFMainMod.F90
main/EDInitMod.F90
main/EDMainMod.F90

So the entire list is:

biogeochem/EDCanopyStructureMod.F90
biogeochem/EDCohortDynamicsMod.F90
biogeochem/EDMortalityFunctionsMod.F90
biogeochem/EDPhysiologyMod.F90
biogeophys/EDAccumulateFluxesMod.F90
biogeophys/EDSurfaceAlbedoMod.F90
biogeophys/FatesPlantRespPhotosynthMod.F90
fire/SFMainMod.F90
main/EDInitMod.F90
main/EDMainMod.F90
main/FatesRestartInterfaceMod.F90

**Comment by ekluzek** [comment]
One way forward with this would be to bring these changes on the NCAR/fates fork and then move them into NGEET/fates master. These changes are desired for the CESM2.1 release which will point to the NCAR/fates version.

**Comment by ekluzek** [comment]
@rgknox yes we do plan on getting basically the latest NGEET/fates into cesm2.1.  So if you can work on this and get into NGEET/fates master that would be great. We need it in a week. If you can't get it in by then, I'll put it on NCAR/fates and we can move it over to NGEET/fates later. So let me know if you can work on this right now. If so, go ahead and put it on master, and it'll be included in the fates update that I do. If not I'll put it on NCAR/fates first.

**Comment by rgknox** [comment]
I can work on integrating these changes immediately. I will also add fixes for #423 as well.
