### ISSUE TITLE
Change numpft to maxveg?

### ISSUE THREAD

**Issue by ekluzek** [NGEET/fates#427]
In CTSM we are considering changing the name of the parameter "numpft" to "maxveg". That more accurately describes that it's not just natural PFT's, but it's also Crop as well.

Right now I see 145 references to numpft in FATES. What do FATES people think about this proposal? Sound OK? We might back off on this, just to make it faster/easier for @slevisconsulting changes come into ctsm. But, I would like to hear opinions on the idea of the change itself.

@slevisconsulting @rgknox

**Comment by rgknox** [comment]
It shouldn't be a problem from the fates side.  In fates, we create our own instance of that variable, and its size is dictated by the parameter file.  So our numpft does not necessarily match CTSM's numpft.

The only requirement that we have in fates is that our numpft does not exceed CTSM's numpft. I've been meaning to add that call where FATES asks CTSM for that value, but have not gotten to it.

But TLDR, this should not be a problem.

**Comment by rgknox** [comment]
@ekluzek , we were wondering if you were suggesting we change things on the FATES side, or was this just a CTSM side change?

**Comment by ekluzek** [comment]
This change has happened in the latest version of CTSM master. So this would be on the fates side to reflect that change. It's not strictly required, but if you want to use a variable name that's the same as what's in CTSM -- you will want to do that. But, if E3SM ELM hasn't changed this -- that might be a reason to stick with the current name.

**Comment by ekluzek** [comment]
Hi @rgknox it looks like this sort of happened in that numpft was changed to maxpft. But, CTSM is using maxveg, and I thought it might be changed to that. But, maybe you decided to keep maxpft as ELM is still using that?

We are completely removing maxpft in CTSM code, and noticed that FATES still has it in place. This is being worked on in https://github.com/ESCOMP/CTSM/issues/881. I'll add this as a point of discussion for next weeks meeting.
