### ISSUE TITLE
net carbon balance for trimming

### ISSUE THREAD

**Issue by rgknox** [NGEET/fates#457]
During photosynthesis, we pass net assimilated carbon for every leaf layer to an array that keeps a running average of how productive each leaf layer is over the course of the year.  This array is only used to inform our trimming functions.  I believe that in the trivial night-time conditions, we have been incorrectly passing a zero net assimilation value, when we should be passing a value equal to - leaf maintenance respiration.
See here:
https://github.com/NGEET/fates/blob/master/biogeophys/FatesPlantRespPhotosynthMod.F90#L941

I ran a 150 year spin-up test at BCI comparing master with the proposed fix.  Surprisingly, there was little impact.  Either way, I checked in with @rosiealice, @ckoven and @walkeranthonyp and there seemed to be concensus that we should be passing back negative leaf respiration at night-time.   I will follow-up with a PR with the fix. More discussion can be added either in that thread or this if need be.

Report:
https://drive.google.com/file/d/1lT9wh8fTH0_ANNVyK8gmAlPmDn5lj16A/view?usp=sharing

**Comment by rosiealice** [comment]
Oh well..I guess it's good that it didn't have a huge effect!

**Comment by rgknox** [comment]
fixed via #459
