### ISSUE TITLE
reduce loop sizes during history diagnostics of productivity

### ISSUE THREAD

**Issue by rgknox** [NGEET/fates#460]
I'm pretty sure the two loops found here:

https://github.com/NGEET/fates/blob/master/main/FatesHistoryInterfaceMod.F90#L2535

can be reduced to the following:

>               do ican=1,cpatch%ncl_p
>                  do ileaf=1,cpatch%ncan(ican,ipft)

**Comment by rgknox** [comment]
note that many terms are also multiplied by cpatch%area * AREA_INV, which can be pre-multiplied.

**Comment by rgknox** [comment]
and a later in the routine, can also be reduced:
https://github.com/NGEET/fates/blob/master/main/FatesHistoryInterfaceMod.F90#L2612

**Comment by ckoven** [comment]
do you know how expensive the history interface routines are?  I feel like a lot of optimization could happen there if it would help.

**Comment by rgknox** [comment]
That one in particular is called every model timestep because it is tracking leaf biophysics and radiation diagnostics.  The subroutine handling dynamics diagnostics only happens once per day though.

**Comment by rgknox** [comment]
there may be a way to pass in the list of active history variables that the land-model is writing, and do a cross-ref against the list of diagnostics calculated in these different schemes.  We could then turn off/on blocks of these diagnostics.

**Comment by ckoven** [comment]
that would be cool.
