### ISSUE TITLE
number of trees changed for static stand structure mode

### ISSUE THREAD

**Issue by pnlfang** [NGEET/fates#461]
The density of trees that’s assigned in the parameter file (fates_recruit_initd) was used to calculate the number of trees (cohort%n) and rhizosphere hydraulic properties.  cohort%n could be reduced in EDCanopyStructureMod.F90 (line 514).  This results in increase of ET.

**Comment by ckoven** [comment]
hi @pnlfang -- you probably don't want to use static stand structure without also using inventory initialization, as the size of the trees in the cold-start initialization will be very small?

**Comment by pnlfang** [comment]
@ckoven -- I increased the size of the trees.
