### ISSUE TITLE
400 day periodicity of cold-deciduous tropical plants?

### ISSUE THREAD

**Issue by rgknox** [NGEET/fates#467]
We have a provision in the phenology logic sequence that will force all cold-deciduous plants to drop their leaves if the time since they last dropped exceeds 400 days.  
I'm just checking in here.  Is this ok? Any thoughts? Can I borrow a feeling?  
I know that these trees would presumably not be competitive in the tropics/sub-tropics (where its not cold-enough to trigger cold-decidous leaf drop) for various other reasons and would die out, but I'm imagining this weird 400 day periodicity for the plants that do somehow compete with tropical evergreens and drought deciduous in the tropics.  Perhaps the problem here is that I am worrying about behavior that should not even manifest in actual plant dynamics.  
Maybe I'm just creeped out seeing "cold-status" triggering in the tropics with 400 day period.
related: #452 
incidentally: https://simpsons.fandom.com/wiki/Can_I_Borrow_A_Feeling%3F

**Comment by rgknox** [comment]
Also: My tests are showing that once cold-deciduous plants drop their leaves due to the 400 day time threshold, they will most likely never go back into a leaf-on status.  This is because one of the conditions to trigger the leaf-on for cold-deciduous is that they had to have encountered at least 1 cold day to properly compare growing degree days.   I suppose if we want to keep this 400 day timer, we can provide some bypass on this cold-day requirement for areas that are obviously warm enough for leaf flushing.   I still think this 400 day leaf-drop is awkward though.

**Comment by jkshuman** [comment]
It seems wrong to have a 400 day period for any region. The leaf longevity term would control how long the trees retain their leaves, and would override this 400 day period, yes? I have been running with deciduous off, but the leaf longevity term has proven important in my testing of competitive dynamics with disturbance. Maybe this 400 day period is a relic? I agree with @rgknox that 400 days seems awkward and wrong.

**Comment by rgknox** [comment]
My understanding now is that the 400 day period, combined with that number of cold-days condition is a way of preventing cold-deciduous in regions that don't experience cold.  It is a little "climate evelopish", but it seems to serve an intended purpose.  Depending on where this conversation goes, I will update the in-code documentation to make this part of the logic clear.

**Comment by rgknox** [comment]
Also,  I think we might be using the wrong "C" parameter from Botta et al:

They calibrated a value of -0.01 +/- 0.001

https://onlinelibrary.wiley.com/doi/epdf/10.1046/j.1365-2486.2000.00362.x

We are using a default of -0.001

https://github.com/NGEET/fates/blob/master/parameter_files/fates_params_14pfts.cdl#L664
https://github.com/NGEET/fates/blob/master/parameter_files/fates_params_default.cdl#L1047
