### ISSUE TITLE
updating fates_next_api to master

### ISSUE THREAD

**Issue by rgknox** [NGEET/fates#469]
We have been using fates_next_api as a place to make changes to the API with FATES, one that we could maintain rapid compatibility between FATES master and a branch in CTSM.

Our thinking was that every so often, we would either fold fates_next_api into CTSM master, or vice versa.

Changes in the cheyenne filesystem, and compatibility needs between CIME, MOSART, RTM, CISM, etc are making a complete set of tests with fates_next_api difficult.

I will start merging CTSM master into fates_next_api, until this is resolved tests with FATES-CLM45 do not seem to be working at the moment.  After we merge master into fates_next_api, I will make a PR back into CTSM master.

cc: @ekluzek @rosiealice @ckoven

**Comment by ckoven** [comment]
seems like this has now been addressed by the recent addition of the fates_main_api CTSM branch by @glemieux. closing.
