### ISSUE TITLE
Failed mkmapdata.sh script in fates_next_api

### ISSUE THREAD

**Issue by jkshuman** [NGEET/fates#470]
@rgknox and @ekluzek @peterhor and @jkshuman were working to get @peterhor single point runs going. He was using the mkmapdata.sh script in ctsm/tools/mkmapdata/ and the script failed due to an old version of intel as well as the ESMBIN_PATH.  We are going to try copying the mkmapdata.sh script from master (which is updated for ctsm) over to his branch in fates_next_api. 

Any other suggestions on getting the domain and path names sorted out if this doesn't work? Will update the post as to the status.

This is related to #469

**Comment by ekluzek** [comment]
That is what I would suggest doing. Just use the version of mkmapdata.sh on master. There should be no changes for the tools for using fates.
