### ISSUE TITLE
Create version of SPITFIRE in MAAT

### ISSUE THREAD

**Issue by jkshuman** [NGEET/fates#474]
Inspired by my struggles in tracking down the source of over active burned fraction in recent FATES-SPITFIRE simulations over the tropics, and @walkeranthonyp LMWG talk about the utility of MAAT in exploring photosynthesis in various models, I was chatting with @walkeranthonyp about getting SPITFIRE into his MAAT format. This would allow us to test the parameter sensitivity outside the model. @rosiealice has an early version of SPITFIRE written in R that can be linked to the MAAT format. I can update that R version with the SPITFIRE updates.

**Comment by walkeranthonyp** [comment]
I added a sister issue in MAAT. 

https://github.com/walkeranthonyp/MAAT/issues/14

@jkshuman @rosiealice if this works for you we can work on getting SPITFIRE into MAAT on that thread and then bring it back here once we're done.

**Comment by rosiealice** [comment]
The R functions I made for SPITFIRE are in Dropbox, here:
https://www.dropbox.com/sh/x8irvqww20q5358/AAC1Mc3_tA-WbLGxaroJ9MTPa?dl=0

**Comment by rgknox** [comment]
closing, issue created in MAAT, feel free to respond and re-open here if needed
