### ISSUE TITLE
update alpha_SH to be a set value, not PFT specific

### ISSUE THREAD

**Issue by jkshuman** [NGEET/fates#476]
@pollybuotte and I were talking through fire parameters. The alpha_SH parameter is currently set to be a PFT specific value, so that the flame height varies based on the PFT.
                   
   EDPftvarcon_inst%fire_alpha_SH(currentCohort%pft) * (currentPatch%FI**0.667_r8) 

https://github.com/jkshuman/fates/blob/e9eb4de6cac81be6c4254031538bb61c44861ae4/fire/SFMainMod.F90#L871-L873

The scorch height is calculated based on this PFT parameter and fire intensity. Fire intensity is calculated from fuel energy and rate of spread. It doesn't make sense to have a fire traveling through a mixed species forest where the flame height changes within a patch based on the PFT. The alpha scorch height parameter in Thonicke et al 2010 made some sense to use at the PFT level as they were using PFT tiles without mixing of PFTs. The mixed PFT composition of FATES should not use a PFT dependent scorch height. Rather scorch height should be computed by the 2/3 law of Byram 1959 relating scorch height and fire intensity. This linear relationship can be modified with a coefficient which might vary regionally. Van Wagner tested this for conifer systems. Suggest looking into VanWagner 1973 (has details of Byram 1959), and the application by Peterson and Ryan (1984) or by Shuman et al 2017.

**Comment by rosiealice** [comment]
Makes sens to me...

**Comment by rosiealice** [comment]
So I read this before I read issue #477. The complication there is to do with the weighting of the SH across PFTs, which makes some attempt to deal with this problem, at least mathematically, but might not make sense scientifically.  The question, I guess, is what we actually mean to represent with the scorch height parameter? Is it a feature of the litter, or of something like crown shape, or is it more to do with the overall canopy structure?
Good that you and @pollybuotte have been getting into the nitty-gritty of this!

**Comment by jkshuman** [comment]
Scorch height (SH) is used specifically to capture tree crown damage as it contributes to tree mortality. From the literature there is an established connection between SH and fire intensity (FI) for forest and shrubland systems (Keeley 2009; Alexander and Cruz 2012; Fernandes et al 2000; Wade 1993; Burrows 1995; Johnson 1992;  Andrews and Rothermal 1982; Van Wagner 1973; Byram 1959). 

The calculation of fire intensity (FI) according to Byram assumes that the fuel is consumed as the flaming front passes, not during smoldering, etc. So, our calculation of FI directly impacts SH. The forward rate of spread (ROS) and fuel consumed determine FI. ROS is strongly altered by the wind speed as shown by results presented at the recent LMWG. I need to open an issue about the impact of wind on ROS, and will post figures there. So it's all connected, and uncertainties/inaccuracies will propagate through subsequent calculations. 

All of this in mind, I think we can reduce the complexity of the SH calculation to conform to the Van Wagner (1973) and Byram (1959) 2/3 linear power law relationship between SH and FI.

Issues with FI and ROS will be handled separately.

**Comment by jkshuman** [comment]
scorch height is a PFT/species level scaler used with the patch level fire intensity (FI) in the application by Van Wagner 1973. This update is addressed with #594

**Comment by jkshuman** [comment]
closing per merge of PR #594
