### ISSUE TITLE
Comment needed to explain 'scpf'

### ISSUE THREAD

**Issue by rosiealice** [NGEET/fates#479]
I was trying to figure out which of the new variables I needed to print out to get GPP through the vertical profile, wrt issue #472. Looking through the HistoryInterface, I came across this reference to 'scpf' at the beginning of the list of scpf variables, which doesn't have any explanation of what it means. 

https://github.com/NGEET/fates/blob/08bb1406bf4de99252cc14faa08a7d2eb651f140/main/FatesHistoryInterfaceMod.F90#L162

Obviously this is documented elsewhere in the code, but I thought that perhaps it is the case that I'm not the only person ever who will try to figure this out in this way. So, can we add a comment to explain what scpf means here?  The same goes for 'scls' further down. 

Apologies for the dunce-hat wearing nature of this comment.

**Comment by ckoven** [comment]
Thanks @rosiealice. I am happy to admit that this is really poorly documented code.  I will write some comments here and a recipe for how to add new variables.

**Comment by rgknox** [comment]
Agreed, this is poorly documented.  Thanks for bringing this to light @rosiealice .

**Comment by ckoven** [comment]
@rosiealice does commit this help? 13bbb78

**Comment by rgknox** [comment]
nice

**Comment by rosiealice** [comment]
Yes, that's very comprehensive :)
