### ISSUE TITLE
define land use drivers for FATES LULCC-v1

### ISSUE THREAD

**Issue by ckoven** [NGEET/fates#491]
In order to keep things moving on the FATES LULCC-v1 (#450), I think a next step should be to define the exact variables that FATES would use to drive the primary to secondary forest transitions in the model.  So I'd like to start discussion on that, and once we agree on exactly what info FATES needs, we can then work outwards from there on putting the LULCC information flow into an interface and having ELM and CLM pass it the info that it needs.

Looking at the CMIP6 drivers, it seems like the relevant fields that we'd want to use initially are the harvest area fields.  So, e.g. looking at either the historical transitions file `multiple-transitions_input4MIPs_landState_CMIP_UofMD-landState-2-1-h_gn_0850-2015.nc`, or one of the future scenario transitions files, e.g. `multiple-transitions_input4MIPs_landState_ScenarioMIP_UofMD-MAGPIE-ssp534-2-1-f_gn_2015-2100.nc`, as downloaded from the input4mips website (https://esgf-node.llnl.gov/search/input4mips/) I see the following fields:

```
	float primn_harv(time, lat, lon) ;
		primn_harv:_FillValue = 1.e+20f ;
		primn_harv:missing_value = 1.e+20f ;
		primn_harv:long_name = "wood harvest area from primary non forest land" ;
		primn_harv:standard_name = "area_fraction" ;
		primn_harv:cell_methods = "time:mean" ;
		primn_harv:units = "1" ;
	float secmf_harv(time, lat, lon) ;
		secmf_harv:_FillValue = 1.e+20f ;
		secmf_harv:missing_value = 1.e+20f ;
		secmf_harv:long_name = "wood harvest area from secondary mature forest land" ;
		secmf_harv:standard_name = "area_fraction" ;
		secmf_harv:cell_methods = "time:mean" ;
		secmf_harv:units = "1" ;
	float secyf_harv(time, lat, lon) ;
		secyf_harv:_FillValue = 1.e+20f ;
		secyf_harv:missing_value = 1.e+20f ;
		secyf_harv:long_name = "wood harvest area from secondary young forest land " ;
		secyf_harv:standard_name = "area_fraction" ;
		secyf_harv:cell_methods = "time:mean" ;
		secyf_harv:units = "1" ;
	float primf_harv(time, lat, lon) ;
		primf_harv:_FillValue = 1.e+20f ;
		primf_harv:missing_value = 1.e+20f ;
		primf_harv:long_name = "wood harvest area from primary forest land" ;
		primf_harv:standard_name = "area_fraction" ;
		primf_harv:cell_methods = "time:mean" ;
		primf_harv:units = "1" ;
	float secnf_harv(time, lat, lon) ;
		secnf_harv:_FillValue = 1.e+20f ;
		secnf_harv:missing_value = 1.e+20f ;
		secnf_harv:long_name = "wood harvest area from secondary non forest land " ;
		secnf_harv:standard_name = "area_fraction" ;
		secnf_harv:cell_methods = "time:mean" ;
		secnf_harv:units = "1" ;
```

I'd propose that we make this information the primary driver data for the initial FATES land use.  Do others agree that this is the simplest first approach?  

If so, a couple further questions:

1. Do we consolidate the forest and non-forest harvest data since, currently, FATES doesn't actually define a forested and non-forested land area fractions?  I.e. should FATES use the sum of forested and non-forested harvested area and just harvest that?  If so, do we do so on the FATES side of the interface, or do we let either (a) the HLMs or (b) some shared preprocessing scripts handle the consolidation?  Or should we pass all the info to FATES as-is and let FATES decide what to do with it?  Either way, do we therefore also need to know what the forested and non-forested fractions that the LUH2 thinks are in a given gridcell so as to take a properly weighted average?
2. Is there an argument for also passing the biomass-based fluxes `secmf_bioh`, `secnf_bioh`, `primf_bioh`, `secyf_bioh`, and `primn_bioh`?  Ideally, it would be nice to be able to run the model with both area-based and mass-based drivers to assess how different the simulations are based on this specification.  If so, should we make that part of the initial LULCC driver or a subsequent step?
3. What is the quantitative distinction between mature and young secondary land?  I.e. if we track secondary forest area in a time-since-anthropogenic disturbance, can we use this data to harvest separately from the patches that are older than or younger than a given age?  I didn't see this in the LUMIP paper so I figured I'd just ask here.
4. What else are we missing here that we'd need to make this work?

cc @dlawrenncar @kvcalvin @lawrencepj1 @bpbond

**Comment by jenniferholm** [comment]
@ckoven - thanks, this is great for starting to define the land use drivers. 

The non-forest land was also one of the first things that jumped out for me. What exactly does "harvest from non forest land" mean? Will this always be a zero value since there is no forest and nothing to harvest, and its just a way for the LULCC driver to keep track of the non-forest (bare ground, lake, urban) area fractions? If so, I think, it seems we need to still keep track of both the forested and non-forested fractions in a given gridcell that LUH2 needs. But since FATES doesn't really have a non-forest fraction, then I think consolidating the two harvest data in the FATES side makes sense. But then after wood-harvest is calculated in FATES, don't we need to un-consolidate back to the weighted averages of forest and non-forest (still in the FATES side) to be passed to the HLM, because LUH2 needs these separately?
I think I need to know what harvest from non forest land exactly means to be able to fully answer this. 

I say yes to passing the biomass carbon fluxes. Especially since it is in the LUH2 input data as you mentioned. 2\. `secmf_bioh`, `secnf_bioh`, `primf_bioh`, `secyf_bioh`, and `primn_bioh`

Time to reach mature status might be different in different biomes (e.g. ~100 years for tropical, much longer for boreal?). Need to look to the literature. Since we're keeping track of patch age, then yes it should be doable to harvest separately from younger and older secondary forests.

**Comment by bpbond** [comment]
Thanks @ckoven 

>1. Do we consolidate the forest and non-forest harvest data since, currently, FATES doesn't actually define a forested and non-forested land area fractions?  I.e. should FATES use the sum of forested and non-forested harvested area and just harvest that?  If so, do we do so on the FATES side of the interface, or do we let either (a) the HLMs or (b) some shared preprocessing scripts handle the consolidation?

My gut reaction is that it's FATES's responsibility to handle the data as-is, i.e. do any consolidation within the model. But don't have a lot of reasoning to back this up.

>2\. Ideally, it would be nice to be able to run the model with both area-based and mass-based drivers

I'm a big fan of "do it initially as simply as possible" but I agree it's tempting to build this in right from the start: either pass in area -> derive biomass, or biomass -> derive area. This could be of huge utility in partitioning sources of variability, seems like.

>3\. What is the quantitative distinction between mature and young secondary land?

🤷‍♂️ @kvcalvin maybe knows?

**Comment by huangmy** [comment]
@ckoven @jenniferholm : 

1. For harvest from non-forest land, I believe it is harvest for fuel wood, which is common in developing countries and not necessarily zero. We should definitely check with @kvcalvin on this. 
2. I think we should pass expected biomass to be harvested to the resource_management structure in FATES, and add a module in FATES to distribute it to different patches, based on biomass/age/area distributions in one gridcell, although we should discuss details on how it should be implemented. This is approximately how it is implemented in CLM5, I believe( @lawrencepj1 and @dlawrenncar, please confirm).  FATES will return an actual biomass harvest and we should allow FATES to say no to harvest when biomass drops below certain threshold. Note that biomass is the actual variable to be exchanged with IAMs, not area, at least in the case of GCAM. 
3. The primary vs mature vs young secondary forests is a hard one, not sure...

**Comment by kvcalvin** [comment]
Thanks, @ckoven. This is really useful.

A few answers -- in theory harvest from non-forest land could be fuel wood, like @huangmy suggests. However, in practice, I think it may have more to do with data mismatches. I know for the future scenarios the IAMs will specify the quantity we want harvested (in m3 or tC) -- if there isn't forest there (or not enough forest), then the harvest will come from non-forested land. For simplicity, it may be best to start with lumping these together. We could later investigate the effects of specifically accounting for fuel wood separately from industrial roundwood.

For biomass vs area, I think @lawrencepj1 may have information here. My understanding is that the area-based harvest can lead to unrealistic harvest quantities in the event that the ESM biomass map looks very different from the LUH2 biomass map. I think this happened in the RCP8.5.

I'm not sure I know the quantitative difference between young and mature forests.

**Comment by ckoven** [comment]
Hi All,

OK, it seems like there is a consensus to include both the area-driven and the biomass-driven land use fluxes.  How to handle the logic of each of them may be complex but at least we can compare them to each other and assess for reasonableness.  Also it doesn't seem like there is a clear answer on the mature versus young secondary forest question, so for now we may as well pass the separate fields to FATES and let FATES decide what to handle it.  Given that these fields all are updated only annually, it doesn't seem like the cost of passing all of this information ought to be very great.

I think a next question to address is how we want to pass some of the parameters to the harvest logic.  Right now the harvest logic by @huangmy et al includes the following parameters, all of which are specified as globally uniform and temporally invariant via the parameter file:

- dbhmin: minimum dbh of trees to harvest
- collateral_frac: fraction of canopy trees killed by collateral damage
- direct_frac: what fraction of trees to harvest (this would be replaced by the LU driver data described above)
- mechanical_frac: fraction of canopy trees killed by mechanical infrastructure (roads, pads, etc)
- coll_under_frac: fraction of understory trees killed by collateral damage
- dbhmax_infra: maximum size of trees killed by infrastructure (since above a certain size its easier to reroute a road around a given tree than to harvest the tree)

In principle all of these might vary spatially and temporally.  Should we let them, and if so how?  

Also I can imagine a couple of other degrees of freedom to the harvest that might maximize the flexibility of how represent anthropogenic disturbance.  In particular:

- dbhmax: could be useful as a management parameter to allow, e.g., thinning of small trees for fire management. This has come up as a thing to do for the California projects.
- thinning_fraction: the same number of trees harvested would result in dramatically different structure of the resulting patch if it was a 100% mortality rate, versus 50% mortality rate on twice the area fraction.    Given the change added in #454 to move trees below the dbhmin size threshold into the disturbed patch, it would be trivial to extend this to allow thinning across size classes to lead to a thinned forest in the newly-disturbed secondary forest patch.  Should we?

Are there any other parameters that we're missing in the list above?

**Comment by huangmy** [comment]
@ckoven and all,

Just a few quick comments on this. 

1. For the same fraction of trees to harvest (direc_frac), we will need to specify different logging practices (e.g., reduced impact logging or conventional logging). In the GMD manuscript, I specified these scenarios by perturbing the parameters but we might want to implement them as options that can be passed through the HLM-FATES interface.

2. It has been shown in tropical managed forest literature that we could assume that the logging practices can be parameterized by linking collateral_frac and mechanical_frac to direc_frac, and that's essential what we did when specifying these parameter values for different logging practices at Tapajos, but we will need to see whether or not we can make similar assumption across the tropics or other forest ecosystems. @mpaiao knows better than I do.

3. My understanding is that in temperate and boreal forests, timber harvest happens more like a crop rotation, rather than selective logging. We might need to account for that too structure-wise.

**Comment by ckoven** [comment]
Hi All,

I've been trying to think this problem through a bit more.  It seems that, rather than specifying each of the logging variables at all gridcells and times, it would be similarly flexible but more tractable to specify a limited number of discrete logging types, e.g. (1) clear cut, (2) selective harvest, etc.  We could add this `logging_type` dimension to the parameter file and index each of the logging parameters on this dimension.  Then we could add a single field to the interface specification, the fraction of logging in each type, which we'd give dimension of gridcell x time x logging_type. Or possibly two fields, one for logging of primary forest and one for logging of secondary forest. When we apply the logging, we could then loop over the logging types (or, more hackishly as a first step, possibly do something like apply type 1 on Jan 1, type 2 on Jan 2, etc). This way we could build a first instance of the simplest case of clear cutting, but then could easily add more diversity to management practices on top of that.  Just wanted to put this proposal out in advance of our call next week focusing on discussion of land use.

A related point: to address the forest rotation issue brought up by @huangmy and possibly resolve the 'young vs mature' secondary forest harvest issue, I guess we could put a rotation age variable as one of the logging_type parameters, which we would then use for applying harvest to secondary forests.

**Comment by ckoven** [comment]
All-
Reporting out from the FATES call last Thursday (4/4).  There was agreement that we want to have FATES ingest land use drivers that are (a) as close to the original driver datasets (e.g. LUH/LUH2) as possible, and (b) that we leave the drivers as general as possible to allow future developments.

The plan is that we'll define the drivers starting from FATES and build out from there to E3SM and CESM, so that we have the possibility of driving FATES with either mass-based or area-based harvest timeseries.  Each of the driving models will then be able to drive FATES once they have the relevant data ingested -- CESM already sounds like it has all the necessary driving data for both area- and mass-based drivers, while E3SM has the capability to drive the model with area-based drivers only, and will add the mass-based capability once E3SM has ingested the LUH2 datasets.

For specifying different types of land use, the plan we agreed on is to have a set of discrete harvest types, with varying parameters for each type.  These parameters will include the current set of land-use drivers, as well as some further ones that we'll add in the future, including maximum size class (as mentioned above, for fire management thinning), the fraction of each plant organ pulled into the various harvest product pools (including a possible indefinite-lifetime product pool to represent BECCS), a minimum rotation age for harvest from secondary forest, possible parameters to represent the intersection of fire and land use, etc. We will then also include a pair of fields with dimension lat x lon x time x harvest_type that represent the fraction of harvest in each type, for both harvest of primary lands and harvest of secondary lands.  For the sake of simplicity, we will allow these fields to be optional, and if not present, it will assume that all the harvest is in type 1, which will represent clear-cut forest harvest.

Next step is thus to build out the drivers for harvest in FATES, and pass these through the interface.  Happy for any interested parties to be involved in helping out with that.
