### ISSUE TITLE
Add _fire_ prefix to parameters

### ISSUE THREAD

**Issue by jkshuman** [NGEET/fates#496]
Add _fire_ to clearly identify parameters as related to SPITFIRE module. Identified in the long name, but not in the parameter name itself. @rgknox thoughts on this? We talked about this at the tutorial when we were counting parameters associated with processes...
for example "fates_fire_low_moisture_Coeff"

fates_low_moisture_Coeff
 fates_low_moisture_Slope 
 fates_mid_moisture 
 fates_mid_moisture_Coeff 
 fates_mid_moisture_Slope 
 fates_min_moisture 
 fates_SAV 
 fates_FBD
 fates_drying_ratio
 fates_durat_slope
fates_fdi_a
fates_fdi_alpha
fates_fdi_b
fates_fuel_energy
fates_max_durat
fates_miner_damp
fates_miner_total
fates_part_dens

**Comment by rgknox** [comment]
prefixes are great, +1 for fates_fire_

**Comment by jkshuman** [comment]
@rgknox can we roll this file modification together with the changes you are making to the seed rain parameter for issue #481 and PR #483 ? I will confirm, but I think it is just these 8 parameters that need the "fates_fire_" update

**Comment by rgknox** [comment]
great idea. Do you have a branch started, or should I just follow your notes on my current working branch for #483 and #503?

**Comment by jkshuman** [comment]
@rgknox I did not start these changes yet. I can roll them into your changes, or you can take charge. It would be good to put them on the same PR was my thought. I will not be able to do this immediately, so depending on how quickly you want to move it into master it may have to wait for a bit.

**Comment by jkshuman** [comment]
@rgknox I just went through to check the list that needed this prefix for fire, and it is much longer than I expected. (I edited the list above, and it is now 18 params.) spitfire is referenced in the long name, but the fire prefix is missing.  Tedious task, so I can do this.

Also fates_FBD

**Comment by jkshuman** [comment]
@rgknox perhaps we can roll this fire param update in with the nutrient refactor?

**Comment by jkshuman** [comment]
resolved via PR #530
