### ISSUE TITLE
woody logic and fire_mort

### ISSUE THREAD

**Issue by rgknox** [NGEET/fates#499]
We have a condition that a plant is woody in order for fire_mort be non-zero.  See here:

https://github.com/NGEET/fates/blob/master/fire/SFMainMod.F90#L1019

But when it comes to generating litter from those rates, we impose the condition again:

https://github.com/NGEET/fates/blob/master/biogeochem/EDPatchDynamicsMod.F90#L964

While I don't think this generating unintended result right now, if we change the logic in the first part, we won't necessarily remember to change the logic on the second part.

Since fire_mort is 0 for non woody plants (as imposed in the SFMainMod.F90 code), is there any reason we can't remove the woody condition in EDPatchDynamicsMod.F90?  

@jkshuman @rosiealice ?

**Comment by rgknox** [comment]
Also, I think we should remove the woody conditionals during sapwood respiration:

https://github.com/NGEET/fates/blob/master/biogeophys/FatesPlantRespPhotosynthMod.F90#L640
https://github.com/NGEET/fates/blob/master/biogeophys/FatesPlantRespPhotosynthMod.F90#L660

While the conditionals kind-of make sense, it is redundant and may be in conflict with the actual mass balance of the plant.  If the plant has zero sapwood, it will respire 0 carbon, whether it is labeled woody or not.

Also, for instance, a user might want to give some non-zero amount of sap to a "non-woody" plant for some experimental or sensitivity purpose.

Maybe we should get rid of the "woody" parameter all-together?  I don't think it is needed, and it is redundant with the allometry parameters.

**Comment by jkshuman** [comment]
Remove "woody" from FatesPlantRespPhoto and EDPatchDynamicsMod? I agree with you for EDPatchDynamics. Seems reasonable for FatesPlantRespPhoto.
We do still need it in SFMainMod to handle the differential fire mortality. Or do you have a thought on how to use another parameter? The woody conditional is a very clear way to distinguish things.
