### ISSUE TITLE
Summary of Model Crashes - March 2019

### ISSUE THREAD

**Issue by rgknox** [NGEET/fates#500]
Description of Crashes:

Crash 1: A cohort with a very large LAI of >30 is created, but this is larger than the array space we have to hold the leaf layers, so the simulation exits.  See issue #495

Crash 2: During the canopy promotion/demotion phase, the model is unable to shuffle cohorts around such that the canopy coverage areas have good agreement with the ground area.  See issue #494

----------------------------------------

Hypothesis of Factors Leading to Recent Errors:  There are no signs that the model has regressed or that new malformed code has been introduced.  Most likely, changes have been recently introduced that have stopped covering-up issues/errors that have been in the code.  

    These new changes are:

    Expanding the maximum canopy layers from 2 to 3
    Reducing the maximum number of leaf layers 
    Increasing the fusion tolerance and decreasing the max number of cohorts

---------------------------------------------

A set of fixes has been introduced that is undergoing testing that seems to be generating stable results:

Fix 1: A genuine bug has been found that was sending plants in the lowest canopy layer to the litter pool (killing them) when they should had been ignored

Fix 2: Charlie’s crown-area fusion conservation algorithm will make the promotion/demotion scheme “smoother”. Promotion/Demotion uses fusion, but if the total crown area changes during fusion, promotion/demotion will constantly be re-shuffling after being affected by this

Fix 3: Charlie and Ryan found that it was important to keep one of the grass biomass pools tied to allometry (like structure is with woody plants). With woody plants, if the structural biomass pool exceeds the maximum structural biomass associated with the tree's stature (dbh), we reset the dbh of the plant so that its maximum structural biomass (aka target biomass) matches the existing structural biomass.  The scenario where actual biomass is higher than the target is an artifact, and one that occurs due to numerical integration error, or because of non-linearity during fusion.  It is important to keep the biomass pools at, or below, the target biomass pool, so that the growth algorithm works correctly.  Grasses, don't have structural biomass, and up to now, we had not been forcing grass plants to have diameters that are tied to a biomass pool (like with woody plants).  In this fix, we tie grasses dbh to root biomass; thus if the root biomass exceeds the carrying capacity of the plant, we increase the dbh to match the root biomass.  As a result, now when fusion generates grass plants with abnormally high leaf biomass relative to its size, the plant's stature is adjusted (increased) and the the leaf area to crown area ratios will gradually reduce until they are within the expected range.  

Fix 4: *A modification of the demotion and promotion logic was introduced to avoid using an iterative solve, and thus reducing number of math operations.  The iterative solve is necessary because the probabalistic demotion/promotion algorithm may impose that 1 or more cohorts demote >100% of their area on the first pass.  The algorithm that rescales these demotion/promotion fractions so they are all <=100% is the complicated part. 

These fixes can be found in the following branch: https://github.com/rgknox/fates/tree/rgknox-demprob-merge-carea

**Comment by ckoven** [comment]
fixed by #501.
