### ISSUE TITLE
Suggest making the default for modules private, so you have to designate what's public

### ISSUE THREAD

**Issue by ekluzek** [NGEET/fates#502]
This is a suggestion, that I want to have some discussion on. I have a PR that will come in that does this for one module. Having public data that is accessible everywhere is evil -- although sometimes a necessary evil. But, something that you want to limit. The biggest problem is if it can be changed everywhere, and a good way to manage that is to use "protected" so that if can only be changed in the parent module. That is something I'm seeing used which is great. I also suggest that as part of the standard boilerplate after declaring "implicit none" you declare, "private" so that all data/subroutines/functions are assumed private rather than public. This makes it a pain to declare something public -- but that's the way it should be -- it should be hard to do something that should be done sparingly. An artifact of NOT doing this is that everything "used" by the module is then public as well, so it can be hard to figure out where data actually lives with a lot of modules that are default public. This last point is the main reason I suggest doing this.

There's a little bit of discussion on this in the CLM Dev guide here...

https://wiki.ucar.edu/display/ccsm/Comprehensive+list+of+standards#Comprehensivelistofstandards-Modularity

**Comment by rgknox** [comment]
@ekluzek , I think setting defaults to private, and using "protected" when possible, is a great suggestion, and I support using this approach in FATES.

**Comment by glemieux** [comment]
@rgknox per our discussion with Charlie today, would you or @ekluzek assign the issue to me please?

**Comment by glemieux** [comment]
I did an audit of the modules this morning and it looks like about 50% of the modules are set `private` by default currently. Many of the others are public by default, but explicitly set to private on a variable-by-variable level.

**Comment by ekluzek** [comment]
The reason to flip it to private by default, is so that you have to explicitly make things public, which is the thing you want to be wary about, rather than private. The worst offender is that anything that's in the "use" list from other modules -- is going to be public -- and you can't make it private to just within the current module. So I'm glad you'll start working on these, thanks for looking into it.

**Comment by glemieux** [comment]
@rgknox I see some of the subroutines in `EDTypesMod.F90` below `contain` being used by other modules by not being called.  Those ones are `dump_cohort` and 'val_check_ed_vars'.  Interestingly it looks like `val_check_ed_vars` isn't being called in `EDTypesMod.F90' itself.  Looks like it was added about 2 years ago: https://github.com/NGEET/fates/commit/df47cfa2fb449614ce559a16f268548368f703ab#diff-14f02c3d54c6afd6502e04e81b2917a6

Has this functionality been superseded?

**Comment by rgknox** [comment]
As for the val_check_ed_vars, it is used as a spot check, and then once things are checked, the call is removed.  ALthough, I don't really use it that often, maybe we should cull it.

The dump_  routines, and the check_var_real  routine are still used frequently though.

**Comment by glemieux** [comment]
Do you want to have those more frequently used subroutines available outside of `EDTypesMod.F90` or are they only to be used internally to the module?

**Comment by rgknox** [comment]
The check_var_real and the dump_ routines should be accessible anywhere in the code.

**Comment by glemieux** [comment]
@rgknox `FatesConstantsMod.F90` is listed as `public` by default in the code:
https://github.com/NGEET/fates/blob/d2f09078f4d5fa7af5b0b4dc31ba16b22667d03a/main/FatesConstantsMod.F90#L1-L8
Since this module is supposed to be global data, I'm wondering if it makes sense to make it `private` by default.  Thoughts?

**Comment by ekluzek** [comment]
Yes, since this is only consisting of public data, and it doesn't include or use anything else -- it might be OK to leave it public. If it's changed to use some other module though, the contents of that module become public -- that's the kind of nastiness you want to avoid. But, this is the safest type of global data it doesn't rely on anything else, and everything is supposed to be a parameter.

Because, it's good to avoid global public data, I think it's actually good to go through the pain of having to declare everything public though. It makes you think about it every time you do it. So I recommend doing it anyway. But, as I said above, this really is a very safe file as is -- so I totally get it if you leave it like it is.

**Comment by glemieux** [comment]
On second thought @ekluzek , I think your argument about the possibility of the module being changed later on down the line is a very good reason to make it private by default.  It's a minor change to bullwark against future Greg's potential oversight :P.

**Comment by glemieux** [comment]
All modules should be private by default now.  Woo!
