### ISSUE TITLE
remove or re-purpose pft_used

### ISSUE THREAD

**Issue by rgknox** [NGEET/fates#503]
We still have the parameter pft_used in the parameter file. It was originally intended to allow the user to keep a pft in the parameter file, but turn-it off or on.  However, it is redundant with the combination of initd (initial density) and external seed rain.  If both of those are zero, you will not get a cohort with said PFT.
Does anyone see any reason to keep this parameter?  It is confusing and misleading new users (it doesn't do anything!).

**Comment by pollybuotte** [comment]
I will confirm that having pft_used as a parameter but not having it turn PFTs on or off is confusing for a new user!  I understand there are two ways to run a case with a subset of the "standard" 14 PFTs.  If I copy the current fates_params_14pfts.nc file and set fates_recruit_initd = 0 and fates_seed_rain = 0 for those PFTs I do not want to use, the case runs.  However, if I use https://github.com/NGEET/fates/blob/master/tools/FatesPFTIndexSwapper.py and select the ENTT, the case fails with this error:

 dtime_sync=         1800  dtime_clm=         1800  mod =            0
 clm: completed timestep            0
 ERROR: ERROR: ERROR in subgridAveMod.F90 at line 950

 Looking at subgridAveMod, it is failing on the column to grid cell averaging.

**Comment by ckoven** [comment]
I agree too that we should get rid of this.  To me, the correct way to not enable a given PFT in a fates run is to delete that PFT from the parameter file. 

I suspect @pollybuotte that you are running into #404.  We should fix and close that issue.

**Comment by pollybuotte** [comment]
Yes, @ckoven, the error comes from running with one PFT.  Thanks.

**Comment by rgknox** [comment]
@pollybuotte , regarding the index swapper, it sounds like you are talking about using on the surface file. It should be used on the fates parameter file.  Did I mis-read that?

**Comment by pollybuotte** [comment]
@rgknox, I was using the idex swapper on the PFT file.

**Comment by rgknox** [comment]
ahh, what is ENTT?

**Comment by pollybuotte** [comment]
Sorry!  My western us-centric shorthand for evergreen needle leaf temperate tree! Not distinguishable from evergreen needle leaf tropical tree.

**Comment by rgknox** [comment]
ok. So in your case I would create a PFT file with the same PFT just listed twice. In my tests I had always treated the two PFTs as clones, each with the same initial density. But it should be fine to set initd = 0 for one of them.

**Comment by pollybuotte** [comment]
I created a file with two pfts and set one of them to initd = 0.  Also set seed_rain = 0 for that pft.  Maybe that's not necessary?  The case is running. Thanks!

**Comment by ckoven** [comment]
@pollybuotte for now it is.  Once we fix #404 that empty PFT shouldn't be needed.

**Comment by rosiealice** [comment]
Agree we should get rid of pft_used.  

I did see some ENT plantations near Sao Paolo one time, so can confirm that ENT's in the tropics don't just die of overheating.

**Comment by rgknox** [comment]
fixed via #530
