### ISSUE TITLE
Some parameters in default file not present in HYDRO default parameter file. 

### ISSUE THREAD

**Issue by rosiealice** [NGEET/fates#505]
I was trying to run a tropical-tree-only simulation with FATES-HYDRO on, and came across the problem that the default parameter file doesn't contain a couple of newer parameters, specifically

fates_senleaf_long_fdrought
fates_drying_ratio

Obviously, this is related to the multiple-file-maintenance issue that is the subject of #444, but I wanted to flag it here incase anyone else is trying to do this. I've made another file which seems to resolve the issue and I'll put it on a branch later.

**Comment by jkshuman** [comment]
I did fix this as I was completing with @huangmy as part of #489. (That one file was not updated with another PR I had, so yes, this will be addressed with only one maintained file.) The file fix is within the SPITFIRE refactor work that is complete and in my repo on branch "SF_fuels_refactor" https://github.com/jkshuman/fates/tree/SF_fuels_refactor. 
@rgknox, @rosiealice  let me know if you want me to fix this as a separate PR, if the refactor is on hold.

**Comment by rgknox** [comment]
this should be close via #514, feel free to re-open if need be
