### ISSUE TITLE
Memory leak in FatesHydro?

### ISSUE THREAD

**Issue by ekluzek** [NGEET/fates#510]
The following test is triggering a memory leak: SMS_Lm3_D_Mmpi-serial.1x1_brazil.I2000Clm50FatesCruGs.hobart_nag.clm-FatesHydro

FAIL SMS_Lm3_D_Mmpi-serial.1x1_brazil.I2000Clm50FatesCruGs.hobart_nag.clm-FatesHydro MEMLEAK memleak detected, memory went from 514.510000 to 574.080000 in 229 days

It looks like that is an excessive increase in memory especially for a single point case. A standard global Fates case does increase in memory, but not nearly as fast (neither in total amount of memory nor as a percent increase).

**Comment by ekluzek** [comment]
There is an allocate statement in this subroutine:

``` fortran
  subroutine InitHydrSites(sites,bc_in,numpft)
.
.
.
          allocate(csite_hydr)
```

I think there needs to be a deallocate statement that mirrors the InitHydrSites allocate above similar to the deallocate in DeallocateHydrCohort from the allocate in InitHydrCohort.

**Comment by rgknox** [comment]
I'm not too worried about that report.  Over the course of half a year, the memory footprint associated with rightfully spawned fates cohorts and patches could change significantly.
These particular allocations should happen once for each site (column), and should then be cleaned up when the execution completes, but they are not dynamically allocated/deallocated during run-time.  I will double check to make sure that is the case though.

**Comment by ekluzek** [comment]
I think we can tell the test what memory range is acceptable. So if it isn't a problem we can tell the test (at least when run from a testlist) that it needs a wider memory range. So I'd like to do that if we think this is OK. But, also look into the issue I brought up in the second comment when looking at the code.

**Comment by rgknox** [comment]
Is there a place in CLM where you guys clean up the memory for columns, LU, etc?  We could put a call in there to clean up FATES memory before the simulation ends.

**Comment by ekluzek** [comment]
Not on an ongoing basis. CLM overall has an allocate at initialization and we rely on the OS to deallocate memory when it closes down the job. Theres some memory at initialization that is deallocated before the run phase, but we don't have ongoing points where we deallocate. For non-transient cases, there wouldn't be anything to deallocate. And for transient cases, you actually keep memory for LU,columns,pfts that aren't active, but will be later and same for ones that become inactive. This is something where fates works in a way that is a lot different than CLM. CLM is pretty static with it's memory, but fates is constantly allocating and deallocating cohorts and patches.

But, as part of the call to run fates, you could check for memory that could be deallocated right?

**Comment by rgknox** [comment]
For fates, treat sites (the csite_hydr hydraulics object), as transient in the same way that columns and LU's are transient, and static.  In other words they are just allocated once at the beginning of the run.  The site objects don't hog much memory, so I see no reason we can't keep them allocated through inactive phases like you do with columns and lus.

As for a check.... I'm thinking extemporaneously here, but maybe there would be some way to calculate the maximum number of cohort and patch objects that should be allowed, and see how many objects are allocated.  If we have memory leaks (which I have not seen any evidence of lately, but there could be!), the allocations would be dereferenced... but maybe fortran can at find all the allocations of each instance?

**Comment by rgknox** [comment]
@ekluzek , should we keep this open, more discussion, close?

**Comment by ekluzek** [comment]
Let's keep it open for discussion. Once, I can change the test so it doesn't show up as an error we could close it. But, right now it does show up as an error, so I'd like to keep it open for that reason. Right now we don't think it's a legit problem with the code, just that from bare ground Fates does ramp up memory quickly. So we do want to change the test so it doesn't show up as an error.

On the other hand I do wonder why this shows up on hobart -- but not cheyenne. I suppose it could be close to triggering on cheyenne,  But, I think it's worth some more work looking into...

**Comment by rgknox** [comment]
ok, it could have a memory leak, so lets keep this open.  I just don't think its related to the "csite_hydro".

**Comment by ekluzek** [comment]
We don't seem to be seeing this as a problem anymore. What it now reports is:

`MEMLEAK insuffiencient data for memleak test`

So I'm closing as a WONTFIX. It might actually have been handled, I just can't really tell.
