### ISSUE TITLE
Add protections to avoid using mortality rates > 100%

### ISSUE THREAD

**Issue by rgknox** [NGEET/fates#528]
I think we need protections to prevent situations where more than 100% of the cohorts are scheduled for mortality.  For instance, I think the user can specify logging rates that are above 100%, and this should create all sorts of problems.

Likewise, I suppose there are strange parameter combinations or contexts that could generate such issues for natural tree-fall as well.

I think we need a few things:

1) Checks during the parameter read-in that will gracefully complain and exit when total logging rates are above 100%.  Also a check to make sure that background mortality is within reason?

2) Checks during run-time that will force mortality rates above 100%, down to 100% if the predicted rate is within some reasonable amount above 100%.   And if the rate is massively higher than 100%, complain and fail.  For the second scenario, we can add a bypass that will allow the user to turn off this protection and squash massive mortality rates down to 100% without error.

**Comment by rosiealice** [comment]
Given mortality rates are annual, doesn't it make some sense that the annual mortality rate could be >100 on a given day?

**Comment by rosiealice** [comment]
I just re-read this and realized I'd interpreted it wrong-ish. I was thinking that you were saying the annual morality rate shouldn't be >100%, but actually you were talking about not making the daily mortality rate >100% (and thus the need to put in place the checks that you mention). 

So, I hereby retract my previous comment...

**Comment by rgknox** [comment]
Agreed, daily is the dangerous one.

**Comment by rgknox** [comment]
after discussion, we realize we have termination mortality protecting us from negative cohort numbers.  Closing this.  Reopen if necessary.
