### ISSUE TITLE
Request removal of the "allpfts" dimension on the params file

### ISSUE THREAD

**Issue by ekluzek** [NGEET/fates#529]
In FatesSynchronizedParamsMod.F90 RegisterParamsScalar the q10_mr and froz_q10 parameters assume the "allpfts" dimension is used on the file. In ctsm we decided that the "allpfts" dimension (which is hardcoded to 1) isn't useful, so we are going away from it.

Could we also do the same in FATES?

**Comment by rgknox** [comment]
This sounds like a good idea @ekluzek.  Is the plan to just use scalars without dimensions then?

**Comment by rgknox** [comment]
Also, in the fates file, we had changed "allpft" to "fates_scalar".  I had been meaning to remove this dimension.

https://github.com/NGEET/fates/blob/master/parameter_files/fates_params_default.cdl#L12

I'm currently putting together a group update to the fates parameter file, this seems like the perfect time to remove fates_scalar.

**Comment by ekluzek** [comment]
@rgknox we are going to remove "allpfts" as a dimension from the CLM paramsfile. So yes any scalars just get read in without a dimension associated with it.

**Comment by ekluzek** [comment]
An update on this. Sam ran into trouble with removing the "allpfts" dimension and getting the same answers. So his update to CTSM probably will NOT have this change. It seemed to work for CLM4.5, but not CLM5.0, which is odd. But, I'm not sure what the end result will be on the CTSM side.

But, if FATES tries to do this you should be aware that we got this surprising change in answers, so you should make sure you don't get that in FATES as well.

**Comment by rgknox** [comment]
Thanks for the heads-up

**Comment by ekluzek** [comment]
OK, the end result was that Sam was able to take allpfts as a dimension out of the bulk of the file in ctsm1.0.dev040. There are still just the two fates variables that have it on now. Below is the start of the thread about this issue. There was a problem in generating the file at first, but changing the way it was done resolved the problem.

https://github.com/ESCOMP/ctsm/pull/684#issuecomment-488859177

**Comment by rgknox** [comment]
@ekluzek , I didn't realize there was an issue with the  q10_mr and froz_q10:

https://github.com/ESCOMP/ctsm/pull/684#issuecomment-486684458

Since this is creating an issue that would require a synchronized fix and an API change, I think it would be better to give FATES access to its own exclusive parameters in its dedicated parameter file.  This would essentially make copies of the parameters and namespace them fates_q10_mr and fates_froz_q10.

**Comment by ekluzek** [comment]
That's true the best thing would be for these parameters to be on a file dedicated for fates. That is unless the intent here is to make sure that fates and CTSM are using the same value for a particular constant. So we should check on that.

**Comment by ckoven** [comment]
@ekluzek there is no real need for these parameters to be synchronized between ctsm and fates.  so best to pull them out as separate parameters.

**Comment by rgknox** [comment]
Yes agreed @ckoven

**Comment by rgknox** [comment]
@ekluzek and @ckoven , fyi:  as of tag sci.1.27.1_api.7.3.0, we maintain all fates parameters in our parameter file.  We also have removed the allpft dimension, and we converted all parameters that had a vector designation with length 1 to a scalar dimension.
