### ISSUE TITLE
Remove main CMakeLists.txt since aren't being used in unit tests

### ISSUE THREAD

**Issue by ekluzek** [NGEET/fates#534]
The CMakeLists.txt file should either be removed, since it currently can't build. Or it should be updated so that it works and a unit test for fates main should be added that does something useful. Since, the purpose of this file is just for unit-testing, it possibly should just be removed until the time that they are added.

In CTSM I'm removing pointing to the fates directory for unit tests until we do have unit tests that could be invoked.

**Comment by glemieux** [comment]
Good timing @ekluzek; I just installed pFUnit on my new machine.  One of the near term goals (next month or so) I was kicking around was to come up with a minimal unit test for fates to get familiar with using pFUnit.  

What do you think @rgknox?  Do you think this is a worthwhile thing to bump up my priority list?

**Comment by ekluzek** [comment]
You can more thoroughly test a lot of code with unit-tests. And if the code you write is unit-testable, it's most likely going to be better code, more modular and easier to work with. So part of the reason to write the unit tests is to end up with better code. You can also do failure testing in unit-tests, we don't really have a way to do that with our system tests.

A question might be is there a module in FATES that would benefit from having unit tests for it? That would provide better test coverage than system tests?

**Comment by rgknox** [comment]
@glemieux , I think unit testing would be a fantastic medium term goal.  I think our allometry module may be a decent candidate for unit testing. It does not rely on (as many) derived type structure, so it may be a good one to start on.   I also think that plant hydraulics may be a good use case.

**Comment by rgknox** [comment]
closing because the change has been issued, we can create a new thread on developing unit tests if need be
