### ISSUE TITLE
normal FATES crash Sierra CZ2 site

### ISSUE THREAD

**Issue by JunyanDing** [NGEET/fates#536]
I ran the normal FATES for pine and oak individually with different combinations of root parameters and vcmax and bb_ slope on Sierra CZ2 site. Oak was set to deciduous. The oak case crashed on 3rd year in Sep. The pine runs ok. The log file is attached.
[cesm.log.txt](https://github.com/NGEET/fates/files/3170535/cesm.log.txt)

**Comment by ckoven** [comment]
Hi @JunyanDing looks like the line numbers don't line up exactly with the code in master, but are you running into this scenario?  if so, perhaps reduce slamax?
https://github.com/NGEET/fates/blob/master/biogeochem/FatesAllometryMod.F90#L702

**Comment by rgknox** [comment]
@JunyanDing , could you  provide the lnd.log file as well?  Also, if you could provide the specific parameter file, or run script, that would help reproduce what is happening.

**Comment by JunyanDing** [comment]
The FATES hash is Faddc742
I ran multiple instance cases. There are 162 lnd.log file. I put 10 of them with the run script in a zip file.
[lnd_0009.log.16895540.zip](https://github.com/NGEET/fates/files/3174717/lnd_0009.log.16895540.zip). 
Thanks! 



 
Thanks!

**Comment by rgknox** [comment]
hash : addc742 

Thanks @JunyanDing ,  I see that this hash is part of 1.22.0_api.7.0.0


This hash was from a pretty unstable period of time from our model (it was crashing a lot then). I would recommend avoiding anything after sci.1.21.0, or before sci.1.26.2.

master is also, provisionally, stable


https://github.com/NGEET/fates/releases

**Comment by JunyanDing** [comment]
Thanks Ryan, I will try another branch. And go through the log files.
I found the code that caused the problem is is FateAllometryMod.F90 (line 712 in that version)

  if( (treelai + tree_sai) > (nlevleaf*dinc_ed) )then
       write(fates_log(),*) 'The leaf and stem are predicted for a cohort, maxed out the array size'
       write(fates_log(),*) 'lai: ',treelai
       write(fates_log(),*) 'sai: ',tree_sai
       write(fates_log(),*) 'lai+sai: ',treelai+tree_sai
       write(fates_log(),*) 'nlevleaf,dinc_ed,nlevleaf*dinc_ed :',nlevleaf,dinc_ed,nlevleaf*dinc_ed
       call endrun(msg=errMsg(sourcefile, __LINE__))
    end if

**Comment by ckoven** [comment]
Hi @JunyanDing  this is a known issue, see here: https://github.com/NGEET/fates/issues/420#issue-364630134

**Comment by rgknox** [comment]
Hopefully that problem will not be an issue with newer code, which may have been fixed via: #501

**Comment by JunyanDing** [comment]
Need to update the codes more often :)

**Comment by rgknox** [comment]
@JunyanDing , it looks like this was resolved, will close, but re-open if needed
