### ISSUE TITLE
Carbon balance failure in smallest size class

### ISSUE THREAD

**Issue by pollybuotte** [NGEET/fates#538]
In testing FATES (with hydro off) at a site in the southern Sierra Nevada with one PFT, I've run into a carbon balance failure in the smallest size class (5.7cm).  I have successfully run with the same parameter file in simulations with initialized, static stand structure (which includes some trees in the 5.7cm class), and prognostic structure initialized with a mature (35cm) stand. However, when I initialize with a 5cm stand, or start from bare ground, the cases fail on the second day of the simulation with a carbon balance error in the smallest size class.

Curiously, the bare ground case has three cohorts in smallest size class in one patch:

![image](https://user-images.githubusercontent.com/30528250/57889295-b50f1900-77f1-11e9-9fe3-0547aeb482de.png)

The initialized case has only two cohorts, but still fails:

![image](https://user-images.githubusercontent.com/30528250/57889366-e556b780-77f1-11e9-8cf0-784bfb113f7c.png)

@ckoven suggested reducing initd.  Reducing from 0.2 to 0.06 there are still 3 cohorts in the bare ground case and a carbon balance failure.

Does this problem look familiar to anyone?

Thanks!

**Comment by rgknox** [comment]
This happens on call index 1, which is tracking the fluxes due to growth and recruitment only.  Its possible that the total mass of new recruits is not being calculated correctly.

Are you running in ST3 mode (I think I read that above, but is it true in all cases that fail)?  Also, could you report on the hashtag of the FATES version you are using?  There were some inconsistencies between phenology and ST3 mode I noticed recently and turned off in recent versions of the code.

**Comment by pollybuotte** [comment]
I get the errors in prognostic stand structure mode.  ST3 mode is working fine.  I'm using Chonggang's latest hydro update, even though I have hydro off, which branched from here:
![image](https://user-images.githubusercontent.com/30528250/57894385-f7415600-7803-11e9-8be8-eb9cbf74fbb9.png)

**Comment by rgknox** [comment]
I think there is potential for mass balance breaking during the recruitment submodule for both prescribed and normal (dynamic) mode now that I look at it.  The scheme calculates a number density of recruits based off of the mass of seed (or the presribed rate), and the expected mass of a single plant that is "on allometry". However, if the new cohort is off allometry, then the actual new mass of the plant will be less than the predicted, and thus and inconsistency.

Other places that could be generating the problem are phenology (but I feel like that would had already triggered errors, but who knows), and growth (but we have several growth mass checks already).

**Comment by ckoven** [comment]
how could a new cohort be off allometry?

**Comment by rgknox** [comment]
if it is created during a drought, it will start off without leaves

**Comment by rgknox** [comment]
although, I guess that seems unlikely in this situation, now that I think of it.  I need to look at create_cohort and the context here again.

**Comment by pollybuotte** [comment]
It seems strange that the model will run in prognostic stand structure mode when I initialize with a stand structure that includes multiple size classes, including 5cm.  And it will run with an initialized stand of all 35cm trees.  But it will not run from bare ground or from an initialization with all 5cm trees.

**Comment by rgknox** [comment]
Its because the error checker uses an error normalized by total mass stocks (which I'm changing in the multi-element release).  So if there is a small mass balance error source that is agnostic of the total biomass, it will seem really large when stocks are low.

**Comment by rgknox** [comment]
looking at the code again, I don't think that disconnect I mentioned above, is actually there.  I see that we do correctly set bleaf = 0 in a logical part of the sequence of things (if leaf-off status).

**Comment by pollybuotte** [comment]
Adjusting several parameters reduces the carbon balance error in the initial cohort class during a simulation from bare ground as follows.

1. leaf biomass allometry: increase leaf biomass for small trees, while not allowing biomass to increase for large trees. Lowest error = 1.69e-4. Still fails on second day of simulation.
2. Increasing the recruit_initd from 0.06 to 0.08.  Error = 1.27e-4. Fails on day 2. Setting to 0.1 increases carbon balance error.
3. Reducing seed_rain from 0.28 to 0.05.  Error = 2.52e-5. Fails on day 459.

Can I turn off seed rain altogether?  I'm running at a 4x4km resolution and it's highly unlikely seed dispersal between grid cells is possible for most tree species in the Sierra Nevada, with the exception of some limited seed dispersal from birds.

@rgknox How certain is the carbon balance error check setting of 10e-6?

**Comment by rosiealice** [comment]
Yes, you can turn seed rain off. It's just to prevent extinctions, things will/should persist from internal recruitment

**Comment by rgknox** [comment]
@pollybuotte , recommend softening the carbon balance error checks for your runs, for the time being. Perhaps set it to 10e-3 (or just turn it off) so you can move forward.  There are some potential changes coming down the pipe that are reducing carbon imbalance errors. 

Meanwhile, It looks like you are using an up-to-date version of the code, but could you check to see if you have the following commit in your branch?

95635c3

**Comment by pollybuotte** [comment]
Thanks @rosiealice and @rgknox.  

I do not have that commit for seed_rain diagnostics in my branch.  Last commit before Chonggang's branch was 82498d5cb18d8e793491ca133989fb20ccd441f7.

Turning off seed rain avoids the carbon balance error for at least 7 years.  I'll be starting a 200 year run soon.

**Comment by rgknox** [comment]
That commit fixed a carbon balance bug related to seed rain.  I would recommend merging master into your branch. Or you can use the cherrypick command to merge that specific commit in.

**Comment by rgknox** [comment]
@pollybuotte .  Can you confirm (or deny) that including the commit mentioned above, does solve your problem?  Will close this up if so.

**Comment by pollybuotte** [comment]
Yes, closing.
