### ISSUE TITLE
unnecessary calls to tree_lai and tree_sai

### ISSUE THREAD

**Issue by rgknox** [NGEET/fates#540]
There are calls to calculate tree lai and tree sai (which is the LAI within the footprint of the plant's crown) here:

https://github.com/NGEET/fates/blob/master/main/EDMainMod.F90#L358
https://github.com/NGEET/fates/blob/master/main/EDMainMod.F90#L377
https://github.com/NGEET/fates/blob/master/main/EDMainMod.F90#L405

As far as I can tell, all three are un-necessary.  LAI is not needed until we either calculate diagnostics, or run the radiation model.  Those both happen after the dynamics step is completed, and the dynamics step will run its canopy summarization and structure routines at the end of the sequence (which will calculate LAI again).

@jkshuman is also triggering errors during the 3rd of these calls, and I believe the issue is as follows: 
1) the plant just grew
2) we did not update crown area to reflect the new DBH
3) the plant has more leaf mass (and also more target leaf mass from dbh), but its trying to cram that into a non-updated crown area.

**Comment by jkshuman** [comment]
@rgknox commenting out those lines as you suggested allows it to run. It is already into year 3.
https://github.com/NGEET/fates/blob/dbc56eaea50dc98f6c26e512eab18fe834cd05b3/main/EDMainMod.F90#L405-L410

**Comment by rgknox** [comment]
resolved via #542
