### ISSUE TITLE
remove cohort variables "lai" and "laimemory"

### ISSUE THREAD

**Issue by rgknox** [NGEET/fates#541]
The cohort variables lai and laimemory have become obsolete.  LAI memory used to hold the LAI on deciduous trees as their leaves fell, however with the new allometry routines, we don't really need to remember this (I think?).  My understanding is that we can re-flush leaves based on the target leaf mass for the size of the plant, and that laimemory does not provide any special information.  @rosiealice, can you confirm this?

The cohort variable "lai" is barely used, and can be derived from cohort variable treelai, crown area and the patch area. It looks like its just taking up memory.

**Comment by rosiealice** [comment]
Sounds good to me. Given we aren't flushing to the actual previous LAI anyway, changes in productivity and/or supply limits from the store, will still mean that the physiological conditions affect the spring leaf dynamics, which was the intent of using lai_memory in the first place..

**Comment by glemieux** [comment]
Updating this conversation with the note that the grass phenology update in #554 mimics the `lai` and `laimemory` convention with `sapwmemory` and `structmemory` which will need to be including in a future refactor.
