### ISSUE TITLE
FatesPFTIndexSwapper.py does not copy doubles

### ISSUE THREAD

**Issue by rgknox** [NGEET/fates#545]
The python tool  FatesPFTIndexSwapper.py assumes that all real numbers are single precision.  Now that the parameter files have been set to double precision, this needs to be fixed.

Identified by @JessicaNeedham  :+1:

**Comment by pollybuotte** [comment]
@rgknox, could this issue lead to run failure when starting from bare ground? I have cases that use a parameter file created with Swapper.py that will run with initialized, static stand structure, but fail with this error in the cesm.log file when starting from bare ground:

forrtl: error (65): floating invalid
Image              PC                Routine            Line        Source             
cesm.exe           000000000390E21D  Unknown               Unknown  Unknown
cesm.exe           000000000390C0B7  Unknown               Unknown  Unknown
cesm.exe           00000000038AE9F4  Unknown               Unknown  Unknown
cesm.exe           00000000038AE806  Unknown               Unknown  Unknown
cesm.exe           0000000003831976  Unknown               Unknown  Unknown
cesm.exe           000000000383C747  Unknown               Unknown  Unknown
Unknown            00002ACA5B2315D0  Unknown               Unknown  Unknown
cesm.exe           00000000038AD43B  Unknown               Unknown  Unknown
cesm.exe           00000000013AEDD6  fateshistoryinter        1651  FatesHistoryInterfaceMod.F90
cesm.exe           0000000000916047  clmfatesinterface        1295  clmfates_interfaceMod.F90
cesm.exe           000000000088BBA6  clm_initializemod         667  clm_initializeMod.F90
cesm.exe           0000000000821D3A  lnd_comp_mct_mp_l         232  lnd_comp_mct.F90
cesm.exe           0000000000459ECC  component_mod_mp_         246  component_mod.F90
cesm.exe           0000000000422149  cime_comp_mod_mp_        1243  cime_comp_mod.F90
cesm.exe           00000000004516AC  MAIN__                    122  cime_driver.F90
cesm.exe           0000000000411E5E  Unknown               Unknown  Unknown
libc.so.6          00002ACA5B4603D5  Unknown               Unknown  Unknown
cesm.exe           0000000000411D69  Unknown               Unknown  Unknown
mpirun noticed that process rank 0 with PID 13378 on node n0064.lr3 exited on signal 6 (Aborted).

 The model date is being passed from the host land model to FATES in line 1651 of FatesHistoryInterfaceMod.

The lnd.log file indicates no errors:

 There will be a total of            1  history tapes
 History tape            1  write frequency =        17520
 All fields on history tape            1  are grid averaged
 Number of time samples on history tape            1  is           31
 Output precision on history tape            1 =           2
 hist_htapes_build hist tape =            1  written with dov2xy=  T
 hist_htapes_build Successfully initialized clm2 history files

I am running with this tag:
commit 6232bb3f495bedee0484445d27e6d09de5c35f3f
Merge: 0cf63a9 8efc24f
Author: Ryan Knox <rgknox@lbl.gov>
Date:   Fri Jun 14 11:00:28 2019 -0700

**Comment by rgknox** [comment]
My gut says its unlikely this is the cause of your problem.  If you want to try updating that swapper tool though, the fix is pretty straight forward:

Change all the instances of the string 'f' to 'd', like in this line:

https://github.com/NGEET/fates/blob/master/tools/FatesPFTIndexSwapper.py#L179

**Comment by rgknox** [comment]
Also, just submitted the fix here:

https://github.com/NGEET/fates/pull/547

**Comment by pollybuotte** [comment]
Your gut was right @rgknox, that was not the problem!  I'll open a new issue, since I still have not found the answer.

**Comment by rgknox** [comment]
ok, thanks for posting, hopefully we can sort it out

**Comment by rgknox** [comment]
I'm going to go ahead and merge this since the changes are trivial and ancillary to the base code

**Comment by rgknox** [comment]
fixed via #547
