### ISSUE TITLE
Update fire_nignitions metadata in parameter file

### ISSUE THREAD

**Issue by jkshuman** [NGEET/fates#557]
Update this value so that it is ignitions (strikes) per year per km2. 
https://github.com/jkshuman/fates/blob/0cf63a938c771e9d72984b2f8fdbf9ff2d5aa836/parameter_files/fates_params_default.cdl#L505
conversion to strikes per day is handled within spitfire module
https://github.com/jkshuman/fates/blob/0cf63a938c771e9d72984b2f8fdbf9ff2d5aa836/fire/SFMainMod.F90#L764

double fates_fire_nignitions ;
		fates_fire_nignitions:units = "ignitions per year per km2" ;
		fates_fire_nignitions:long_name = "number of annual ignitions per square km" ;

**Comment by ckoven** [comment]
while at it, could you change 365 to 365._r8 on
https://github.com/NGEET/fates/blob/master/fire/SFMainMod.F90#L765

**Comment by jkshuman** [comment]
sure thing @ckoven

**Comment by ckoven** [comment]
or, better yet, days_per_year  from https://github.com/NGEET/fates/blob/master/main/FatesConstantsMod.F90#L107

**Comment by ckoven** [comment]
or even better than that, multiply by years_per_day and really speed up the runtime ;)

**Comment by jkshuman** [comment]
closed per PR #561 and merged into master
