### ISSUE TITLE
Inventory cold-starts with HYDRO using un-initialized transpiration (at start?)

### ISSUE THREAD

**Issue by rgknox** [NGEET/fates#559]
The new error trap that was introduced in the last pull request has detected strange behavior:

```
ERROR in plant hydraulics.
 The HLM predicted a non-zero total transpiration flux
 for this patch, yet there is no leaf-area-weighted conductance?
 transp:    1.0000000000000000E+036
 gscan_patch:    0.0000000000000000     
 ENDRUN:ERROR in /home/rgknox/SyncLRC/ctsm2/src/fates/biogeophys/FatesPlantHydraulicsMod.F90 at line 2488     
``` 

This error is triggered when I do a cold-start type simulation, using inventory initialization, with hydro and dynamics turned on (BCI).  The large transpiration value is clearly indicative of an un-initialized value.  Will report back with more as I uncover it.

**Comment by rgknox** [comment]
I checked the call sequence.  Since hydo is called at the end of the canopy_fluxes() iteration loop, even on startup, it seems like transpiration should be calculated prior to it being called.  

I then looked at the interface call, where canopy_fluxes() calls hydro, and preps the boundary conditions, there I printed out the transpiration rates for all the patches:

```
do ifp = 1, this%fates(nc)%sites(s)%youngest_patch%patchno
         p = ifp+col%patchi(c)
         this%fates(nc)%bc_in(s)%swrad_net_pa(ifp) = solarabs_inst%fsa_patch(p)
         this%fates(nc)%bc_in(s)%lwrad_net_pa(ifp) = energyflux_inst%eflx_lwrad_net_patch(p)
         write(iulog,*) 'transfering transp: ',ifp,p,waterflux_inst%qflx_tran_veg_patch(p)
         this%fates(nc)%bc_in(s)%qflx_transp_pa(ifp) = waterflux_inst%qflx_tran_veg_patch(p)
      end do
```

It looks like one patch is not being initialized...

```
 transfering transp:            1           2   0.0000000000000000
 transfering transp:            2           3   0.0000000000000000
 transfering transp:            3           4   0.0000000000000000
 transfering transp:            4           5   0.0000000000000000
 transfering transp:            5           6   0.0000000000000000
 transfering transp:            6           7   0.0000000000000000
 transfering transp:            7           8   0.0000000000000000
 transfering transp:            8           9   1.0000000000000000E+036
 transfering transp:            9          10   0.0000000000000000
 transfering transp:           10          11   0.0000000000000000
```

**Comment by rgknox** [comment]
Here is a proposed fix:

https://github.com/ESCOMP/ctsm/pull/770

I do still think it is strange that one of the FATES patches was not in the exposed vegetation filter though.  This needs to be invetigated as well.  However, the fix proposed above is needed even if we have patches that are not exposed, but should be.  Because, there are definitley concievable cases where we want to run plant hydraulics, even on patches that are not exposed.

**Comment by jenniferholm** [comment]
@rgknox - weird and good discovery that it was one patch was not being initialized. Weird how it's only one patch? Patch monsters strike again. 

Do you plan on doing this fix in ELM git as well?

**Comment by rgknox** [comment]
> Patch monsters strike again.

I can visualize the first FATES t-shirt now.  

That error was generated because the inventory initialization did generate a small patch with no plants on it.  And because of this, the HLMs, rightfully, determined that patch should have no "weight" for its various biophysics schemes.

So, we end up passing in uninitialized transpiration, to a patch with no plants, which would had been fine, but still it fails that new check we added.

The fix I'm submitting should however, prevent some other weird things from happening, like passing unintialized tranpsiration to FATES patches that were covered in snow. In that case, things could get really messed up without the fix.

**Comment by rgknox** [comment]
this has been addressed
