### ISSUE TITLE
when doing inventory initialization, order the patches by the total biomass on the patches?

### ISSUE THREAD

**Issue by ckoven** [NGEET/fates#560]
one of the outcomes of #553 is that we now get multiple patches when we do inventory initializations; prior to that, the size structure was there, but the patch heterogeneity was tending to get collapsed.  an effect of this is that, since all the patches get an age of zero when they are started, they are in kind of a random order in the linked-list structure.  in principle that's fine, as patch order shouldn't affect any of the fates processes, but it makes visualizing from restart files tricky.  I'd like to suggest that we add logic in the inventory initialization that it inserts each new patch into the linked list to sort the patches based on the amount of biomass in the patch, so that we end up with a linked-list order that roughly follows the oldest-to-youngest structure once the model gets going.

**Comment by rgknox** [comment]
@ckoven , are you proposing an age that has some approximate realism consistent with the biomass, or values that are not necessarily realistic yet consistent with biomass rank?

**Comment by ckoven** [comment]
I'm suggesting we keep them all zero aged so as not to make things up, but at least put in an order that makes sense

**Comment by rgknox** [comment]
ok, got it. I suppose if we have two patches with the same age presented to our sorting routine, it won't change their order on us after we set it during inventory init.

**Comment by ckoven** [comment]
right.  separately, if we wanted to speed up the patch fusion during the now-slow first timestep of inventory initialization we could also try tweaking the algorithm to first try to fuse all adjacent patch combinations in the linked list and then do the more off-diagonal combinations second?
