### ISSUE TITLE
Problem with the 2pwr biomass allometry equation

### ISSUE THREAD

**Issue by jkshuman** [NGEET/fates#568]
Working with @acf7m on calibrating biomass allometry for species in Canada. The default equation in the d2bagw is giving us results that are 10 times lower than UVAFME for the region (using a range around the default parameters). We do not think there is a conversion error. The d2bagw_2pwr equation has the form:  bagw    = (p1 * d**p2)/c2b        ; p1=0.07 p2=0.57  [](https://github.com/jkshuman/fates/blob/d95e3564b64a1b93b121098da5909b9435dff36d/biogeochem/FatesAllometryMod.F90#L1658)

If we use the Chojnacky 2014 equation, which is in the d2bagw_2pwr comments [](https://github.com/jkshuman/fates/blob/d95e3564b64a1b93b121098da5909b9435dff36d/biogeochem/FatesAllometryMod.F90#L1647)
and has the form    ! bagw = exp(b0 + b1*ln(diameter))/c2b   ;b0=-3.03 b1=2.55 per the Chojnacky paper then we get reasonable results for picea.

@jenniferholm which agb equation did you use? any thoughts on this d2bagw_2pwr equation?

**Comment by jkshuman** [comment]
The default values in the param file were just way off for application in the boreal. 
We get reasonable values with this equation bagw = (p1 * d**p2)/c2b  with values of p1=0.08 and p2=2.36 for picea
Though there is value in adding the Chojnacky equation form, as you can parameterize it directly from the Chojnacky 2014 paper. Good starting point for more users. I will add in the Chojnacky agb equation as an option.

**Comment by jenniferholm** [comment]
Linking to #550. 

I'm also using the 2pwr allometry equation (d2bagw_2pwr). But not the 2014 Chojnacky equation option. I did a large synthesis of the BAAD database and developed some coefficents from that. 

For spruce I'm using - p1=0.22 and p2=2.2  (when comparing this modeled prediction against some of the BAAD observed biomass data, this did give slightly larger AGB. But FATES was predicting pretty low biomass at first, so I went with these values.)
For the birch, aspen, deciduous type I'm using - p1=0.09 and p2=2.61

**Comment by pollybuotte** [comment]
I'm using the Chojnacky data to parameterize the default d2agb equation with these parameters for ponderosa pine p1=0.25, p2=0.7, p3=2, p4=1.9.  It seems to working pretty well.  You can see how I went went Chojnacky to those parameters here https://docs.google.com/spreadsheets/d/1tnIhJtG0hCOmL2Uf5OHqh7ogCTrJFDoDRJ2S3uxSvkE/edit?usp=sharing

**Comment by jkshuman** [comment]
Thanks @jenniferholm and @pollybuotte. I will look over these resources. We were just in the calibration phase, and are still working on the parameter file. We were testing outside of FATES, and the values were not even in the ballpark. As I said we were able to adjust these to get values that made sense. Once I am done with the param file I may follow up to compare notes on things that are harder to compare to observations (sapwood).
