### ISSUE TITLE
'Nevercold' deciduous plants staging mysterious comeback (without climate triggers being triggered)

### ISSUE THREAD

**Issue by rosiealice** [NGEET/fates#574]
Despite FATES best efforts with the 'nevercold' logic, it seems, sadly, that the cold deciduous plants are coming back to life in the tropics (seemingly without actually triggering any of our climate switches) :( 

At this point, my primary suspicion is to do with how PARTEH handles the status of new recruits, but I admit that I am not expert enough in PARTEH to figure out what happens with the initialization of cohort%status and bleaf (sorry for being behind on your efforts @rgknox)

Anyway, I've put all this in the form of a short story on Jupyter.  I hope you enjoy it...
https://github.com/rosiealice/jupyter_notes/blob/master/python_scripts/FATES_cold_dec.ipynb

(noting that I've been having intermittant success with getting these notebooks to render on git, it seems like it might just be a thing which is flaky/arbitrarily variable in time)

**Comment by rgknox** [comment]
Still looking through code to see if I can understand what is happening.  I see that the nevercold flag seems to be correct, but indeed there should not be leaves.

PARTEH doesn't actually know what the status of a cohort is.  

Carbon should only flow to leaves if it fills these conditions:

1) if the storepriority parameter is non-zero and the plant is evergreen, some carbon to flow to build leaves, even if there has been no GPP.  (this does not seem to be the case, as you don't have evergreens)

https://github.com/NGEET/fates/blob/master/parteh/PRTAllometricCarbonMod.F90#L475



2) After that, the plant needs to have positive carbon balance to build more leaves, which should not be possible unless there was bud-burst.

https://github.com/NGEET/fates/blob/master/parteh/PRTAllometricCarbonMod.F90#L546


So my guess, is there is something weird going on with either the recruitment, or bud-burst. Will look at that next.

**Comment by rgknox** [comment]
Bud burst only happens in two locations:
For cold deciduous here:
https://github.com/NGEET/fates/blob/master/biogeochem/EDPhysiologyMod.F90#L947

For drought deciduous here:
https://github.com/NGEET/fates/blob/master/biogeochem/EDPhysiologyMod.F90#L1007

I double checked those calls, and it seems that you won't get flushing during the nevercold status.  Seems it should only trigger when the site is in a phen_cstat_notcold state.

https://github.com/NGEET/fates/blob/master/biogeochem/EDPhysiologyMod.F90#L933

Let me know if it looks like I'm missing anything.

**Comment by rgknox** [comment]
Its possible this logic during recruitment is not doing what we think it is doing?

https://github.com/NGEET/fates/blob/master/biogeochem/EDPhysiologyMod.F90#L1356

Is it also possible that the tropics is getting a single chilling day?  All it needs is 1 day and it is allowed to break out of "nevercold" for another several hundred days.

**Comment by rgknox** [comment]
@rosiealice could you confirm though that the PFTs in your simulation don't have a drought deciduous denomination? I saw you verfied that they were season decid and not evergreen.  I think the code should check this anyway though...

**Comment by rgknox** [comment]
Another possibility, maybe we are majorly messing up how we create the LAI diagnostic.  That is one of the few non-FATES diagnostics that reports on vegetation.  I'm curious what   "PFTleafbiomass" looks like, as that is a FATES specific diagnostic.

**Comment by rosiealice** [comment]
The last two things (stress phenology and PFTleafbiomass) are not the culprits, as per the updated notebook (at the end) 
https://github.com/rosiealice/jupyter_notes/blob/master/python_scripts/FATES_cold_dec.ipynb

However, the output is monthly, and so we aren't 100% certain that we never ever leave nevercold status, I guess??

**Comment by rgknox** [comment]
Maybe the problem has more to do with incomplete, or missed, leaf dropping when the site first enters nevercold status?
Perhaps on this line:
https://github.com/NGEET/fates/blob/master/biogeochem/EDPhysiologyMod.F90#L958
...there  are plants that are incorrectly flagged as "leaf-off", yet they have leaves?  So they never actually drop.

**Comment by rosiealice** [comment]
OK I've a new theory: in the timestep when the leaves drop, they have a positive NPP, and the leaf biomass is set to below the target. Because PARTEH doesn't know about the status, it allocates a bit of either NPP or stored carbon to get closer to the target leafc. In the next timestep, there is no productivity , so we don't keep moving closer to the target, but are nonetheless left with a little bit of leaf biomass which keeps ticking over. 

Root biomass/mresp gradually declines such that NPP eventually becomes positive and the LAI/GPP feedback kicks in to get us back to normal productivity (the latter part  I've verified in the notebook but it's taking a long time to read the data so will post in the morning).

Is the first part here feasible @rgknox ? I think all of the points, not just the 'nevercold' ones are displaying a little bit of LAI in the off season...

**Comment by rosiealice** [comment]
If this is happening, a) how can we check it, and b) how can we stop it?!

**Comment by ckoven** [comment]
if we change the overall logic to set the leaf target biomass to zero when leaf status is off, would that fix the problem?

**Comment by rosiealice** [comment]
Yes, but we'd need to pass 'status' to parteh to do that, and at the moment everything that controls the phenology is external...

**Comment by rgknox** [comment]
@rosiealice , I think your on to something here

**Comment by rgknox** [comment]
@rosiealice , I made some changes to the carbon only (our default) allocation in parteh, so that it now requires that leaves are in an "on" status to set a non-zero leaf allocation target.
Changes here:
https://github.com/rgknox/fates/tree/fix-leafstatus

I ran a test at BCI using a single cold deciduous tree and compared to master.  The output is agreggated yearly, so we should see in the annual time-series that bleaf should drop to zero.  You can see in the base version (master) it does not drop to exactly zero, but in the test version (branch linked above) it does.  I'm hopeful this may be a fix.  Could you give it a test and review? If it looks good I will submit a PR.

**Comment by rosiealice** [comment]
So, that (@rgknox's fix to the PARTEH code) definitively fixed the tropical issue .- the leaves go off and don't come back on again.

It does seem to have uncovered some new cluster of issues in the high latitudes though. I've not got to the bottom of them yet, but at the very least, at higher latitudes, plants appear to be having two quasi-flushing events, one of which is associated with them producing litter fall.  There are some lower latitude regimes where this doesn't seem to happen, and also some questions around what's happening with growing degree day thresholds. tbc. 

https://github.com/rosiealice/jupyter_notes/blob/master/python_scripts/FATES_cold_dec_fix.ipynb

**Comment by rgknox** [comment]
@rosiealice, is your sense at this point that the site level cold-status flags are working correctly (if not needing better parameters)?  I will submit a PR with the changes, but could hold if you think there are any algorithmic short-comings.

**Comment by rosiealice** [comment]
I think I'd hold off. I finished today thinking there were a few things I need to figure out...

**Comment by rosiealice** [comment]
OK, one thing I think is perhaps confusing things is that there's nothing to stop the leaves coming on on line 694 of EDphysiology, and then (if it's cold) immediately coming off again, because we don't recalculate dayssincecleafon Inbetween those two statements. Does that seem plausible to you? It would love with what I'm finding staring at all this output...

**Comment by rosiealice** [comment]
Next thing (this would be a separate bug fix, but I recommend putting these all in together, since mending the tropical issue has uncovered a cluster of temperate issues...) 

The first issue I uncovered is that the line which determines the fraction of C going to the store :
https://github.com/NGEET/fates/blob/393b905468d93786735a340356d48babc3769988/biogeochem/EDPhysiologyMod.F90#L940

appeared to often be generating values of 1.0, which translated into a cstore of zero, which I think triggers this line 
https://github.com/NGEET/fates/blob/393b905468d93786735a340356d48babc3769988/biogeochem/EDCohortDynamicsMod.F90#L688
that terminates cohorts whose store is close to zero... 

Fixing this, by replacing that  line with this one (apologies I haven't got it on a branch yet):
 store_c_transfer_frac =  min((EDPftvarcon_inst%phenflush_fraction(ipft)*currentCohort%laimemory)/store_c,0.75_r8)

 has a dramatic impact on the northern hemisphere simulations, documented here: 
https://github.com/rosiealice/jupyter_notes/blob/master/python_scripts/FATES_cold_dec_store_fix.ipynb

**Comment by rosiealice** [comment]
The next issue is that there is a strange second leaf-off-then-on-again event after the spring budburst for the high latitude sites.  I am a little confused about why the GDD timers are allowing this to happen, but in the interim, I experimented with making **fates_phen_mindayson** 90 (from 30) in the parameter file, which got rid of the strangeness there. 

https://github.com/rosiealice/jupyter_notes/blob/master/python_scripts/FATES_cold_dec_store_phenmin_fix.ipynb

**Comment by rgknox** [comment]
@rosiealice , regarding phenology flushing, perhaps we should be applying "EDPftvarcon_inst%phenflush_fraction(ipft)" to the available storage carbon and not to the leaf target?  I had always wondered which is more appropriate.

**Comment by rosiealice** [comment]
I'm not sure. In principle it would be good to keep the capacity for some deciduous trees to keep more carbon than others (via their target/cushion) and not necessarily be compelled to add a fixed fraction of that larger pool to the leaf display. Also, I'd worry about getting very large leaf biomass pools that wouldn't ever get trimmed (next trimming takes a while)...

**Comment by rosiealice** [comment]
OK, just documenting the next issue I found, which is that we need to re-zero the 'dayssincecleafon' counter at leaf-on (to prevent immediate leaf drop), here:

https://github.com/NGEET/fates/blob/393b905468d93786735a340356d48babc3769988/biogeochem/EDPhysiologyMod.F90#L726

The illustration of the impact is here. This actually seems to make the post growing season re-leafing behaviour worse, but the counters make more sense, so I'm going to keep it and press on to solve the other issue. 

https://github.com/rosiealice/jupyter_notes/blob/master/python_scripts/FATES_cold_dec_store_phenmin_loncounter_fix.ipynb

**Comment by rosiealice** [comment]
Next thing: zeroing out the GDD counter when leafon happens, and also not allowing it to accumulate during the growing season. Has beneficial impacts on the sanity of the GDD timers, but no apparent impact on the leaf behaviour... 

https://github.com/rosiealice/jupyter_notes/blob/master/python_scripts/FATES_cold_dec_store_phenmin_loncounter_GDD1_fix.ipynb

**Comment by rgknox** [comment]
That's unexpected. I had found in earlier tests that if I didn't zero the GDD at leafon, leaves would be flushed again after the growing season ended and that month-long-ish waiting period had expired. Maybe another protection against that is somewhere in the code.

**Comment by rgknox** [comment]
>OK, just documenting the next issue I found, which is that we need to re-zero the 'dayssincecleafon' counter at leaf-on (to prevent immediate leaf drop), here:

@rosiealice , would the zero'ing happen at around line 699:?

https://github.com/NGEET/fates/blob/393b905468d93786735a340356d48babc3769988/biogeochem/EDPhysiologyMod.F90#L699

**Comment by rosiealice** [comment]
@rgknox I think there are lots of order-dependencies in how the model behaves while I fix these these various bugs. 
and yes, zeroing on that line that you highlighted. 

Today I looked into adding an mandatory 'off' phase (the same length as the mandatory 'on' phase, which seemed to resolve a set of behaviours related to leaves re-flushing immediately after they had been lost. This all now looks a lot more sensible, with two perhaps related caveats, namely

1. I am not sure why the leaf re-flushing was happening in the first place, given that it shouldn't have been over the GDD threshold and 
2. My calculations for the size of the GDD threshold are a lot higher than the GDDs the model is actually reaching, so that is weird.   I need to look into this further. All of this latest twist is now here.

https://github.com/rosiealice/jupyter_notes/blob/master/python_scripts/FATES_cold_dec_store_phenmin_loncounter_GDD3_fix.ipynb

I'm much happier with how this is all looking now though. I'll try and make a branch with these changes on before the end of the week...

**Comment by rosiealice** [comment]
OK, I've made a branch with all these changes on, and a documentation of all of the stages together here:
https://github.com/rosiealice/jupyter_notes/blob/master/python_scripts/FATES_colddec_branch.ipynb

and there's a pull request to Ryan's branch from my branch with all the changes on here:
https://github.com/rgknox/fates/pull/6
