### ISSUE TITLE
Clean up NaN and zeroing of fire variables in Patch and Cohort Dynamics

### ISSUE THREAD

**Issue by jkshuman** [NGEET/fates#575]
Need to clean up Nan and zeroing of fire variables in Patch and Cohort Dynamics per issue #231 
Opening this as a separate issue due to the number of fire variables that need to be assessed in https://github.com/NGEET/fates/blob/3f6749d471e8766a212dd0a2b0c4c95aacd97f65/biogeochem/EDPatchDynamicsMod.F90#L1960-L1988
tagging @jkshuman to do this

**Comment by jkshuman** [comment]
@jkshuman @rgknox @glemieux remember #562 and bad fire behavior in the clean-up of these nan_cohort and zero_cohort

**Comment by ckoven** [comment]
Hi All -- in my cleaning out of fire code I cam across this issue, and thought that, while the fire code is all fresh in my head, now would be a good time to nan these values and also remove some apparently unnecessary zeroing that is happening in the fire code.  So I've now done so and it looks good and behaves well.  does anyone care whether I add that to the existing fire PR versus make a new one with just this change to ensure b4b-ness on it?

**Comment by jkshuman** [comment]
Thanks @ckoven. You are on a fire tornado roll.

**Comment by ckoven** [comment]
commit ea97d55 addresses this.  haven't added it to #717 yet but can either do that or a make separate PR to ensure b4b-ness.
