### ISSUE TITLE
Container development - followup from call on 2019-09-17

### ISSUE THREAD

**Issue by serbinsh** [NGEET/fates#577]
@glemieux @rgknox Just wanted to put an issue here to settle on where to migrate FATES Docker development to, based on my initial stab found here:  https://github.com/serbinsh/ctsm_containers

I think it would be best if we could have a "container" sub folder or separate repository where we develop the Docker files which we then build into images to use for testbeds and site simulations.  We also need a place to store any ancillary files.  

I would envision a place where we can start to develop the baseOS and FATES containers that can be used in example workflows.  We can then also incorporate dockerized versions of the analysis tools which can be downloaded by end users to run locally on their run output.  We can also develop some example Jupyter notebooks, as a starting point.

Finally, we should create a new FATES DockerHub where we can build the images, for example: https://hub.docker.com/r/serbinsh/ctsm_containers

One issue, we will want to provide ways to build ELM or CTSM FATES versions, is it ok to place these together in this one container repo for FATES?  We can separate by having sub-dirs for both models but fundamentally I think we just want to provide some "off the shelf" versions that can be run by new or even experienced users wanting to run simulations on their own machines or experiment quickly with code changes.

I think we decided for now the steps are:

1) Identify where we want to coordinate development, as a project

2) Create the first NGEE Tropics simple docker version with instructions on how to run it, change options, etc

3) "release" this example to the larger community for feedback

4) Develop a plan for how we turn these into a repeatable testbed system with release versions for the community to use in their research. [this is a simple summary of a lot of next steps]

5) etc etc

**Comment by serbinsh** [comment]
Again, we can really simplify these for users BUT here is an example where i map a local setup script into the CTSM container to allow me to run a custom script with a pre-built container: https://github.com/serbinsh/ctsm_containers/blob/master/notebooks/ctsm/run_custom_ctsm_build_example_1.ipynb

**Comment by rgknox** [comment]
Thanks for starting the thread @serbinsh.  Wasn't sure if this was still an open question, but it seems like a separate repository is needed/in-order for developing docker files right?
I don't have a sense of how large and extensive these files can be though.  I should take a look at this folder you linked.

**Comment by serbinsh** [comment]
@rgknox what would be your suggestion for building CTSM-FATES where we "fix" the CTSM next_api at a specific commit?  If I just request that tag each time it will change with code changes, causing possible breakages and we want to keep these static or fixed in docker.  Would we just checkout a specific commit of the api branch of CTSM?

**Comment by glemieux** [comment]
Thanks for starting this issue discussion @serbinsh and laying out the broad goals for the next steps.  

I think having a seperate repo is probably the best way to go based on Val's comments during our talk.  I think it might be worth it to adopt the 'docker-' prefix for the repo name.  As such should we simply start a repo under NGEET called 'docker-fates-tutorial' or something similar to emphasize that this will be for a simple build that we expect new users to try?  I'm assuming that we might later have separate repos such as 'docker-fates-development'.

Additionally, I'd make the case that we should separate this initial effort from the 'testbed' repo with the potential to merge these two efforts together a little further down the road.  

> One issue, we will want to provide ways to build ELM or CTSM FATES versions, is it ok to place these together in this one container repo for FATES?

Baring any political reasons, I think this makes sense given that FATES is still 'experimental'.  I'm assuming that far down the road, the responsibility of this (or similar containerized effort) will largely be taken up by CESM and E3SM, yeah?  I skimmed the E3SM confluence and they have a containerization strategy laid out and a dockerhub setup (https://hub.docker.com/u/e3sm).

I'll create a FATES DockerHub ID btw.

**Comment by rgknox** [comment]
@serbinsh , we have been thinking of creating tags for the fates_next_api changes.  I think @ekluzek may had started this.  If we don't maintain that, than I think the only other alternative is to use specific commit hashes, or to use the head of the branch.  But, like you mention, the branch is dynamic and may break functionality (Unless we use the docker as part of our continuous integration when we update fates_next_api)... But yeah, I would say as a first pass, lets just point to a specific hash or the tag (better?).

**Comment by glemieux** [comment]
Closing this issue now that we've created a docker repo where we can record containerization specific issues: https://github.com/NGEET/docker-fates-tutorial
