### ISSUE TITLE
Update PFT optical properties per Majasalmi and Bright 

### ISSUE THREAD

**Issue by jkshuman** [NGEET/fates#578]
@olyson identified a recent manuscript evaluating LSMs that recommends updating PFT optical properties based on various spectral databases. Many of the FATES param values are drawn from historical CLM PFT values, so will likely need updating. Specifically, there were notable differences between CLM and measured values in the NIR, particularly for conifer trees. 

Majasalmi, T. and R. M. Bright, 2019: Evaluation of leaf-level optical properties employed in land surface models. Geoscientific Model Development, 12, 3923-3938.

@olyson is testing these updates in CLM per https://github.com/ESCOMP/ctsm/issues/807
When this is complete we will update the default FATES_param file for relevant values and PFTs based on @olyson recommendations.

**Comment by jkshuman** [comment]
Modify FATES optical parameters per CLM PFT optical params per file ctsm51_params.c210923.nc
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/jkshuman/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/jkshuman/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



FATES |   |   |   |   |   |   |   |   |   |   |   |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
parameter | BETropT | NEExTropT | NCDExTropT | BEExTropT | BHDTropT | BCDExTropT | BEExTropS | BHDExS | BCDExS | C3arcG | C3nonarcG | C4
CLM param | BETroT | NETemT | NDBorT | BETemT | BDTroT | BDTemT | BES | BDTemS | BDBorS | C3ArcG | C3nonArcG | C4
rholnir | 0.46 | 0.41 | 0.39 | 0.46 | 0.41 | 0.41 | 0.46 | 0.41 | 0.41 | 0.28 | 0.28 | 0.28
rholvis | 0.11 | 0.09 | 0.08 | 0.11 | 0.08 | 0.08 | 0.11 | 0.08 | 0.08 | 0.05 | 0.05 | 0.05
rhosnir | 0.49 | 0.36 | 0.36 | 0.49 | 0.49 | 0.49 | 0.49 | 0.49 | 0.49 | 0.53 | 0.53 | 0.53
rhosvis | 0.21 | 0.12 | 0.12 | 0.21 | 0.21 | 0.21 | 0.21 | 0.21 | 0.21 | 0.31 | 0.31 | 0.31
taulnir | 0.33 | 0.32 | 0.42 | 0.33 | 0.43 | 0.43 | 0.33 | 0.43 | 0.43 | 0.4 | 0.4 | 0.4
taulvis | 0.06 | 0.04 | 0.04 | 0.06 | 0.06 | 0.06 | 0.06 | 0.06 | 0.06 | 0.05 | 0.05 | 0.05
tausnir | 0.001 | 0.001 | 0.001 | 0.001 | 0.001 | 0.001 | 0.001 | 0.001 | 0.001 | 0.25 | 0.25 | 0.25
tausvis | 0.001 | 0.001 | 0.001 | 0.001 | 0.001 | 0.001 | 0.001 | 0.001 | 0.001 | 0.12 | 0.12 | 0.12
xl | 0.32 | 0.01 | 0.01 | 0.32 | 0.2 | 0.59 | 0.32 | 0.59 | 0.59 | -0.23 | -0.23 | -0.23



</body>

</html>

**Comment by glemieux** [comment]
@jkshuman I double checked the above table and the PR #831 changes against the source parameter file and found a minor diffference.  It looks like the `taulvis` for NCDExTropT column should be `0.06`.  Would you confirm please?

**Comment by jkshuman** [comment]
@glemieux this is correct NCDExTropT taulvis=0.06 per the file and tableS1 of the Majasalmi Bright 2019 paper. Thank you for checking and catching this.

**Comment by jkshuman** [comment]
Corrected the above table to reflect the correction noted by @glemieux to read NCDExTropT taulvis=0.06
