### ISSUE TITLE
Parameter file definition edits

### ISSUE THREAD

**Issue by pollybuotte** [NGEET/fates#581]
@rgknox Here are a few minor edits needed when the next round of parameter file updates happens:

           double fates_branch_turnover(fates_pft) ;
		fates_branch_turnover:units = "yr-1" ; 
		fates_branch_turnover:long_name = "turnover time of branches" ;

Units should be "yr".  And here,

	double fates_seed_decay_turnover(fates_pft) ;
		fates_seed_decay_turnover:units = "1/yr" ;
		fates_seed_decay_turnover:long_name = "turnover time for seeds with respect to germination" ;
	double fates_seed_germination_timescale(fates_pft) ;
		fates_seed_germination_timescale:units = "1/yr" ;
		fates_seed_germination_timescale:long_name = "turnover time for seeds with respect to decay" ;

The long_names are switched.

**Comment by rgknox** [comment]
I believe these have been addressed, see:
https://github.com/NGEET/fates/blob/master/parameter_files/fates_params_default.cdl#L126
https://github.com/NGEET/fates/blob/master/parameter_files/fates_params_default.cdl#L448
https://github.com/NGEET/fates/blob/master/parameter_files/fates_params_default.cdl#L451

@pollybuotte , feel free to re-open if you see fit
