### ISSUE TITLE
Build error opening module file: reference not found in module edtypesmod

### ISSUE THREAD

**Issue by serbinsh** [NGEET/fates#587]
I am trying to build a newer "release" version of ctsm-fates on modex but running into this error during land model build 

```
@check_includes
shr_assert.h shr_assert.h shr_assert.h shr_assert.h shr_assert.h shr_assert.h shr_assert.h shr_assert.h shr_assert.h shr_assert.h shr_assert.h shr_assert.h shr_assert.h shr_assert.h shr_assert.h shr_assert.h shr_assert.h shr_assert.h shr_assert.h shr_assert.h shr_assert.h shr_assert.h shr_assert.h shr_assert.h shr_assert.h shr_assert.h shr_assert.h shr_assert.h shr_assert.h shr_assert.h shr_assert.h shr_assert.h shr_assert.h shr_assert.h shr_assert.h shr_assert.h shr_assert.h shr_assert.h shr_assert.h shr_assert.h shr_assert.h shr_assert.h shr_assert.h shr_assert.h shr_assert.h shr_assert.h shr_assert.h shr_assert.h shr_assert.h shr_assert.h shr_assert.h shr_assert.h shr_assert.h shr_assert.h shr_assert.h shr_assert.h shr_assert.h shr_assert.h shr_assert.h shr_assert.h shr_assert.h shr_assert.h shr_assert.h shr_assert.h shr_assert.h shr_assert.h shr_assert.h shr_assert.h shr_assert.h shr_assert.h shr_assert.h shr_assert.h shr_assert.h shr_assert.h shr_assert.h shr_assert.h shr_assert.h shr_assert.h shr_assert.h shr_assert.h shr_assert.h shr_assert.h shr_assert.h shr_assert.h shr_assert.h shr_assert.h shr_assert.h shr_assert.h shr_assert.h shr_assert.h shr_assert.h shr_assert.h shr_assert.h shr_assert.h shr_assert.h shr_assert.h shr_assert.h mpif.h shr_assert.h shr_assert.h shr_assert.h shr_assert.h shr_assert.h shr_assert.h
/data/software/src/ctsm_fates/ctsm_fates_sci.1.27.2_api.7.3.0/src/main/histFileMod.F90:29:32:

   use EDTypesMod        , only : num_elements_fates => num_elements
                                1
Error: Symbol ‘num_elements’ referenced at (1) not found in module ‘edtypesmod’
/data/software/src/ctsm_fates/ctsm_fates_sci.1.27.2_api.7.3.0/src/main/histFileMod.F90:28:6:

   use FatesLitterMod    , only : ncwd
      1
Fatal Error: Can't open module file ‘fateslittermod.mod’ for reading at (1): No such file or directory
compilation terminated.
gmake: *** [histFileMod.o] Error 1
gmake: *** Waiting for unfinished jobs....

ERROR: Command gmake complib -j 4 MODEL=clm COMPLIB=/data2/Model_Output/ctsm_runs/single_point/CLM5-FATES_1571831718_1x1_brazil/bld/gnu/openmpi/nodebug/nothreads/mct/mct/noesmf/lib/libclm.a -f /data2/Model_Output/ctsm_runs/single_point/CLM5-FATES_1571831718_1x1_brazil/Tools/Makefile MACFILE=/data2/Model_Output/ctsm_runs/single_point/CLM5-FATES_1571831718_1x1_brazil/Macros.modex  failed with rc=2
[sserbin@modex case_scripts]$
```

This seems to be occurring with ctsm_fates_sci.1.27.2_api.7.3.0 but not with ctsm_fates_sci.1.23.0_api.7.1.0

To confirm versions, here is the git describe

```
[sserbin@modex ctsm_fates_sci.1.27.2_api.7.3.0]$ git describe
clm5.0.dev008-139-g4e50a44
[sserbin@modex ctsm_fates_sci.1.27.2_api.7.3.0]$

[sserbin@modex ctsm_fates_sci.1.27.2_api.7.3.0]$ cd src/fates/
[sserbin@modex fates]$ git describe
sci.1.27.2_api.7.3.0
[sserbin@modex fates]$
```

I havent run into this build error before.  I could try a newer version but I wonder if anyone else has had this issue before?  Perhaps a local compiler or other issue?

**Comment by serbinsh** [comment]
It appears an issue with module references but not clear

**Comment by ekluzek** [comment]
@serbinsh the version of CTSM you are using, is NOT compatible with the version of FATES you are trying to use (and vice versa). The CTSM version is tied to the FATES API version. If you look at the Externals_CLM.xml file at the top level you can see what version of the FATES API it expects. The science version can change from that, but the API version can't -- unless you make changes to CTSM.

**Comment by rgknox** [comment]
@serbinsh , I see the same thing as @ekluzek .  It seems the fates_next_api branch on ctsm is ahead of the branch of fates, FatesLitterMod.F90 is one of our newest fates subroutines, that was introduced in tag: sci.1.30.0_api.8.0.0

**Comment by serbinsh** [comment]
OK, I think I am still a little incorrect in my thinking/approaching of the "release" version names used on the FATES page.  I was trying to match the release names on the FATES releases, eg. ```sci.1.27.3_api.7.3.0``` by getting the version of fates_next_api and FATES that match those tags....but perhaps I am not doing that exactly right.  I try to find in the ctsm fates_next_api branch commits the git hash that seesm to correspond to something like api.7.3.0.  I think I just need to go over again how I find the correct code versions of each source (CTSM/FATES) that matches the release.....does that make sense?

**Comment by serbinsh** [comment]
@rgknox @ekluzek 

My apologies, I am still trying to understand how to align versions of CTSM, CIME, and FATES to allow error-free builds.  As for CIME, I realized the FATES wiki has the instructions slightly out of order which results in CIME being checked out as a very new version that, at least for modex, wont work/build.  I instead switch to the fates_next_api branch first then checkout the externals.  I then get the correct cime (I could also just checkout the version compatible if the order is different).

I can then go to src/fates and change my version from detached to master, or in my case, to a release version,.  e.g. sci.1.27.2_api.7.3.0

I can then go to CTSM and find a git hash that is within the same API number, that is before the API gets switch (e.g. 320a80dc9858d79a9f89d3ea580faf6261a08229).  But even when I do this, that is make sure I am on a commit that is within the API listed for FATES (7.3.0) I sill get this same build error?

```
Building lnd with output to /data2/Model_Output/ctsm_runs/single_point/CLM5-FATES_1574258255_1x1_brazil/bld/lnd.bldlog.191120-085752
Error: Symbol ‘num_elements’ referenced at (1) not found in module ‘edtypesmod’

```

I am on this CTSM commit

```
commit 4e50a445db9f40c7590b49cbc11f81025c30bc3a
Author: Ryan Knox <rgknox@lbl.gov>
Date:   Thu Aug 1 13:34:44 2019 -0600

    Updated FATES testmods_dirs to reflect changes in history variables.
```

That is before the API change....but do I need to go back farther?  Am I missing something obvious to tell me what commits of CTSM will work with release versions of fates or some way of knowing what commits/branches/tags will work seamlessly together?  Right now, I am finding it challenging to know how to line everything up to work within a "stable release" of FATES instead of off the latest code.  

Does this make sense?  I feel I am missing something really obvious.

**Comment by serbinsh** [comment]
OK, so then if I align by commit date and use CTSM hash b807b43b40c114a6f1b08f03710900a92189cc14 (June 5th) I am getting these build errors

```
Component csm_share build complete with 1 warnings
         - Building clm library
Building lnd with output to /data2/Model_Output/ctsm_runs/single_point/CLM5-FATES_1574259085_1x1_brazil/bld/lnd.bldlog.191120-091143
Error: Symbol ‘num_elements’ referenced at (1) not found in module ‘edtypesmod’

Error: Symbol ‘fates_hdim_agemap_levelage’ referenced at (1) not found in module ‘fatesinterfacemod’

Error: Symbol ‘fates_hdim_elmap_levelage’ referenced at (1) not found in module ‘fatesinterfacemod’

Error: Symbol ‘fates_hdim_cwdmap_levelcwd’ referenced at (1) not found in module ‘fatesinterfacemod’

Error: Symbol ‘fates_hdim_elmap_levelcwd’ referenced at (1) not found in module ‘fatesinterfacemod’

Error: Symbol ‘fates_hdim_pftmap_levelpft’ referenced at (1) not found in module ‘fatesinterfacemod’

Error: Symbol ‘fates_hdim_elmap_levelpft’ referenced at (1) not found in module ‘fatesinterfacemod’

Error: Symbol ‘fates_hdim_levelem’ referenced at (1) not found in module ‘fatesinterfacemod’

Error: Symbol ‘num_elements_fates’ at (1) has no IMPLICIT type

Error: Symbol ‘fates_hdim_agemap_levelage’ at (1) has no IMPLICIT type

Error: Symbol ‘fates_hdim_cwdmap_levelcwd’ at (1) has no IMPLICIT type

Error: Symbol ‘fates_hdim_elmap_levelage’ at (1) has no IMPLICIT type

Error: Symbol ‘fates_hdim_elmap_levelcwd’ at (1) has no IMPLICIT type

Error: Symbol ‘fates_hdim_elmap_levelpft’ at (1) has no IMPLICIT type

Error: Symbol ‘fates_hdim_levelem’ at (1) has no IMPLICIT type

Error: Symbol ‘fates_hdim_pftmap_levelpft’ at (1) has no IMPLICIT type

Error: Symbol ‘num_elements_fates’ at (1) has no IMPLICIT type

clm built in 12.353843 seconds
ERROR: BUILD FAIL: clm.buildlib failed, cat /data2/Model_Output/ctsm_runs/single_point/CLM5-FATES_1574259085_1x1_brazil/bld/lnd.bldlog.191120-091143
*** Finished building new case in CASE: /data2/Model_Output/ctsm_runs/single_point/CLM5-FATES_1574259085_1x1_brazil
```

When I am attempting to build a simple test case.  

Again, what I am attempting to do is look at a FATES release tag and then put the pieces together to allow us to run that specific version with the correct CTSM and CIME.  I thought I had a handle on how to align commits of fates_next_api but clearly I was wrong

**Comment by serbinsh** [comment]
OK, I rest back to this commit and the build worked:

```
commit 08fc9481fb6543bf91d21176f1d8563ddf39d954
Merge: 27cdc37 5acdd7b
Author: Ryan Knox <rgknox@lbl.gov>
Date:   Fri May 31 10:45:11 2019 -0700

    Merge pull request #740 from rgknox/fates-api-7.3.0

    Fates api 7.3.0

```
