### ISSUE TITLE
Connect fire events to ignitions

### ISSUE THREAD

**Issue by jkshuman** [NGEET/fates#589]
Within SPITFIRE there is not a connection between a fire events and an ignition event. As it stands, if it can burn, it will burn regardless of ignitions. Going to add in a connection to ignitions. 
(if FI exceeds fire threshold and ignitions are greater than 0 then fire ==true) Can I get a confirmation that I am not missing something here...? @rosiealice @rgknox @adrifoster @pollybuotte @slevisconsulting  

https://github.com/jkshuman/fates/blob/1ad93c311ed1a5d45df656b9031c8714a7071e64/fire/SFMainMod.F90#L687-L688
This is a larger problem because it is then carried through into tree fire-damage and tree mortality, if it can burn, then the trees might be fire-damaged, regardless of the presence of ignitions. Might explain some of the excessive tree death.
https://github.com/jkshuman/fates/blob/1ad93c311ed1a5d45df656b9031c8714a7071e64/fire/SFMainMod.F90#L963
https://github.com/jkshuman/fates/blob/1ad93c311ed1a5d45df656b9031c8714a7071e64/fire/SFMainMod.F90#L1013

**Comment by rosiealice** [comment]
Shouldn't there be a link between the lightening counts (real number) and the fire area? As per:
https://github.com/NGEET/fates/blob/87ce240691a6c1446b847a9faffcb5e450e4596d/fire/SFMainMod.F90#L788
So the ignition counts do always make a fire, but the amount of fire is variable. I guess what you're getting it is some scalar to account for the fact that not every lightening strike actually causes a fire? ('Lightening strike efficiency' or something like that?)

**Comment by adrifoster** [comment]
In Thonicke 2010 AB is then incorporated into the FI calculation 

FI = h * FC/Ab_frac * ROS/60.0

For UVAFME I did not include this area burnt impact on FI, but used ignition rate times FDI as a "probability" of fire ignition. Fire can only occur if that ignition event happens (and then following that FI exceeds the threshold).

**Comment by jkshuman** [comment]
@rosiealice the AB calculation is indeed connected to ignitions as you notice. The calculation for crown damage and tree mortality is connected only to fire==true on the patch. This is set in the Fire Intensity subroutine: https://github.com/NGEET/fates/blob/87ce240691a6c1446b847a9faffcb5e450e4596d/fire/SFMainMod.F90#L687-L688
Then we calculate area burnt using the ignitions value, then crown scorch, damage, and finally tree mortality. Problem I am seeing is that after area burnt the ignitions are no longer used the calculation is set by fire==true, so you could potentially have zero ignitions resulting in zero area burnt but with non-zero fire damage and mortality. I haven't tested for that zero ignitions case, but seems to be a missing connection.

**Comment by jkshuman** [comment]
@adrifoster frac_burnt is set in area burnt calculation after using ignitions to get to area burnt (AB):
https://github.com/NGEET/fates/blob/87ce240691a6c1446b847a9faffcb5e450e4596d/fire/SFMainMod.F90#L790-L791
fraction crown burnt is set inside the crown damage routine:
https://github.com/NGEET/fates/blob/87ce240691a6c1446b847a9faffcb5e450e4596d/fire/SFMainMod.F90#L914-L919

**Comment by jkshuman** [comment]
@rosiealice yes - the scaler is going to adjust for the fact that only a fraction of lightning strikes have the energy to start a fire. so it just reduces that value to a "fire igniting" relevant value

**Comment by slevisconsulting** [comment]
@jkshuman I have not looked for an explanation in the code to justify this result BUT I have confirmed no fire for no ignitions with this simple test:

I ran single point at CZ2 and replaced ignitions NF:
`NF = ED_val_nignitions * years_per_day`
with
`NF = 0._r8`
I get:
`FIRE_AREA = 0`
`CROWNFIREMORT_SCPF = 0`
`CAMBIALFIREMORT_SCPF = 0`
`M5_SCLS = 0`
Many diagnostic fire variables are non-zero, but I think the bottom line is that they have no effect when NF = 0. Do you find otherwise?

**Comment by rosiealice** [comment]
Ah, so if there are no ignitions, but there are still 'burnable' conditions, you might get a high theoretical carbon intensity which would make fire==true, and then things might do wrong downstream of that? So in principle the logic of whether patch%fire is true or false should have an  (if NF > 0)then . around it?

and I guess this is all an issue now because before we were specifying ignitions as always >0...

Is that right?

**Comment by jkshuman** [comment]
@rosiealice exactly right. If you have fuel that is "burnable" as it is the fire intensity could be above 50Kw/m threshold and set patch%fire ==true, even with zero ignitions. I moved a few things around, and testing the zero ignitions case, but so far so good. The other thing that needed to happen was tying the calculation of FI to ignitions. This now happens by including the burnt fraction in the FI calculation, and thus scales the FI according to the actual area burnt (rather than using the fuels on the whole patch). This is used in Thonicke 2010. Will summarize those changes in a PR related to this. This has resulted in improved performance in the savanna of SA where you  have consistently "burnable"conditions, so that's good.

**Comment by jkshuman** [comment]
my branch with these fixes. Chatting with Ryan about this today...
https://github.com/jkshuman/fates/blob/FI-update/fire/SFMainMod.F90

**Comment by jkshuman** [comment]
getting a fail in simulation when the order of the calls is swtiched to calculate area_burnt prior to fire_intensity
cesm.log with fail (below)
dist mode:            2
 anthro_disturbance_label:            1
 ---------------------------------------
 patch area:    58.4349816229170     
 AG CWD:   1.041408172973289E-002
 BG CWD (by layer):   3.415172834463647E-004  6.355358316751320E-004
  8.446833529172978E-004  9.507805527705958E-004  1.120787320429172E-003
  1.066481055372897E-003  8.639582952629191E-004  6.101556502763734E-004
  3.804427368009551E-004  2.110164638605815E-004  1.046248545866968E-004
  4.652503099200012E-005  1.859940765311297E-005  7.107311850267568E-006
  2.066417845168098E-006  4.617368900356882E-007  7.978018072008980E-008
  1.070162001165404E-008  1.117468196102283E-009  9.100806434125077E-011
 leaf litter:  8.492274828564845E-003
 root litter (by layer):   4.484292895898153E-003  8.359021727095978E-003
  1.110987948695426E-002  1.250534572907024E-002  1.474139630841477E-002
  1.402712147622106E-002  1.136339731211116E-002  8.025203432082328E-003
  5.003854927349907E-003  2.775439429648419E-003  1.376100904301968E-003
  6.119304774537691E-004  2.446327098091295E-004  9.348044786246149E-005
  2.717900518604987E-005  6.073093763787964E-006  1.049325987290305E-006
  1.407553590751238E-007  1.469774081177620E-008  1.197003141686480E-009
 dist mode:        -9999
 anthro_disturbance_label:            1
 aborting on date:           2           8           7
 ENDRUN:
 ERROR in EDMainMod.F90 at line 699                                             
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                       
 ERROR: Unknown error submitted to shr_abort_abort.
 Projected Canopy Area of all FATES patches
 cannot exceed 1.0
Image              PC                Routine            Line        Source

**Comment by jkshuman** [comment]
After chatting with @rgknox about these changes, I need to do more investigating before implementing this change that includes frac_burnt in the fire intensity (FI) calculation. The model is failing with a re-order of the call to the subroutines. Will submit a PR for the scaler associated with cloud to ground lightning strikes separate of this change to including frac_burnt in the FI calculation. That scaler will at least bring strikes into a more realistic value.

**Comment by rgknox** [comment]
@jkshuman , is it possible that somehow  the %fire flag is inconsistent now, or being reset inadvertently?  I'm wondering if there are now patches that have burned area but a %fire=0 flag, or vice versa. 

I say this because we only pass litter fluxes if patch%fire == 1, but the rest of the mass balance does not require that flag to be true (such as reducing number density)

https://github.com/NGEET/fates/blob/master/biogeochem/EDPatchDynamicsMod.F90#L1424

**Comment by rgknox** [comment]
You could test this by going to that line linked above, and instead of returning, write a catch, where if that is true, then fail gracefully with a verbose error message.

**Comment by rgknox** [comment]
Also, this line needs to go or be moved:
https://github.com/jkshuman/fates/blob/FI-update/fire/SFMainMod.F90#L803
We should not even be running the fire code if it not turned on, we should call some stub that passes back  0 burned fractions and 0 mortality rates and then exits before we get into the spitfire code.

**Comment by jkshuman** [comment]
These are good points @rgknox. I am going to implement a different version of the connection between fire events and ignitions. Require the fire_threshold and NF>0 for fire==true, but maintain the subroutine order and current FI calculation. Testing this simpler implementation with expanded  conditional for fire==true now.

I need to truly evaluate the inclusion of frac_burnt as part of the FI calculation that initiated the re-order of the subroutines. @rosiealice can you provide the rationale for modifying the original Thonicke calculation for FI? Did you find that the frac_burnt was not necessary for calculating FI?
I will evaluate a change to the FI calculation outside of this issue, and address @rgknox comments there.

**Comment by jkshuman** [comment]
> Also, this line needs to go or be moved:
> https://github.com/jkshuman/fates/blob/FI-update/fire/SFMainMod.F90#L803
> We should not even be running the fire code if it not turned on, we should call some stub that passes back 0 burned fractions and 0 mortality rates and then exits before we get into the spitfire code.

@rgknox At the start of the fire_model subroutine we check that hlm_use_spitfire == true  prior to calling subroutines. https://github.com/jkshuman/fates/blob/721b204245c5ec6487346ee904a128eb5ca6a159/fire/SFMainMod.F90#L94-L106
I will delete that line inside the fire_intensity subroutine. Let me know if you want me to do something else.

**Comment by rgknox** [comment]
Awesome, thanks @jkshuman

**Comment by jkshuman** [comment]
closing per PR #594
