### ISSUE TITLE
Enforcing end of line 'lf' character for github repo code

### ISSUE THREAD

**Issue by glemieux** [NGEET/fates#601]
Recently, in deconflicting PR #554 (found [here](https://github.com/xuchongang/fates-1/pull/8)), it was found that the EDLoggingMortalityMod.F90 file had been originally committed to the repo with `crlf` end of line characters instead of the `lf` which git considers "normal".  This ended up being corrected to `lf` in PR #524 which was included in the deconflict effort (specifically in commit https://github.com/NGEET/fates/commit/5f24b0417edb5d94e4f0468c8a59144366ffbad4).

This created a minor annoyance when viewing the diff on github initially as git (correctly) flagged the whole file as changed due to the eol character change.  @rgknox noted that you can ignore whitespaces (including eol characters) using the settings at the top of the diff page:

![image](https://user-images.githubusercontent.com/7565064/72191786-456d2000-33b8-11ea-92ba-1bf2d1151099.png)

That said, I'm suggesting that we implement some git capability to enforce having all code updates commit to the ngeet repo with `lf` eol character.  We can do this by using a `.gitattributes` file in the root directory that tells each user's local git repo to override their global configuration (for the eol attribute only) to make sure git commits the files with `lf`.  The relevant git article is [here](https://git-scm.com/docs/gitattributes).  I've got a draft PR, #600, currently in the works.  Thoughts?

P.S. I found only one file currently in the repo with `crlf` eol characters: https://github.com/NGEET/fates/blob/master/functional_unit_testing/allometry/drive_allomtests.py

**Comment by rgknox** [comment]
I really like the idea of having this project level attribute set.  This will help us avoid future mangling with these hidden characters.

**Comment by glemieux** [comment]
Closing per #600
