### ISSUE TITLE
Nag compiler complains about an edit descriptor

### ISSUE THREAD

**Issue by ekluzek** [NGEET/fates#603]
The nag compiler on izumi complains about the edit descriptor for a write statement that was added on Dec/16th of last year.

> Building lnd with output to /scratch/cluster/erik/SMS_Lm3_D_Mmpi-serial.1x1_brazil.I2000Clm50FatesCruGs.izumi_nag.clm-FatesHydro.GC.rl-clm53nagf/bld/lnd.bldlog.200115-164255
> Error: /fs/cgd/data0/erik/ctsm_relanswerchangesfor5029/src/fates/main/EDParamsMod.F90, line 549: Missing field width for L edit descriptor
> 
> Component lnd build complete with 6 warnings
> clm built in 3.881813 seconds
> 

A simple change that allows it to compile is as follows...

Using the "L" descriptor without a width argument to it is against the FORTRAN standard. It's allowed for the "A" descriptor, but not others.

``` fortran
diff --git a/main/EDParamsMod.F90 b/main/EDParamsMod.F90
index 986151a8..0f5e3645 100644
--- a/main/EDParamsMod.F90
+++ b/main/EDParamsMod.F90
@@ -546,7 +546,7 @@ subroutine FatesReportParams(is_master)
         write(fates_log(),fmt0) 'q10_mr = ',q10_mr
         write(fates_log(),fmt0) 'q10_froz = ',q10_froz
         write(fates_log(),fmt0) 'cg_strikes = ',cg_strikes
-        write(fates_log(),'(a,L)') 'active_crown_fire = ',active_crown_fire
+        write(fates_log(),'(a,L1)') 'active_crown_fire = ',active_crown_fire
         write(fates_log(),*) '------------------------------------------------------'
 
      end if
```

**Comment by rgknox** [comment]
@ekluzek , looks like we have modified this write statement, does the following look sufficient?
https://github.com/NGEET/fates/blob/master/main/EDParamsMod.F90#L572

**Comment by ekluzek** [comment]
Yes that should be fine.
