### ISSUE TITLE
Code typos in FatesHistoryInterfaceMod.F90

### ISSUE THREAD

**Issue by serbinsh** [NGEET/fates#606]
While searching through this to find outputs we want to enable for some tests I noticed at least one typo, I think.   

``` call this%set_history_var(vname='C_LBLAYER_BY_AGE', units='umol m-2 s-1',                   &
         long='mean leaf boundary layer conductance - by page age', use_default='inactive', &
         avgflag='A', vtype=site_age_r8, hlms='CLM:ALM', flushval=0.0_r8, upfreq=2,   &
         ivar=ivar, initialize=initialize_variables, index = ih_c_lblayer_si_age )```

Should be "patch age" I believe. If so we can have @Qianyuxuan add this change to her upcoming PR.  And any others I might find

**Comment by serbinsh** [comment]
@rgknox @glemieux I see some mixing and matching of units in FATES where some are expressed as ```umol m-2 s-1```, for example and others ```gC/m^2/s```  Just legacy? Should we be working toward a standard such as ``` g C m-2 s-1```? for complex units but keeping / in simpler like ```m/s```?  I find it hard to reconcile pure CF with other documentation on appropriate expression of units.  http://cfconventions.org/cf-conventions/cf-conventions.html. Here is what we are doing in PEcAn https://pecanproject.github.io/pecan-documentation/develop/pecan-standards.html to keep track of that, as an example.

**Comment by rgknox** [comment]
@serbinsh  I like the idea of conforming to CF
If your finding inconsistencies in units from different flux variables, my guess is that the differences were not intended and there is no reason we cant unify under one unit

**Comment by glemieux** [comment]
Closing per #609
