### ISSUE TITLE
Patch area does not equal 1 affecting multiple output variables

### ISSUE THREAD

**Issue by JoshuaRady** [NGEET/fates#614]
In single point simulations with Pure PPA (fates_mort_disturb_frac = 0) and one PFT the sole patch is consistently less than one (sum of PATCH_AREA_BY_AGE > 1).  The deviation from 1 is consistent for a given grid cell but varies from grid cell to grid cell.  The patch area seems to be more or less time invariant.  This missing patch area can be from a fraction of a percent up to 5 percent.

This effects all output variables I have checked for which I have an a priori expectation of their value.  For example AREA_PLANT should approach 1 after canopy closure and (the sum of) CANOPY_AREA_BY_AGE should max out at 2 but both max out at a multiple of the patch area.  This is even true for variables such as CANOPY_SPREAD where the initial value for a bare ground cold start should seemingly always start at 1.

While it makes sense numerically that the grid cell (lndgrid) level, per unit area quantities would be reduced due to the missing patch area is is not clear what the missing patch area represents.  In all cases there is only one patch.  There is no empty patch occupying the remainder of the nominal hectare.

The location dependance of the patch area has also baffled me.  I have examined the surface files (which I think are ignored anyway) and have not found anything that would explain the variability.  I should also note that the vegetated land units composition is identical across the locations I have differ in their patch area.

The obvious solution is to adjust all output by the patch area.  Doing so results in appropriate number for the variables above.  However, I am loth to do this systematically until I am sure that I don't have a configuration problem that is causing this issue.

**Comment by ckoven** [comment]
@JoshuaRady  I suspect this has to do with the fill value used on non-FATES columns

**Comment by JoshuaRady** [comment]
I'll look at the surface files again and examine the columns outside the vegetated land unit and see if any of them add up to the right number.

**Comment by JoshuaRady** [comment]
I examined one location and found there is a small fraction of lake and urban that adds to an appropriate area.  I was under the misapprehension that these columns were not being simulated under my configuration.  I will repeat a run with a modified surface file just to be sure.

**Comment by JoshuaRady** [comment]
I can confirm (belatedly) that this solves the issue.  After modifying the surface file to 100% natural vegetation for the grid cell the patch areas equal 1 as expected.  User error was the source of the issue.  This issue is resolved and can be closed.
