### ISSUE TITLE
Drought Deciduous phenology termination death 

### ISSUE THREAD

**Issue by rosiealice** [NGEET/fates#615]
Following our discussion last week on how the drought deciduous trees appear to be prone to dying from termination mortality induced death of the third type,
https://github.com/NGEET/fates/blob/f55eb83c6011f90e3f01fae14c01a7f3530075d4/biogeochem/EDCohortDynamicsMod.F90#L701

 @rgknox reminded me that we had implemented a buffer to prevent the store being zero'ed out. The comments suggest that in a past life, I apparently encountered the exact same issue:
https://github.com/NGEET/fates/blob/f55eb83c6011f90e3f01fae14c01a7f3530075d4/biogeochem/EDPhysiologyMod.F90#L973

This seems to be in place for cold deciduous leaf flushing, but, potentially importantly, it isn't implemented for the drought deciduous trees.
https://github.com/NGEET/fates/blob/f55eb83c6011f90e3f01fae14c01a7f3530075d4/biogeochem/EDPhysiologyMod.F90#L1092

I think this might be the culprit of the excessive termination mortality I'm seeing. 

I tried, @ckoven & @tompowell9, upping the storage target to 3x the leaf biomass. That had a beneficial effect, but interestingly, it is still hitting these massive spikes, I guess in places with high interannual variability (which is most semi-arid places) and occasional very long dry seasons and I think it's causing some quite erratic behavior. 

I'm obviously going to try implementing the buffer in the DD phenology line, but Cheyenne appears to be having a blip right now, and won't be up for several more days, so am putting this here as a placeholder and to get a sanity check from anyone who wants to take a look... 

I'd share my jupyter notebook on this, but it's not neat and tidy enough yet ;)

**Comment by rgknox** [comment]
ahh, righto @rosiealice 
I see we have the storage carbon buffer protection in place for cold deciduous, here:
https://github.com/NGEET/fates/blob/f55eb83c6011f90e3f01fae14c01a7f3530075d4/biogeochem/EDPhysiologyMod.F90#L981

But not for drought deciduous... looks like it fell through the cracks..

**Comment by rosiealice** [comment]
Just to update. I tested it, and while it didn't make the termination mortality go away altogether (some things still just unavoidably starve to death, because, you know, that is life), it did have some impact...
