### ISSUE TITLE
Global PFT file and vegetation forms

### ISSUE THREAD

**Issue by jkshuman** [NGEET/fates#619]
At the recent LMWG meeting and spurred by my 3 PFT tree-grass South America simulations and @rosiealice global testing, a few issues and discussions have cropped up related to allometry. @rgknox started a discussion of the importance of allometry and the importance of remembering that the default file parameter values should (at the moment) NOT be considered scientifically validated until marked otherwise or demonstrated in your own testing (see allometry issue #352). In my 3PFT tree-grass with active fire testing across South America, an incorrect grass crown allometry allowed the grass to be overly and unrealistically competitive to the trees. (Shame on me for using the default crown allometry, but happy to talk about my mistakes if you missed my LMWG presentation.) If you are competing two similar vegetation forms in the same photosynthetic pathway, bad crown allometry might not alter competitive dynamics, but it will give you odd LAI values, etc. My grass-tree fire testing demonstrated to me that crown allometry is important when two distinct forms are competing dynamically. 

To help us move along towards an improved global "default" PFT file and help folks avoid just plain wrong results, I suggest that we pool our experiments and provide updates to the default parameter file to define a few vegetation forms with, at a minimum, reasonable crown area allometry (conifer form, broadleaf deciduous form, grass form, etc). @ckoven suggested we use the PFTs that @rosiealice has been testing for her global runs. I have a moist tropical tree and dry tropical tree and C4 tropical grass (modified from @xuchongang parameterization of C4 spartina grass). I think @pollybuotte and @JunyanDing have been testing conifer forms, @ckoven will have a broadleaf temperate deciduous form soon. We can likely use the same C4 grass form for the C3 grass as a starting point and specify the C3 pathway. @jenniferholm has also been testing in the boreal and might have input on this. 

What do people think? @rosiealice can you provide your list of global PFTs?

**Comment by jkshuman** [comment]
tagging related issue #596 recently posted by @rosiealice

**Comment by rosiealice** [comment]
Thanks @jkshuman! @ckoven  and I just got off the phone where we were taking about the need to have exactly this sort of discussion as part of the all hands call on Monday and this is an excellent start. We need to think of a strategy for how to combine efforts. Will think more on this tomorrow.

**Comment by rosiealice** [comment]
Just reading this again, the PFTs I've been using are
Broadleaf evergreen tree
Broadleaf drought deciduous tree
Broadleaf cold deciduous tree
Needleleaf Evergreen Tree
C3 grass
C4 grass

It would be great if people had candidate allometric relationships for these different PFTs that we could assimilate into the 6 PFT file.  @jenniferholm noted she had been using BAAD for this as well. It would be great to not re-invent the wheel on that while we are getting the global PFT set together.

**Comment by pollybuotte** [comment]
I have a few candidate allometries for a typical pine/needleleaf evergreen tree, where I've used the BAAD data to fit the parameters.  I expect I'll settle on "final" parameters for my California runs this week.

**Comment by JunyanDing** [comment]
I estimated allometry for general temperate conifer from BAAD. I tried them
with FATESHydro , and gives reasonable  size structure and LAI.

Junyan

**Comment by glemieux** [comment]
Closing this to discuss further in #941
