### ISSUE TITLE
Snow Burial is always off

### ISSUE THREAD

**Issue by rosiealice** [NGEET/fates#625]
A few weeks ago @huitang-earth and I were looking through the radiation code and realized that snow burial is always off (as in, after the calcualtions, the 'fraction_exposed' is set back to one. I suspect that this crept in during earlier debugging of the radiation code. It's trivial to fix of course, but needs testing to make sure it doesn't break the radiation energy balance checks, or indeed anything else.

In this absence of this, ELAI will always be the same as TLAI, and any investigations of how snow burial affects albedo will of course be nullified.

**Comment by ckoven** [comment]
is this the same as #359 or different?

**Comment by rosiealice** [comment]
Ah yes. Maybe I'll just delete this...
