### ISSUE TITLE
BIOMASS and BURNED_AREA not in output files (causes issues with ILAMB)

### ISSUE THREAD

**Issue by rosiealice** [NGEET/fates#626]
When running initial FATES tests with ILAMB,  it appears that neither BIOMASS nor BURNED_AREA are FATES outputs at the moment.  We have 'BIOMASS_CANOPY' and 'BIOMASS_UNDERSTOREY' and 'FIRE_AREA', but the ILAMB code wants them to be labelled a specific way..

**Comment by dlawrenncar** [comment]
Note that ILAMB can handle different variable names for different
applications.  For example, there is a list of variable names for CMOR
output and for direct CLM output.  So, this is not an insurmountable
problem.  However, it does seem like it would be useful to consider
reporting summary variables, like TOTVEGC, in FATES if that is not already
being done.

**Comment by jkshuman** [comment]
@rosiealice is ED_BIOMASS the same as TOTVEGC?

**Comment by ckoven** [comment]
closing this as it seems like it can be fixed on the ilamb side.
