### ISSUE TITLE
Site-level-vegetation temperature bug

### ISSUE THREAD

**Issue by xuchongang** [NGEET/fates#636]
When running ELM(FATES), t_veg24_si will not be updated and cause errors in phenology (never cold) and cause vegetation to die off from carbon starvation. See the detailed description and solution in the attached pdf file. Please let me and @rgknox  know if you have any suggestions for the solution. 
[Bug of site-level-vegetation temperature.pdf](https://github.com/NGEET/fates/files/4530536/Bug.of.site-level-vegetation.temperature.pdf)

**Comment by rgknox** [comment]
@xuchongang , I just talked this over with @ckoven and @glemieux and we feel the fix to this is simple, and can be fixed on the FATES side of the code.  
The solution is to just calculate the area weighted mean of the patch-level t_veg_24 (a variable we get along with the site level anyway) ourselves in fates.  I will self assign.
