### ISSUE TITLE
When cohort age tracking is on maxCohortsPerPatch needs to be increased in set_fates_global_elements

### ISSUE THREAD

**Issue by JessicaNeedham** [NGEET/fates#639]
If cohort age tracking is on then we need to increase maxCohortsPerPatch in FatesInterfaceMod so that enough memory is allocated in the restart files. This happens in set_fates_global_elements. At this point hlm_use_cohort_age_tracking has not yet been defined. We therefore need to call use_fates_cohort_age_tracking from clm_varctl. This might cause problems if FATES is not being run with CLM.

**Comment by rgknox** [comment]
@JessicaNeedham , I recommend we pass that value as an argument to set_fates_global_elements():

https://github.com/NGEET/fates/blob/master/main/FatesInterfaceMod.F90#L1031

**Comment by ckoven** [comment]
this was fixed by #647, closing.
