### ISSUE TITLE
cool vs. arctic C3 grass PFT

### ISSUE THREAD

**Issue by evalieungh** [NGEET/fates#641]
Hi! 
A hopefully quick question: Can someone explain the major differences between PFTs cool_C3_grass and arctic_C3_grass? I'm thinking about what species they represent, the PFTs rough current distribution and whether they should be able to coexist in a gridcell in real life.

**Comment by ckoven** [comment]
Hi @evalieungh, looks like there are only three differences: phenology (cold deciduous versus drought-stress deciduous), freeze tolerance, and carbon starvation resistance.  I get this by extracting just each of the pfts into their own file, then converting those text and diffing the resulting files.  e.g.:
```
> FatesPFTIndexSwapper.py --pft-indices=11 --fin=fates_params_default_b4eb75f8.nc --fout=fates_params_default_b4eb75f8_pft11.nc
> FatesPFTIndexSwapper.py --pft-indices=10 --fin=fates_params_default_b4eb75f8.nc --fout=fates_params_default_b4eb75f8_pft10.nc
> ncdump fates_params_default_b4eb75f8_pft11.nc  > fates_params_default_b4eb75f8_pft11.cdl
> ncdump fates_params_default_b4eb75f8_pft10.nc > fates_params_default_b4eb75f8_pft10.cdl
> diff fates_params_default_b4eb75f8_pft10.cdl  fates_params_default_b4eb75f8_pft11.cdl
```

which results in:
```
1c1
< netcdf fates_params_default_b4eb75f8_pft10 {
---
> netcdf fates_params_default_b4eb75f8_pft11 {
674c674
< 			" Indices = [10]" ;
---
> 			" Indices = [11]" ;
837c837
<   "arctic_c3_grass                            " ;
---
>   "cool_c3_grass                              " ;
999c999
<  fates_maintresp_reduction_intercept = 2 ;
---
>  fates_maintresp_reduction_intercept = 1 ;
1003c1003
<  fates_mort_freezetol = -80 ;
---
>  fates_mort_freezetol = -20 ;
1031c1031
<  fates_phen_season_decid = 1 ;
---
>  fates_phen_season_decid = 0 ;
1035c1035
<  fates_phen_stress_decid = 0 ;
---
>  fates_phen_stress_decid = 1 ;
```

Not sure what the conceptual reason is for the difference in carbon starvation resistance (value of fates_maintresp_reduction_intercept) though...

**Comment by evalieungh** [comment]
Thank you @ckoven! That answers the technical differences between them. The method for finding differences is also very helpful, I will try that for some other PFTs too I think. 

Is there a more 'ecological' interpretation, though? I'm asking because I'm making a new parameter file with a subset of the PFTs that are relevant in my study area (Norway) and I am unsure if I should include both of the C3 grass PFTs or just the arctic one. Not sure if the graminoids in the lowlands here fit either very well. The safest thing to do is maybe to include both and see what happens, but it would be nice to be able to think about the PFTs in terms of example species or ecosystems that they are supposed to represent.

**Comment by rosiealice** [comment]
I don't think there is a more ecological interpretation.  The PFTs in the default file are essentially the same as in CLM/ELM. One of the things that has always bugged me about those definitions is the 'temperate/boreal/arctic' distinctions that are primarily geographical rather than physiological or ecological. This is fine in a model with static vegetation, but in a DGVM context you really want the PFT trait differences to affect whether vegetation does well or badly in different climate zones. That's primarily why i started using the reduced form PFT set without the temperate/arctic/boreal differentiation. 

It would be better if we could re-define those PFTs are having traits that reflect the real differences that control the fitness of plants in different climate zones...

**Comment by evalieungh** [comment]
Thanks for the input, @rosiealice. It's interesting that the distinctions stem from geographical thinking rather than real physiological. I'm assuming then that that difference between them is not necessarily very big and it would be interesting to include both and see what happens. If the simulations show large amounts of cool C3 grass in our alpine sites I will guess something is wrong and maybe take it out again. In the slightly longer run, I want to modify the PFT parameters so I will think a bit more about the differences between these two and which of them will be most appropriate to copy and modify to get something more aligned with our dominant species. 

I'll close this issue now, but I guess it can be reopened if someone else wants to discuss differences between these two PFTs!
