### ISSUE TITLE
Clarification on useage of set_bcs?

### ISSUE THREAD

**Issue by glemieux** [NGEET/fates#648]
This came up in the context of reviewing https://github.com/NGEET/fates/pull/647#discussion_r421966187.  @rgknox refactored `set_bcs` out of the `fates_interface_type` definition to avoid circular dependency issues.  The comments in the subroutine appears to suggest that this might have future usage as a direct call from the HLM.  @xuchongang can you clarify if I'm understanding this correctly?  Are you using it in any local branches of your code?

**Comment by xuchongang** [comment]
@glemieux and @rgknox , I think it is fine to refactor set_bcs outside of the interface. For ATS-FATES coupling, we have directly fed data to the bcs. We do not use an direct call from HLM during ATS-FATES coupling.

**Comment by glemieux** [comment]
Thansk @xuchongang.  I'm going to close this now that we've merged #647.
