### ISSUE TITLE
dbh uninitialized

### ISSUE THREAD

**Issue by pnlfang** [NGEET/fates#662]
dbh in the third call of carea_allom ~line 1174 in "biogeochem/EDCohortDynamicsMod.F90" doesn't seem to be initiated.

**Comment by glemieux** [comment]
Adding permalink to the line in question for quick link:
https://github.com/NGEET/fates/blob/70dda4c9a63722e19a96d71b6b474884c253fbbe/biogeochem/EDCohortDynamicsMod.F90#L1172-L1173

**Comment by rgknox** [comment]
I think this should be alright, and is as intended.  Note that carea_allom can be run in "inverse mode", where it calculates dbh as an output from c_area, as is done in that third call. If this is tripping up some compilers, perhaps we can set dbh to -9 or some nominal nonsense value prior to the calculation.

**Comment by rgknox** [comment]
It also might be cleaner to create a new routine that handles the inverse calculation... DbhFromCrArea or something like that.
