### ISSUE TITLE
rename main branch to "main"

### ISSUE THREAD

**Issue by ckoven** [NGEET/fates#664]
Per various news sources (e.g. https://www.marketplace.org/2020/06/17/tech-companies-update-language-to-avoid-offensive-terms/, https://www.bbc.com/news/technology-53050955), github is going to make it easier to change the default branch on all repos to something other than "master", for the obvious reason that that is an offensive word. Let's proceed to make that change (to "main"?) asap once they publish the workflow to do that.

**Comment by adrifoster** [comment]
Doing this on my repos as well. Here is a good how-to guide for this (and includes a method to change the default naming convention for new repos).

[https://www.hanselman.com/blog/EasilyRenameYourGitDefaultBranchFromMasterToMain.aspx](https://www.hanselman.com/blog/EasilyRenameYourGitDefaultBranchFromMasterToMain.aspx)

**Comment by glemieux** [comment]
This has been prioritized to happen very soon.  An email will be sent out with instruction on updating remotes in users's forks of this repo.

**Comment by glemieux** [comment]
Done!

For reference, here are the commands to update your local `master` branch to `main:
```
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```
