### ISSUE TITLE
Modifying hydraulic parameters failed to achieve co-existence in ELM-FATES

### ISSUE THREAD

**Issue by yanyanchengHydro** [NGEET/fates#672]
I am trying to tune hydraulic parameters to improve ELM-FATES-simulated soil moisture and runoff in a Panama forest site. I use two forest indices for early and late succession PFTs. I met some problems when I tuned the hydraulic parameters, such as increasing saturated water content and the BSW parameter for the soil retention curve. The use_fates_planthydro is false in my case.

1. After I increase the saturated water content (WATSAT), either late or early succession PFT could not survive (they can co-exist when WATSAT is lower). So I changed the saturated hydraulic conductivity (Ksat) together to see the impact. I found increased Ksat didn’t result in co-existence, but decreased Ksat did. I thought an increased WATSAT led to a decreased Kunsat due to a lower saturated fraction, so an increased Ksat should help to increase Kunsat and water supply. But it was not the case. Can anyone suggest any mechanisms or results to look at and understand why is this happening?

2. Will modifying any plant hydraulics parameters (fates_hydr_*) help achieve co-existence when WATSAT, Ksat and the BSW parameter are modified? If so, are there any publications on the sensitivity of these plant hydraulics-related parameters in FATES?

3. It has many WARNINGs in the FatesPlantHydraulicsMod.F90 file, saying it is still undergoing testing. Will FATES still use this code if use_fates_planthydro is false?

4. I tried to use FatesPFTIndexSwapper.py to select 1 PFT to drive ELM-FATES to see if a single type of forest can grow when hydraulic parameters are modified. But the model always failed when using a parameter file with one PFT index. Does FATES force to use at least 2 indices, even if I am simulating one PFT?

Thank you very much for the help in advance.

**Comment by rosiealice** [comment]
HI @yanyanchengHydro,

In response to your point #4, I have run many global simulations with one PFT -without- FATES-HYDRO on. Are you using a recent version of FATES and FATES_NEXT_API? 

In general, achieving coexistence in all demographic models is an ongoing research problem.   @pollybuotte, @jenniferholm  , @tompowell9, @ckoven and @JessicaNeedham have all done some big ensembles with FATES looking at how modifying the parameter space can impact the outcome of competition.  It would almost certainly be most effective to perform a systematic search of the space represented by these hydraulics parameters to see what general conditions are causing the flip from early to late successional dominance. What are the differences between the two (?) PFTs you are using?  Does generally more dry or wet soil tip the balance of productivity in favour of one of them?  Is achieving coexistence your research goal here, or is it something you need to fix to look at something else? (if so, I'd suggest using one of the reduced complexity modes to assert coexistence instead).

**Comment by yanyanchengHydro** [comment]
@rosiealice Thank you so much Rosie. The FATES tag I am using is sci.1.29.0_api.7.3.0, which I guess didn't incorporate the new feature that can make fates_pft=1 to simulate one PFT?

The main difference between the early and late succession PFTs I am using is the early succession PFT has higher vcmax (65 umol/m2/s compared to 55 for late succession PFT), lower wood density (0.5 g/cm3 compared to 0.9 for late succession PFT), shorter leaf and root lifetimes (0.9 yr compared to 2.6 for late succession PFT), and greater background mortality rate (0.035/yr compared to 0.014 for late succession PFT). Usually wet soil promotes late succession PFT.

Another thing is even if I simulate one PFT, it can only survive under certain hydrological conditions. My primary research goal is to improve ELM-FATES-simulated soil moisture and runoff in the Panama forest site and analyze the impact of carbon-hydrology interaction on forest recovery dynamics. But I think the impact of hydraulic properties on co-existence can also be an interesting study? And do you have more information on the reduced complexity modes to assert coexistence?

**Comment by rosiealice** [comment]
Hi Yanyang,

I agree this could be an interested line of enquiry, and I suspect that you
will have to do some kind of ensemble to sample the space hat allows
coexistence.

On the reduced complexity modes, there are two that would be of interest.
The first is the 'static stand structure' (SST) mode, where you can use
essentially a restart-type file ot specify an existing forest type that
does not evolve over the course of the simulation. That is perhaps best to
assess the hydrological functionality on its own. I know that mode has been
used at BCI, but not by me (@ckoven, @rgknox ?)

The other mode is the 'no competition' mode I am in the course of
implementing in FATES, whereby you can specify which fraction of the grid
cell/site 'belongs' to each PFT. Thus, the demographics and LAI can change
(unlike the SST mode) but the areal fraction will no. At the moment this
version is on my branch and only works with a single patch, but if you were
interested I'm planning to get it on to the trunk in the next week or two
and to work on the patch dynamics after that.  Let me know if you think
that would suit your purposes better. More into is here
https://github.com/NGEET/fates/projects/5
and also here
https://docs.google.com/presentation/d/1_z2PIroU0AzLgwHuDf-ast-OrLPpSiSzW-liLvH5vyo/edit?usp=sharing

bye for now,
-Rosie




Le jeu. 16 juil. 2020 à 09:04, YanyanCheng <notifications@github.com> a
écrit :

**Comment by JunyanDing** [comment]
Hi Yangyang,
If you have use_fates_planthydro = false, the FatesPlantHydraulicsMod.F90 will not be used and any hydraulic parameters will have no effects. 

Junyan

**Comment by yanyanchengHydro** [comment]
> Hi Yangyang,
> If you have use_fates_planthydro = false, the FatesPlantHydraulicsMod.F90 will not be used and any hydraulic parameters will have no effects.
> 
> Junyan

Thanks Junyan for the clarification!!
