### ISSUE TITLE
CNFireFactoryMod is not allowed in FATES

### ISSUE THREAD

**Issue by rgknox** [NGEET/fates#675]
I missed this in my review of the new lightning PR, but we can't call CNFireFactoryMod (a CTSM module) from FATES.  

Called here: https://github.com/NGEET/fates/blob/master/fire/SFMainMod.F90#L44

Fix:   We add the scalar values referenced in that module to the interface.  Should not be to hard, I will make the PR.

**Comment by jkshuman** [comment]
Thanks for catching this @rgknox . Will make more sense to me when I see your change.
