### ISSUE TITLE
Possible source of water balance error in FATES-Hydro

### ISSUE THREAD

**Issue by JunyanDing** [NGEET/fates#677]
I ran the pine and cedar along an environment gradient transect at Southern Sierra. In the setup, pine and cedar have different vulnerability curves: 
 
![image](https://user-images.githubusercontent.com/43835195/88851600-d0b9d180-d1a1-11ea-9d37-508e668c1bcd.png)

The single PFT simulations ran well, but with 2PFTs together, the model crashed on some grids from water balance error.
In the FATES, the total transpired water allocated to each individual plant is proportion to the leaf area weighted stromal conductance of that cohort to the canopy stomatal conductance by 
https://github.com/NGEET/fates/blob/master/biogeophys/FatesPlantHydraulicsMod.F90#L2356
if(ccohort%g_sb_laweight>nearzero) then
                qflx_tran_veg_indiv     = bc_in(s)%qflx_transp_pa(ifp) * cpatch%total_canopy_area * & 
                (ccohort%g_sb_laweight/gscan_patch)/ccohort%n
I think this may be the source of water balance error. A plant can have high stomatal conductance but low xylem conductance (due to cavitation), thus transpire little water even with high gs. It is the whole plant conductance determine how much water a plant transpire. For 1 PFT, whole plant conductance scale with stomatal conductance in the same manner, so use stomatal conductance to determine the proportion of the total transpiration of the plant is fine. But when 2 PFT having different vulnerability curves, the whole plant conductance scale with stomatal conductance in different rates, using stoma alone causes problem.  I think we should use the total conductance of the plant instead of stomatal conductance to calculate this ratio term “ccohort%g_sb_laweight/gscan_patch”, something like:  Ccohort%g_k_sb_laweight/gk_can_patch” 
We can calculate the whole plant conductance from the conductance of each compartment using Ohm’s law, and to upscale to canopy level.

@rgknox , @bchristo , and @xuchongang What’s your opinion?

**Comment by rosiealice** [comment]
So, in principle, @JunyanDing, shouldn't a low xylem conductance cause a low LWP, and therefore a low stomatal conductance and therefore transpiration should be indirectly controlled by the xylem in that way (which is, I think, how it should work in real life)

Or are you suggesting that minor issues in the solver could cause, say, lags between embolism of the xylem and stomatal closure that eventually lead to water balance errors (if, e.g. a leaf is trying to transpire water that it doesn't have?) Say, if there is very little capacitance in the system and the stomata do not close quickly enough in response to running out of water?

**Comment by rgknox** [comment]
This is an interesting point @JunyanDing .  I'm guessing that if  the stomatal conductance drop-off as a function of psi, is less steep than the conductance drop-off between stem and leaf, that could also generate issues.

I am worried that by using the total conductance, we will be removing the model's ability to capture certain dynamics, like where the stem really can't keep up with leaf transpiration demand, and the leaves respond.

I wonder if, prior to calculating stomatal conductance (in photosynthesis), we could run a simplified analytical solve on the leaf and stem compartment (or just leaf)... The solve would have a no-flow boundary condition into the stem (from TRoot side), and seek to determine the maximum allowable stomatal conductance.

**Comment by JunyanDing** [comment]
You are so right, @rgknox ! Shouldn't use the whole plant conductance. 

Your solution is better. We can use the adjusted stomatal conductance to determine transpiration.  Not sure whether we should include both stem and leaf in the analytical solving, or just leaf.

**Comment by rgknox** [comment]
There might be another issue at play here.  Earlier on in my refactor, I realized that we did not have any information on petiole conductance, and since I assumed that it would be harmonically averaged with the upper compartment of the stem's conductance, I set it very high:
https://github.com/NGEET/fates/blob/master/biogeophys/FatesPlantHydraulicsMod.F90#L2707
Since this is a harmonic average, it essentially ignores the very high kmax in the petiole.  But..

Later on, I modified the default behavior so that the wet side conductance is the only one that is used, and essentially copies the wet side conductance to the dry side before averaging.  If the leaf has slightly higher potential than the stem, for any reason, the  flow will reverse out of the leaf, and will use the petiole kmax (in series), which is massive.

**Comment by rgknox** [comment]
One thing I would like to try is to not allow upstream-only conductance if the upstream is the leaf.  Will write up a little patch and post.

**Comment by rgknox** [comment]
or, we could just come up with a reasonble estimate of petiole/leaf vein conductance

**Comment by rgknox** [comment]
Here is what the patch would look like:
https://github.com/NGEET/fates/compare/master...rgknox:petiole-upstream-fix

**Comment by JunyanDing** [comment]
@rgknox , I think assign petiole kmax (kmax_petiole_to_leaf, the petiole/leaf vein conductance?) a high value does cause problem. Perhaps, we could assign it (kmax_petiole_to_leaf) the same value of downstream side of stem kmax (kmax_stem_upper)?   
The change you proposed (https://github.com/NGEET/fates/compare/master...rgknox:petiole-upstream-fix)
seems only changes the fraction of kmax, but not eliminates the conductance of the upstream if it is the leaf ? So, if we have high kmax_petiole_to_leaf, then we still have high petiole-leaf xylem conductance. I may misunderstand the codes, please correct me if I am. You know much better about the codes than me :)
Let me know what you think.

**Comment by rgknox** [comment]
Actually, you bring up a good point again @JunyanDing.  That patch should not be necessary.  I crossed some wires and forgot that we do always use the harmonic average (series resistance) of the conductances, its just the fractional loss of conductivity that we apply from the upstream side.

**Comment by JunyanDing** [comment]
Hi @rgknox,  @pollybuotte ,@ckoven,   Below is my approached to use adjusted gs to deal with this issue,
![image](https://user-images.githubusercontent.com/43835195/89337823-7365ca80-d650-11ea-950b-d7b890e4bdf7.png)
Please let me know what you think, is this feasible, and/or if you have any questions.

**Comment by rgknox** [comment]
I think the simplest way to get f(), would be to say that during this calculation the leaf compartment has a no-flow boundary through the petiole (not exactly what you proposed), and that E_h balances the change in volume in the comaprtment:

E_h  =   rho * V theta  / (Delta t)

As psi in the leaf compartment drops, you will have a dynamic response of g_s

Alternatively, maybe we can come up with a quick or reduced analytical solve to also add in the stem compartment, so it would be a system of two equations, allowing flow between leaf and stem.

E_h  =   rho * V_leaf * theta_leaf  / (Delta t) + q_stem_to_leaf

q_stem_to_leaf = - rho * V_stem * theta_stem / (Delta t)

**Comment by rgknox** [comment]
note this would be integrated just like the ODE's for the main hydraulics solve, but this would be a much smaller system.  The big difference is that now the leaf to atmosphere boundary condition is not constant. The flux E_h would be evaluated as a result of the solve.

**Comment by rgknox** [comment]
I think the part we are missing here though, is that the g_s in your equation 1, contains the effects of photosynthesis on stomatal control.   

Here is where we set 1/g_s that is used in the patch-level transpiration calculation:
https://github.com/NGEET/fates/blob/master/biogeophys/FatesPlantRespPhotosynthMod.F90#L769-L770
.

**Comment by glemieux** [comment]
@JunyanDing is there any update on this from your side?

**Comment by JunyanDing** [comment]
@glemieux  we have solved this issue by introducing the control of leaf water potential on the supply. The change is in the hydro module of current FATES version.

**Comment by glemieux** [comment]
Closing per #736
