### ISSUE TITLE
odd/even cohort number setting drought status on restarts

### ISSUE THREAD

**Issue by rgknox** [NGEET/fates#68]
### Summary of Issue:

During restarts, cohorts are initialized (allocation and some starter values) in CreatePatchCohortStructure() and then the cohort values are filled in during convertCohortVectorToList().

However, during the initialization process, the PFT of the initializing cohort is alternated (see "ft" below), and the even cohorts are set to a different growth status as the odds (leaves on versus off).  

From what I can tell, the code is assuming an order of pftcon%stress_decid(ft).  

Also, it looks like it really doesn't matter what the cohortstatus is, because it appears that the values it sets in create_cohort() are overwritten during convertCohortVectorToList() anyway.  I believe the same is true for the cohorts pft value.

Anyway, just take a look and chime in.

```
             ! set the pft (only 2 used in ed) based on odd/even cohort
             ! number
             ft=2
             if ((mod(fto, 2)  ==  0 )) then
                ft=1
             endif

             cohortstatus = newp%siteptr%status

             if(pftcon%stress_decid(ft) == 1)then !drought decidous, override status. 
                cohortstatus = newp%siteptr%dstatus
             endif
```

I believe two solutions should be acceptable: 1) just pass an arbitrary dummy variable to the create_cohort() subroutine following this logic, and just leave it at that.   or 2) read in the pft variable from the cohort vector list during initialization.

Any thoughts?

**Comment by ckoven** [comment]
this got fixed at some point. closing.
