### ISSUE TITLE
canopy resistance scaling of PFTs to patches needs some reworking

### ISSUE THREAD

**Issue by ckoven** [NGEET/fates#690]
Hi all -- a question came up on a call this morning about how some of the patch quantities get calculated for the canopy resistance calculations.  Right now this PFT->patch upscaling is too simple, as it is using the values of the first PFT for three of the parameters, which is sort of obviously just a placeholder.  Since in the default param file there is no PFT variation for any of these parameters (also a problem, but a separate one) the current placeholder code shouldn't be affecting results, but as that may change at any point, we should update this sooner rather than later.  I don't think anyone is actively working on this so wanted to raise this as an issue to fix.

The relevant code is here:
https://github.com/NGEET/fates/blob/master/biogeochem/EDCanopyStructureMod.F90#L1943-L1945

The parameters being used here are these three:
https://github.com/NGEET/fates/blob/master/parameter_files/fates_params_default.cdl#L501
https://github.com/NGEET/fates/blob/master/parameter_files/fates_params_default.cdl#L131
https://github.com/NGEET/fates/blob/master/parameter_files/fates_params_default.cdl#L251

I guess I'd propose we keep this simple here, and try find a solution only slightly more complex than the existing code. Possibilities include:
1. use a weighted average of the PFTs, with PFT weighting based on either crown area, leaf area, or canopy-only crown area
2. use the value of the dominant PFT on that patch (where dominant is defined again using either leaf area, crown area, or canopy-only crown area)
3. something else? I guess a more complex approach would be to trace through how each of these are used and calculate some averaging that approximates the mean of the function rather than the function of the mean?

**Comment by rosiealice** [comment]
Hi @ckoven.  Indeed, this is a very/embarrasingly old placeholder. 

I feel like I did in fact write a scheme to make a weighted average for these, but that was back in the bad old days before github and so it perished somewhere. 

I think that option 1) is preferable, fwiw, scaled by leaf area for dleaf and displa and maybe by biomass for z0?

**Comment by ckoven** [comment]
@rosiealice ok great.  I agree on weighting dleaf and displa by leaf area but suggest we weight z0 by fractional crown area in the canopy.  that way it will naturally ignore understory plants and also average in zero height for bare area when the canopy is not closed. or do we need to average a bare-soil roughness for open areas?

**Comment by rgknox** [comment]
Maybe we should weight by total area index (LAI + stem AI).  Since these indices are invoking drag and affecting canopy turbulence, we should include all surfaces.  Moreover, this will prevent weirdness when leaves are off.

**Comment by rosiealice** [comment]
Agreed that we want to avoid strangeness when the leaves aren't on...

**Comment by rgknox** [comment]
see: https://github.com/ESCOMP/CTSM/issues/1316
