### ISSUE TITLE
A plea for comments on 'end if', 'end do' and 'else' statements

### ISSUE THREAD

**Issue by rosiealice** [NGEET/fates#691]
This is really more of a plea that an issue. After a couple of days of trying to figure out what unfamiliar code does, I realize that I typically spend 70% or so of that effort trying to match 'if's with 'end if's and 'do's with 'end do's. There are many places where a lot of code resides inside such loops, and matching them up is pretty arduous. 

I'd thus like to propose that in general we try and add comment to the 'end if' and 'end do' statements, (one word to say which loop/if statement they belong to) to facilitate understanding for future developers? 

Thoughts on this idea?

**Comment by glemieux** [comment]
I agree.  I've found having this helpful in the past as well, particularly when I was updating the `trim_canopy` function:
https://github.com/NGEET/fates/blob/154bd2956a65c8afa55a765554c7bf95727c0669/biogeochem/EDPhysiologyMod.F90#L607-L612

**Comment by ckoven** [comment]
Yeah, I agree too.  Sorry that I haven't been good about doing this myself, will try to improve.

**Comment by rgknox** [comment]
This is a good practice, @rosiealice , I will try to adhere to it too.

FWIW, one can also enforce active labeling on loops, like here:  https://github.com/NGEET/fates/blob/master/biogeophys/FatesPlantHydraulicsMod.F90#L4655

Which closes here: https://github.com/NGEET/fates/blob/master/biogeophys/FatesPlantHydraulicsMod.F90#L5028

Although, this technique is mostly used to enable the "cycle()" intrinsic to send you to the end of a desired loop, you don't need to have the cycle statement to use the loop's label enforcement.

**Comment by bpbond** [comment]
@rgknox oh wow I didn't know that, thanks.

**Comment by rgknox** [comment]
Made some updates to the style guide: https://github.com/NGEET/fates/wiki/Coding-Practices-and-Style-Guide

**Comment by ekluzek** [comment]
I think if you add a label for a loop -- you should as @rgknox points out use the FORTRAN syntax for labels on loops. That will ensure it's correct.

The other part to remember is the maintenance on the comments. If loops or ifs change you have to update the ending comments, or they'll be wrong. That's one reason to use the label syntax for loops, it'll be correctly maintained with updates.

The labels do take some room in the left white space margins -- so if you use them, the starting white space margin should likely be 7 to 10 spaces deep, so you can have labels of at least 5 characters. So you might want to make sure that the starting whitespace starts fairly deeply indented.

@rosiealice another question is if this should just be done for loops and if statements that have many lines in them. I think if they just have a few lines you probably don't need it. @rgknox comment gives the guideline of over 50 lines.

I'll try to bring this up for CTSM as well.

**Comment by minxu74** [comment]
I wonder if the code structure collapse/expand folding features of  popular editors like vim or emacs can be helpful or applied here to match if and do blocks easily.

**Comment by rosiealice** [comment]
To be clear, I just mean this as a point to note going forward, rather than imposing it on the whole existing codebase.

**Comment by billsacks** [comment]
I was thinking about this a bit today. I would suggest only doing this where the compiler can enforce it – which I think is just on 'do' statements – and then (as others have noted) only when the loops are long.

I think the maintenance issue is a real problem if you rely on comments. Comments often don't get updated, and I personally wouldn't trust any comments like this in code: it's too easy for a minor code rework to lead to the wrong comment being on an "end if" statement. A wrong comment is MUCH worse than no comment at all, because it can give a false sense of security that leads to bugs.

I can only speak for emacs, but for emacs, if you hit tab on a line with an "end if" or "end do", you will be shown the corresponding "if" or "do" statement – in the main window if it's there, and otherwise in the minibuffer at the bottom of the screen. I imagine most editors have similar capabilities, and if they don't, you should just switch to emacs :-P

**Comment by billsacks** [comment]
Sorry, I feel that I should clarify that my last statement was meant entirely tongue-in-cheek (even though my tongue didn't manage to stay inside my mouth in the emoji). I did a quick search and it seems like vim offers similar capabilities: https://stackoverflow.com/questions/32585697/vim-jumping-to-if-endif-in-fortran

**Comment by ekluzek** [comment]
And I checked that adding this to my .vimrc works as advertised and it does. So you use the % key to go between the start and end of the if or do loop.

```
filetype plugin on
runtime macros/matchit.vim
```

So I think I agree with @billsacks use labels for long loops, but use your editor to check how if's are matched (and make sure you use whitespace indentation). It is easy for comments to get out of date (and that's also a good reminder to make sure when you modify code that you edit the comments associated with a section you change).
