### ISSUE TITLE
Use HLM's temperature and moisture scalars for litter fragmentation instead of FATES functions

### ISSUE THREAD

**Issue by ckoven** [NGEET/fates#699]
Currently in the FATES/HLM scope of processes, the HLMs handle decomposition type things while FATES handles the plants and also the fragmentation of recently-deceased tissues that can contribute to fire, since those need to be tracked at the patch level of organization.  For the litter and CWD fragmentation, FATES is calculating temperature and moisture scalars that represent the environmental control on their fragmentation rates.  But the values of the temp and moisture scalars for litter fragmentation in FATES are ending up being quite different from the ones that the HLMs calculate for decomposition.  I'd like to propose that we unify these by passing the HLM's decomposition temperature and moisture scalars at a daily mean and at some suitable depth across the HLM/FATES interface, and just have FATES use those instead of trying to calculate them itself.

Discussed with @jkshuman who is I believe in support of this.

**Comment by jkshuman** [comment]
@ckoven agreed. Thanks for opening this, and for talking it over with me. I support the change you propose.

This will certainly change behavior, and I am curious to see how things go. In the fire module the values of max_decomp have been a strong control on modulating litter pools which are fuel for fire. These values needed to be changed for different regions, suggesting the value of the fragmentation_scalar set by temp and moisture were not effective. 
here is that fragmentation_scalar location in the code:
https://github.com/NGEET/fates/blob/61a751c37181f18162e23851fff495db62fc807a/biogeochem/EDPhysiologyMod.F90#L2285

A switch to the values of the HLM makes sense, or we need justification as to why we are using different values in FATES. 

https://github.com/NGEET/fates/blob/61a751c37181f18162e23851fff495db62fc807a/biogeochem/EDPhysiologyMod.F90#L2321-L2322

Perhaps with this change we can use a common set of max_decomp values across regions.
