### ISSUE TITLE
Pointer deallocate with cray compiler

### ISSUE THREAD

**Issue by amametjanov** [NGEET/fates#702]
In E3SM's `ERS_Ld20.f45_f45.IELMED.theta_cray.elm-fates` test with cray compiler `cce/10.0.1`, getting an error on deallocate of a pointer pointing to previously allocated `ed_cohort_type` instance:
```
40: lib-4412 : UNRECOVERABLE library error
40:   An argument in the DEALLOCATE statement is a disassociated pointer, an
40:  unallocated array, or a pointer not allocated as a pointer.
```

This is probably cray-specific, but indirect deallocation (through loop pointers) fails. This patch lets the run complete without errors:
```
diff --git a/biogeochem/EDCohortDynamicsMod.F90 b/biogeochem/EDCohortDynamicsMod.F90
index 3e3e2533..fd6e46b1 100644
--- a/biogeochem/EDCohortDynamicsMod.F90
+++ b/biogeochem/EDCohortDynamicsMod.F90
@@ -786,7 +786,7 @@ contains


           call DeallocateCohort(currentCohort)
-          deallocate(currentCohort)
+         !deallocate(currentCohort) !currentCohort is a pointer, just disaccosiate it
           nullify(currentCohort)

        endif
@@ -1386,7 +1386,7 @@ contains
                                    endif

                                    call DeallocateCohort(nextc)
-                                   deallocate(nextc)
+                                  !deallocate(nextc) !nextc is a pointer, just disaccosiate it
                                    nullify(nextc)


```

**Comment by rgknox** [comment]
Thanks for the submission @amametjanov .  The currentCohort and nextc structures do need to be released of their memory in both these contexts.  Without these deallocations, fates will generate pretty massive memory leaks since we are constantly spawning these cohort data-structures anew.
They should be associated pointers at the time of deallocation though, I wonder why in this case they are not.   Is this a new compiler?

**Comment by rgknox** [comment]
@amametjanov , is the error triggering immediately upon attempting its first deallocation, or does this occur later on?

**Comment by amametjanov** [comment]
This is with Cray compiler `cce/10.0.1` that is re-introduced back into E3SM. The error is triggered immediately.

I'm looking into possible memory leaks with valgrind to see about other alternatives.

**Comment by rgknox** [comment]
That's actually good to hear.  I would be more worried about the latter, as it would imply that FATES is doing something very wrong in passing a truly unassociated pointer in a certain context.

**Comment by amametjanov** [comment]
Correction to my previous comment: error occurs during day 4, from lnd.log:
```
 Beginning timestep   : 0001-01-04_00:30:00
 clm: calling FATES model  145
FATES Dynamics:    1-01-04
```

I thought this was Cray-specific, but the error occurs with IBM compiler `xl/16.1.1-7` on Summit too. Runs with Intel and GNU are fine though.

After instrumenting deallocates with return status codes:
```
diff --git a/biogeochem/EDCohortDynamicsMod.F90 b/biogeochem/EDCohortDynamicsMod.F90
index 3e3e2533..b309bed7 100644
--- a/biogeochem/EDCohortDynamicsMod.F90
+++ b/biogeochem/EDCohortDynamicsMod.F90
@@ -671,6 +671,7 @@ contains
     integer :: terminate  ! do we terminate (itrue) or not (ifalse)
     integer :: c           ! counter for litter size class.
     integer :: levcan      ! canopy level
+    integer :: istat      ! return status code
     !----------------------------------------------------------------------

     currentCohort => currentPatch%shortest
@@ -786,7 +787,10 @@ contains


           call DeallocateCohort(currentCohort)
-          deallocate(currentCohort)
+          deallocate(currentCohort, stat=istat)
+          if (istat.ne.0) then
+             write(fates_log(),*) 'warn: in terminate_cohorts non-zero status of deallocate(currentCohort)',istat
+          endif
           nullify(currentCohort)

        endif
@@ -928,6 +932,8 @@ contains
      ! ----------------------------------------------------------------------------------

      type(ed_cohort_type),intent(inout) :: currentCohort
+     integer                            :: istat         ! return status code
+     character(len=255)                 :: smsg

      ! At this point, nothing should be pointing to current Cohort
      if (hlm_use_planthydro.eq.itrue) call DeallocateHydrCohort(currentCohort)
@@ -936,7 +942,8 @@ contains
      call currentCohort%prt%DeallocatePRTVartypes()

      ! Deallocate the PRT object
-     deallocate(currentCohort%prt)
+     deallocate(currentCohort%prt, stat=istat, errmsg=smsg)
+     if (istat.ne.0) write(fates_log(),*) 'warn: in DeallocateCohort non-zero status of deallocate(currentCohort%prt)',istat,smsg

      return
   end subroutine DeallocateCohort
@@ -993,6 +1000,8 @@ contains

      logical, parameter :: fuse_debug = .false.   ! This debug is over-verbose
                                                  ! and gets its own flag
+     integer  :: istat         ! return status code
+     character(len=255) :: smsg

      !----------------------------------------------------------------------

@@ -1386,7 +1395,10 @@ contains
                                    endif

                                    call DeallocateCohort(nextc)
-                                   deallocate(nextc)
+                                   deallocate(nextc, stat=istat, errmsg=smsg)
+                                   if (istat.ne.0) then
+                                      write(fates_log(),*) 'warn: in fuse_cohorts non-zero status of deallocate(nextc)',istat,smsg
+                                   endif
                                    nullify(nextc)


```
the error is with deallocation of PRT object in `fuse_cohorts`, from e3sm.log:
```
1: 7:  warn: in DeallocateCohort non-zero status of deallocate(currentCohort%prt) 2 1525-207 An invalid data object has been specified for the DEALLOCATE statement.
1: 7:  warn: in fuse_cohorts non-zero status of deallocate(nextc) 2 1525-207 An invalid data object has been specified for the DEALLOCATE statement.
```

Reading of deallocate `stat` codes lets the run proceed to completion, but this should probably to be fixed: i.e. all deallocate calls read `stat` codes and all statuses are 0.

Overall, there is a memory leak (in runs with written-out `stat` codes) on the order of 3MB per simulation day: based on e3sm.log `sysmem ... rss` stats (valgrind output has too many false positives).

A reproducer on Summit is `cime/scripts/create_test SMS_Ld20.f45_f45.IELMED.summit_ibm.elm-fates`. Can you take a look?

Some relevant specs from https://www.ibm.com/support/knowledgecenter/SSGH4D_16.1.0/com.ibm.xlf161.aix.doc/language_ref/dealloc.html 

> An allocatable object with the TARGET attribute cannot be deallocated through an associated pointer.

and 

> Deallocation of a pointer target causes the association status of any other pointer associated with all or part of the target to become undefined.
