### ISSUE TITLE
prescribed nuptake and puptake value checking

### ISSUE THREAD

**Issue by rgknox** [NGEET/fates#708]
When running a carbon only run, we should not enforce expected range of prescribed N uptake and P uptake.

Here is an error that charlie generated:

Negative values for EDPftvarcon_inst% prescribed_nuptake(:)
 are not allowed. Reasonable ranges for this parameter are zero
 to something slightly larger than 1, so we set a cap at 10.
 Set to zero to turn off and use coupled nutrients.
  Aborting
 ENDRUN:
 ERROR in EDPftvarcon.F90 at line 1484

**Comment by glemieux** [comment]
This is still relevant.  We discussed updating the results within the context of the existing case-specific parteh mode check.
