### ISSUE TITLE
Smoothing parameters mysteriously affect canopy water use efficiency

### ISSUE THREAD

**Issue by rosiealice** [NGEET/fates#748]
A while ago, following @walkeranthonyp 's discovery that smoothing parameters have a large impact on GPP, and the general consensus that they were perhaps less necessary in a multi-layer model, we switched FATES to not use 'smoothing' functions between the two rate-limiting photosynthetic processes (carboxylation and electron transport.  This happens here:
https://github.com/NGEET/fates/blob/1723d1443a2bc84f15f9b4e6e637592b49790971/biogeophys/FatesPlantRespPhotosynthMod.F90#L1036

Smoothing was used to ‘introduced to "_allow a more realistic, gradual transition from one limitation to another, and to allow for some co-limitation_" and the background to this is covered in Walker et al 2021 https://onlinelibrary.wiley.com/doi/pdf/10.1111/gcb.15366

That studydidn't look at the water cycling implications of changing the smoothing parameters. During my investigations of the difference betwen CLM5-SP and CLM-FATES-SP modes, I noticed a big influence of the smoothing change on ET and GPP. 

![SPcomp_WUE_prog_4](https://user-images.githubusercontent.com/12954691/120158565-8e638580-c1f4-11eb-98dd-7bdffdd9ccdc.png)

Firstly, curious, as at a leaf level, WUE should not be affected by the smoothing. GPP feeds into the stomatal conductance calculations downstream of the smoothing and so the WUE of leaves should be determined by the stomatal slope parameters primarily.  

Secondly, this is mildly alarming, as the change in WUE is significant and, being unexplained, provides a very large lever on the model output. Without smoothing, the WUE is higher, and so ET is lower per unit GPP, which means that one needs to have a much higher stomatal slope to simultaneously fit canopy-scale-and-above observations of ET and GPP. 

Nothing that I'm not suggesting that one or the other is more or less correct, but instead that we need to at least understand the dynamics of what is going on. My suspicion is that the answer is to be found in looking at the layers output with and without smoothing, and also potentially (as per @tompowell9's suggestion( that having layered GPP but a single canopy conductance might also have a role to play).  Putting this as an issue to note that this is TBD... 

Tagging NGEET RFA1 people (@alistairrogers @serbinsh @Qianyuxuan ) as this obvs affects your  domain!

**Comment by alistairrogers** [comment]
I would expect WUEi (A/gsw) to be greater after removing smoothing because for the same Ci (same gsw) you will get a higher modeled A. Note that the data used to derive g1 values do not include a smoothing parameter and so the derived g1 values used for parameterization should be consistent with unsmoothed modeling of A. If you give the smoothed version a higher Vcmax it should shrink the effect. Checking the impact of smoothing on the iterative solver might also be valuable.

**Comment by rosiealice** [comment]
Thanks Alistair.  

That kind-of makes sense to me, if you think of gs as a given, but.... Shouldn't gs then also go up if A increases, on account of the formulation of the BB term?  (I probably haven't thought about the dynamics of Ci enough. )

 Also, you would expect to see this leaf-level behavior in MAAT, right? (I think @walkeranthonyp  said he didn't see it) 

Oh, and I just also realized that my plots are of WUE as GPP/ET,  not GPP/gs. Not sure if that changes the interpretation?  

Anyway, thanks for the discourse. Will be good to get to the bottom of this!

**Comment by walkeranthonyp** [comment]
Yes, I was thinking the same @alistairrogers but when I looked at maat output iWUE dis not change with smoothing. 

On second thought that makes sense given iWUE is determined entirely by the gs EQ and neither smoothing nor Ci feature in that. Although Cb does I'd be surprised if that was our culprit here (tho I am already surprised).

@rosiealice a gpp/Gc plot might help with the diagnosis.

**Comment by alistairrogers** [comment]
@walkeranthonyp wow that is surprising. What happens to Ci, Ci:Ca and gsw. If A goes down but WUEi stays the same something has to give.

**Comment by rosiealice** [comment]
Closing this as it eventually turned out to be a red herring.
