### ISSUE TITLE
New Parameters Inbound

### ISSUE THREAD

**Issue by rgknox** [NGEET/fates#753]
There are few new parameters that are imminent. 

See the following PRs:

#752 
 - scalar:  ED_val_vai_top_bin_width
 - scalar: ED_val_vai_width_increase_factor

#724
 - Leaf photosynthetic temperature acclimation timescale

#738 
     real(r8), allocatable :: allom_dbh_max(:)  
     real(r8), allocatable :: allom_dbh_0(:)
     real(r8), allocatable :: allom_zfr_max(:)
     real(r8), allocatable :: allom_zfr_0(:)
     real(r8), allocatable :: allom_frk(:)

#737
    real(r8), allocatable :: hydr_alpha_vg(:)      ! capilary length parameter in van Genuchten model 
     real(r8), allocatable :: hydr_m_vg(:)          ! pore size distribution, m in van Genuchten 1980 model range (0,1)
     real(r8), allocatable :: hydr_n_vg(:)          ! pore size distribution, n in van Genuchten 1980 model range >2
     real(r8), allocatable :: hydr_k_lwp(:)         ! inner leaf humidity scaling coefficient 

#736  
real(r8), allocatable :: hydr_k_lwp(:)         ! inner leaf humidity scaling coefficient

#703
real(r8), allocatable :: hlm_pft_map(:,:)           ! Mapping from HLM PFTs to FATES PFTs in fixed biogeog mode. 

It would be nice to consolidate these into one PR to help people with updating their code.  I will work with authors to finalize the list of parameters. Will roll this out before the referenced PRs (except for SP, if SP is ready first, I think we should just let SP do its thing)

@ckoven
@JunyanDing 
@rgknox 
@rosiealice 
@glemieux

**Comment by ckoven** [comment]
As we will want to update the leaf maintenance respiration model shortly to also allow acclimation (PR #729), we should at a minimum figure out what the parameters for that will be and include them as well here.  Also which of these updates will require switches to turn on or off?  I imagine at a minimum, a switch to choose acclimating/non-acclimating photosynthesis for #724, a switch to turn on/off the size-dependent rooting depth for #738, anything else?

**Comment by rgknox** [comment]
As an option, for the acclimation timescale, -1 or 0 could be a special value flagging that its not used.

For the rooting depths, by setting the dbh at maximum rooting depth to zero and the maximum rooting depth to the bottom of the soil column it should force cohorts to always have deep roots (current hypothesis).

**Comment by ckoven** [comment]
let's fix a typo in the parameter file too:
https://github.com/NGEET/fates/blob/master/parameter_files/fates_params_default.cdl#L1009

there is a 2 in the `fates_maintresp_reduction_intercept` field that shouldn't be there...

**Comment by rgknox** [comment]
As part of #737, I'm going to add a parameter switch that allows the user to option between Van Genuchten and TFS types of pressure-volume and pressure-conductivity curves.  "hydr_pvpk_mode"  1=TFS,   2=VG

**Would anyone like this switch dimensioned by plant organ?** For instance, this would allow a user to specify VG for the various internal plant compartments and TFS for the stomata, or any combination they desire. My sense is that perhaps this is over-complicated, but wanted to get people's opinions.
@JunyanDing 
@xuchongang 
@pnlfang 
@pollybuotte 
@tompowell9 
@bchristo 

Also, we have the following naming convention for some tfs specific parameters:   "hydr_avuln_node".  I think it would be nice to suffix these with "_tfs", for instance: "hydr_avuln_tfs".  This way the user can quickly identify which parameters are relevant depending on the PV/PK model they are using.  The downside is that people have to make more modifications to their existing parameter files to keep them compatible (although they will have to make modifications anyway).

**Comment by JunyanDing** [comment]
@rgknox I like this option. I think TFS is better for leaf while VG is better for xylem. Thanks.

**Comment by rgknox** [comment]
edit of previous post:  Stomatal conductance has its own parameters and separate parameters from those that govern pressure-volume and pressure-conductivity in the plant organs.  We currently only have one hypothesis (TFS) that regulates stomatal conductance from leaf-water-potential. The current proposal will not change that.

**Comment by rgknox** [comment]
The PR can be found here: #759

**Comment by rgknox** [comment]
Parameters added via #759
