### ISSUE TITLE
Typo for "fates_phen_c" ?

### ISSUE THREAD

**Issue by jenniferholm** [NGEET/fates#756]
Hi, 
Quick question. What should the parameter value be for "fates_phen_c", the exponent in the GDD threshold equation. Should it be "0.01 or 0.001"? 
Because in the parameter file it is 0.01, but when the equation was hard coded in EDPhysiology for reference the value is 0.001.  Do we think it's a typo in the commented out line at https://github.com/NGEET/fates/blob/1758ffef93ce05e7103689fd3e47880ba7c8d795/biogeochem/EDPhysiologyMod.F90#L792 ?
I'm also getting confused because an old version of a parameter file I've been using has phen_c as 0.001 (like in the code). But I can't remember I changed that myself or not.

Is there a publication where these constants come from?  Because this is leading to some kind of big differences in cold deciduous trees with leaf-on and GDD > gdd_threshold. 

!GDD accumulation function, which also depends on chilling days.
    !  -68 + 638 * (-0.001 * ncd) 
    gdd_threshold = ED_val_phen_a + ED_val_phen_b*exp(ED_val_phen_c*real(currentSite%nchilldays,r8))

Has this been bought up before, and I missed it?

**Comment by ckoven** [comment]
Looking this up in the tech note, this equation and parameters come from Botta et al (2000), and their c parameter is -.01 (table 4 of 
https://onlinelibrary.wiley.com/doi/epdf/10.1046/j.1365-2486.2000.00362.x )

**Comment by jenniferholm** [comment]
Awesome, thanks for the quick clarification!

**Comment by rgknox** [comment]
closing, feel free to re-open if needed @jenniferholm
