### ISSUE TITLE
FatesPFTIndexSwapper.py needs updating to api 16.1

### ISSUE THREAD

**Issue by rgknox** [NGEET/fates#763]
FatesPFTIndexSwapper.py will not work on the new parameter file as per 16.1.  This is due to new dimension combinations. Thanks for bringing this up @JessicaNeedham 

I will patch, but feel free to use this in the mean time:

https://drive.google.com/file/d/132HEMeZPv0OJKPkFXiMxYByKR7cLc7jK/view?usp=sharing

**Comment by adrifoster** [comment]
I am using this new FatesPFTIndexSwapper.py, which works, but I am getting some runtime warnings.

From FatesPFTIndexSwapper.py I get this warning seemingly when it is just about finished:

```
/home/afoster/env/lib/python3.7/site-packages/scipy/io/netcdf.py:312: RuntimeWarning: Cannot close a netcdf_file opened with mmap=True, when netcdf_variables or arrays referring to its data still exist. All data arrays obtained from such files refer directly to data on disk, and must be copied before the file can be cleanly closed. (See netcdf_file docstring for more information on mmap.)
  ), category=RuntimeWarning)
Cloneing complete!
```

From the modify_fates_paramfile.py, when I try to change the pft names I get this error:

```
/project/tss/afoster/ctsm_fates/src/fates/tools/modify_fates_paramfile.py:65: DeprecationWarning: string or file could not be read to its end due to unmatched data; this will raise a ValueError in the future.
  outputval = np.fromstring(args.val, sep=',', dtype=np.float32)
replacing prior value of pft name for PFT 1, which was "needleleaf_evergreen_extratrop_tree", with new value of "pice_mari"
replacing file: /project/tss/afoster/parameter_files/param_file_canada.nc
```

I'm not totally convinced this one isn't an error on my end, but it still seems to work. It also just seems like `np.fromstring()` is deprecated in its current use. Things still seem to go okay, so just wanted users to be aware of potential warnings.
