### ISSUE TITLE
Mismatch between variable print in FatesHistoryInterfaceMod.F90 and output file

### ISSUE THREAD

**Issue by mariuslam** [NGEET/fates#778]
Hi,

I am trying to add a site_pft variable in FatesHistoryInterfaceMod.F90.
Unfortunately, when I ncdump the variable in the hist file it does not correspond to the value it should be.
The value is right when I print it at the place where it is weighted in FatesHistoryInterfaceMod.F90. Exemple, if there is only one cohort and one pft, then number_fraction_pft=1, hio_hard_level_pft=ccohort%hard_level=-2, but in the output file, HARDINESS=-1

I copied below a part of the relevant code but the github file can be found here:
https://github.com/mariuslam/Fates_single_site/blob/c885dee7074ce2ebc32febbcd041f1bd944485cf/main/FatesHistoryInterfaceMod.F90#L2420-L2430

I also added a picture of an ncdump on the variable and a the log file with the corresponding prints.

I would be very thankful if anyone has suggestions to explore or a clue of what is going on.
Thanks in advance,

Marius Lambert, University of Oslo

!____________________________CODE in History file____________________
ipft = ccohort%pft
number_fraction_pft = (ccohort%n / ncohort_pft(ipft))

hio_hard_level_pft(io_si,ipft) = hio_hard_level_pft(io_si,ipft) + ccohort%hard_level * number_fraction_pft

write(fates_log(),*) 'check1',number_fraction_pft
write(fates_log(),*) 'check2',ccohort%hard_level ,hio_hard_level_pft(io_si,ipft)
!----------------------------------------------------------------------------------------------------------------
![image](https://user-images.githubusercontent.com/44898967/134679475-3cb5c57e-99d5-42aa-a874-816dfab3523a.png)
[lnd.log.3554735.210922-113454.gz](https://github.com/NGEET/fates/files/7225771/lnd.log.3554735.210922-113454.gz)
[1x1_Caxiuana_era_FATES_hydro_evergreen_PART1_1m_hardening_print_hist_deg.clm2.h0.1921-01-01-00000.nc.gz](https://github.com/NGEET/fates/files/7225772/1x1_Caxiuana_era_FATES_hydro_evergreen_PART1_1m_hardening_print_hist_deg.clm2.h0.1921-01-01-00000.nc.gz)

**Comment by rgknox** [comment]
Hi @mariuslam 

Is it possible that you are getting zeros included in the average from non-fates columns?  

If you want output that is only an average over FATES sites, there are two things you need to do:

1) set flushval = hio_ignore_val , here: https://github.com/mariuslam/Fates_single_site/blob/c885dee7074ce2ebc32febbcd041f1bd944485cf/main/FatesHistoryInterfaceMod.F90#L4287
This setting tells the averaging routines on the CLM side of the code, as well as the netcdf writing utilities, that all fields should be intiialized with the "ignore" value, ie a value not to be included.

2) if you have a diagnostic that is created by adding or incrementing over a loop, like in your case, you then need to zero the array indices that are relevant to your diagnostic.  I think this would be all fates sites (ie the indices indexed via counter "io_si") and the associated PFT indices that have the PFT active on that site. The key is to zero before the patch loop starts around 2174.  Even better, I would only zero on the PFT indices that are present on that site.  So perhaps around line 2174, before the patch loop, loop through the PFTs, and if the pft_fraction is > 0, then zero the variable.

https://github.com/mariuslam/Fates_single_site/blob/c885dee7074ce2ebc32febbcd041f1bd944485cf/main/FatesHistoryInterfaceMod.F90#L2174

Hopefully this solves your problem, I didn't see any other issues, but can take another look if this doesn't fix the problem.

**Comment by mariuslam** [comment]
Hi @rgknox , 

Thanks for the detailed explanation! 

Adding this did the trick: 
         do ft = 1, numpft
           if (ncohort_pft(ft)>0._r8)then
              hio_hardlevel_si_pft(io_si,ft)=0._r8
              hio_hardGRF_si_pft(io_si,ft)=0._r8
           endif
         enddo
