### ISSUE TITLE
Non-zero frost mortality at the beginning of the simulation

### ISSUE THREAD

**Issue by mpaiao** [NGEET/fates#781]
I noticed that all my simulations have non-zero frost mortality at the first time step. All of them are for lowland sites near the Equator, where the temperature never gets near freezing. Below is an example for a simulation at Paracou, but it happens in other places and settings too.

[m8-tspft-D0006_ParacouEGHD_CLM_FATES.pdf](https://github.com/NGEET/fates/files/7238740/m8-tspft-D0006_ParacouEGHD_CLM_FATES.pdf)

Potentially a some variable that is not correctly initialised?

**Comment by glemieux** [comment]
@mpaiao, now that the running means PR #724 has been integrated with [sci.1.52.0_api.20.0.0](https://github.com/NGEET/fates/releases/tag/sci.1.52.0_api.20.0.0), can you check to see if this issue presents itself (without using the fix in #816)?  Note that this update requires [ctsm5.1.dev066](https://github.com/ESCOMP/CTSM/releases/tag/ctsm5.1.dev066).

Per @rgknox, the relevant fixes is here in the same place as your frost mortality fix:
https://github.com/NGEET/fates/blob/b27149270b459fc2518dc2a5bacfc48ccd256528/biogeochem/EDMortalityFunctionsMod.F90#L174

The initialization is here;
https://github.com/NGEET/fates/blob/b27149270b459fc2518dc2a5bacfc48ccd256528/biogeochem/EDPatchDynamicsMod.F90#L2043

Note that it uses `temp_init_veg`, which is updated here:
https://github.com/NGEET/fates/blob/b27149270b459fc2518dc2a5bacfc48ccd256528/biogeochem/EDPatchDynamicsMod.F90#L2024

**Comment by mpaiao** [comment]
@glemieux @rgknox I think initializing the temperature with 15°C should fix the issue. I guess a quick test is to see if any frost mortality occurs on the first day of simulation for a tropical place with [sci.1.52.0_api.20.0.0](https://github.com/NGEET/fates/releases/tag/sci.1.52.0_api.20.0.0). If frost mortality is zero, then #816 is not needed.
