### ISSUE TITLE
Leaf and root litter fines history variables are reversed.

### ISSUE THREAD

**Issue by JoshuaRady** [NGEET/fates#808]
The following pointer references in FatesHistoryInterfaceMod.F90 are crossed causing the values of LITTER_FINES_AG_ELEM and LITTER_FINES_BG_ELEM history output variables to be reversed.
https://github.com/NGEET/fates/blob/5d449e4ab393cf5cd48ed0a736b4ace0ffe740d7/main/FatesHistoryInterfaceMod.F90#L1926-L1927
Obviously, this is a simple fix.  I can put in a pull request, but will need to finish some work on my current branch before I can get to that.

**Comment by JoshuaRady** [comment]
I thought this was timely with @adrifoster's output variable presentation going on today.

**Comment by adrifoster** [comment]
@JoshuaRady thanks for catching this! I have just fixed this on my branch, and so this will be fixed with the ongoing PR.

**Comment by JoshuaRady** [comment]
This issue has been resolved with the merger of Pull Request #802.
