### ISSUE TITLE
Move calculation of frac_lai to outside the hlm_numSWb loop

### ISSUE THREAD

**Issue by adrifoster** [NGEET/fates#843]
In looking at the radiation code, I noticed that we are potentially unnecessarily recalculating frac_lai and frac_sai for visible and NIR bands (https://github.com/NGEET/fates/blob/7edf030f499b3612a8439851929470e72a0bfe49/biogeophys/EDSurfaceAlbedoMod.F90#L321):

          do  iv = 1, currentPatch%nrad(L,ft)
             if (currentPatch%canopy_area_profile(L,ft,iv) > 0._r8)then
                currentPatch%canopy_mask(L,ft) = 1
                ! layer level reflectance qualities
                do ib = 1,hlm_numSWb !vis, nir
                   if(currentPatch%elai_profile(L,ft,iv)+ currentPatch%esai_profile(L,ft,iv).gt.0.0_r8) then
                      frac_lai = currentPatch%elai_profile(L,ft,iv)/&
                           (currentPatch%elai_profile(L,ft,iv)+ currentPatch%esai_profile(L,ft,iv))
                   else
                      frac_lai = 1.0_r8
                   endif
                   !frac_lai = 1.0_r8 ! make the same as previous codebase, in theory.
                   frac_sai = 1.0_r8 - frac_lai

These calculations occur inside the do ib = 1, hlm_numSWb loop, but I don't think they are actually affected by the ib value. Should we move this to just before the do ib... loop? It may save us a modicum of computation time, and helps with code understandability.

Alternatively, I may be wrong! I conferred with @glemieux, but if others could chime in that would be helpful!

**Comment by rgknox** [comment]
we checked in on this in the software meeting, and there was agreement with  @adrifoster that her plan to improve the algorithm is solid

**Comment by adrifoster** [comment]
I think we can close this now!
