### ISSUE TITLE
update error message when age tracking is required

### ISSUE THREAD

**Issue by adamhb** [NGEET/fates#902]
When age tracking is required (but not switched on) fates raises an error flag instructing the user to set "hlm_use_cohort_age_tracking" to "true". The new namelist option for this is "use_fates_cohort_age_tracking". The name in the error message just needs to be updated.

**Comment by JessicaNeedham** [comment]
Good find, thanks @adamhb. This will also need to be updated in the warning about using age tracking with inventory init.
