### ISSUE TITLE
clarify units description in "bleaf" subroutine

### ISSUE THREAD

**Issue by adamhb** [NGEET/fates#968]
The bleaf subroutine predicts plant leaf biomass in units of KgC, not biomass. We should probably update the units description for "bl" [here](https://github.com/NGEET/fates/blob/main/biogeochem/FatesAllometryMod.F90#L556) to say "KgC" rather than "Kg" just to make it more explicit.

**Comment by rgknox** [comment]
yeah, good point, maybe we can sneak this fix and the sapwood comment fix into another PR that is in queue
